//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by editres.rc
//
#define IDPREVIEW                       3
#define IDD_EDFILEOPEN                  101
#define IDD_EDITOR_PAGE                 102
#define IDB_LIGHTBULB                   102
#define IDM_POPUP_HLINK                 103
#define IDD_TIP                         103
#define IDD_HLINK_PROPERTIES            105
#define IDS_HLINK_PROPERTIES            105
#define IDS_RICHED_LOAD_FAIL            108
#define IDI_EDITPAD                     128
#define IDI_EDITPADTYPE                 129
#define IDC_HLINK                       130
#define IDI_EDITPADRICHTYPE             130
#define IDI_EDITPADBINTYPE              131
#define IDC_HLINK_BAD                   131
#define IDI_HLINK_URL                   132
#define IDD_SPLASH                      157
#define IDC_STATIC1                     158
#define IDB_BITMAP48                    162
#define IDS_TIP_DIDYOUKNOW              301
#define IDS_TIP_FILE_ABSENT             302
#define IDS_TIP_FILE_CORRUPT            303
#define IDB_LIGHTBULB2                  344
#define IDC_ME                          1000
#define IDC_BULB                        1000
#define IDC_ANDREI                      1001
#define IDC_STARTUP                     1001
#define IDR_POPUP_HEX_EDIT              1001
#define IDC_SVEN                        1002
#define IDC_INSERT_TABS                 1002
#define IDC_NEXTTIP                     1002
#define IDC_IMAGE                       1002
#define IDC_STAS                        1003
#define IDC_INSERT_SPACES               1003
#define IDC_DESC                        1003
#define IDC_MARKO                       1004
#define IDC_TAB_SIZE                    1004
#define IDC_TIPSTRING                   1004
#define IDC_ADOLF                       1005
#define IDC_NAME                        1005
#define IDC_SHOW_TABS                   1005
#define IDC_NUMBER                      1005
#define IDC_FRANKY                      1006
#define IDC_URL_PROMPT                  1006
#define IDC_AUTOINDENT                  1006
#define IDC_TEXT                        1006
#define IDC_URL                         1007
#define IDC_BACKSP_AT_BOL               1007
#define IDC_ENCODING                    1007
#define IDC_SELOM                       1008
#define IDC_SEL_MARGIN                  1008
#define IDC_FORMAT                      1008
#define IDC_NONE                        1009
#define IDC_ASP                         1010
#define IDC_HANS                        1010
#define IDC_BASIC                       1011
#define IDC_MICHAEL                     1011
#define IDC_BATCH                       1012
#define IDC_ROBERTO                     1012
#define IDC_C                           1013
#define IDC_AUTODCL                     1014
#define IDC_ROBERTO2                    1013
#define IDC_JOSH                        1013
#define IDC_FORTRAN                     1015
#define IDC_EXTENSIONS                  1014
#define IDC_JAN                         1014
#define IDC_HTML                        1016
#define IDC_PAUL                        1015
#define IDC_INSTALLSHIELD               1017
#define IDC_CRISTI                      1017
#define IDC_JAVA                        1018
#define IDC_AUTOLISP                    1019
#define IDC_WITOLD                      1018
#define IDC_MFCCODEGURU                 1019
#define IDC_PASCAL                      1020
#define IDC_PERL                        1021
#define IDC_PHP                         1022
#define IDC_PYTHON                      1023
#define IDC_RSRC                        1024
#define IDC_REXX                        1025
#define IDC_BIGICON                     1023
#define IDC_SGML                        1026
#define IDC_SH                          1027
#define IDC_SIOD                        1028
#define IDC_SQL                         1029
#define IDC_TCL                         1030
#define IDC_TEX                         1031
#define IDC_SELECT_ALL                  1032
#define IDC_UNSELECT_ALL                1033
#define IDC_BRACES_NO                   1032
#define IDC_BRACES_ANSI                 1033
#define IDC_BRACES_GNU                  1034
#define IDC_EOLN_AUTO                   1035
#define IDC_EOLN_DOS                    1036
#define IDC_EOLN_UNIX                   1037
#define IDC_EOLN_MAC                    1038
#define IDC_FNBRACE                     1039
#define IDC_WORDWRAP                    1040
#define IDC_MORE                        1041
#define IDC_EDITPAGE1                   1042
#define IDC_SRC                         1043
#define IDC_ALPHA_ONLY                  1044
#define IDC_PREVIEW                     1045
#define IDC_RECODE                      1046
#define stc32                           0x045f
#define IDC_EDIT_TEXT                   8601
#define IDD_EDIT_GOTO                   8603
#define IDD_EDIT_CHARCONV               8604
#define IDD_EDITOR_PAGE1                8605
#define IDD_EDITOR_PAGE2                8606
#define IDC_DEST                        8606
#define IDD_EDFILEADD                   8607
#define IDD_EDITOR_PAGE3                8608
#define IDS_MENU_UNDO_FORMAT            8615
#define IDS_MENU_REDO_FORMAT            8616
#define IDS_MENU_UNDO_DEFAULT           8617
#define IDS_MENU_REDO_DEFAULT           8618
#define IDS_EDITOP_UNKNOWN              8619
#define IDS_EDITOP_PASTE                8620
#define IDS_EDITOP_DELSELECTION         8621
#define IDS_EDITOP_CUT                  8622
#define IDS_EDITOP_DELETE               8623
#define IDS_EDITOP_TYPING               8624
#define IDS_EDITOP_BACKSPACE            8625
#define IDS_EDITOP_INDENT               8626
#define IDS_EDITOP_DRAGDROP             8627
#define IDS_EDITOP_REPLACE              8628
#define IDS_EDITOP_AUTOINDENT           8629
#define IDS_EDITOP_AUTOCOMPLETE         8630
#define IDS_EDITOP_AUTOEXPAND           8631
#define IDS_EDITOP_LOWERCASE            8632
#define IDS_EDITOP_UPPERCASE            8633
#define IDS_EDITOP_SWAPCASE             8634
#define IDS_EDITOP_CAPITALIZE           8635
#define IDS_EDITOP_SENTENCIZE           8636
#define IDS_EDITOP_RECODE               8637
#define IDS_EDITOP_SPELL                8638
#define IDS_FIND_INCREMENTAL_FORWARD    8640
#define IDS_FIND_INCREMENTAL_BACKWARD   8641
#define IDS_FIND_INCREMENTAL_FAILED     8642
#define IDS_SHEET_OPTIONS               8700
#define IDR_DEFAULT_ACCEL               20001
#define IDR_RTF_ACCEL                   20003
#define ID_POPUP_EDIT                   20032
#define ID_POPUP_PRINT                  20033
#define ID_POPUP_OPEN                   20034
#define ID_POPUP_COPYSHORTCUT           20035
#define ID_POPUP_ADDTOFAVORITES         20036
#define ID_POPUP_ADDTODESKTOP           20037
#define ID_POPUP_PROPERTIES             20038
#define ID_VIEW_FULL_SCREEN             20064
#define ID_CHAR_BOLD                    20080
#define ID_TOOLS_SPELLING               20081
#define ID_TOOLS_SPELLING_SET           20082
#define ID_CHAR_ITALIC                  20083
#define ID_TOOLS_CHARCODING             20084
#define ID_CHAR_UNDERLINE               20085
#define ID_PARA_LEFT                    20086
#define ID_PARA_CENTER                  20087
#define ID_PARA_RIGHT                   20088
#define ID_FILE_RELOAD                  20999
#define ID_EDIT_FIRST                   21000
#define ID_EDIT_DELETE                  21000
#define ID_EDIT_DELETE_BACK             21001
#define ID_EDIT_DELETE_WORD             21002
#define ID_EDIT_DELETE_WORD_BACK        21003
#define ID_EDIT_TAB                     21004
#define ID_EDIT_UNTAB                   21005
#define ID_EDIT_SWITCH_OVRMODE          21006
#define ID_EDIT_CHAR_LEFT               21100
#define ID_EDIT_EXT_CHAR_LEFT           21101
#define ID_EDIT_CHAR_RIGHT              21102
#define ID_EDIT_EXT_CHAR_RIGHT          21103
#define ID_EDIT_WORD_LEFT               21104
#define ID_EDIT_EXT_WORD_LEFT           21105
#define ID_EDIT_WORD_RIGHT              21106
#define ID_EDIT_EXT_WORD_RIGHT          21107
#define ID_EDIT_LINE_UP                 21108
#define ID_EDIT_EXT_LINE_UP             21109
#define ID_EDIT_LINE_DOWN               21110
#define ID_EDIT_EXT_LINE_DOWN           21111
#define ID_EDIT_SCROLL_UP               21112
#define ID_EDIT_SCROLL_DOWN             21113
#define ID_EDIT_PAGE_UP                 21114
#define ID_EDIT_EXT_PAGE_UP             21115
#define ID_EDIT_PAGE_DOWN               21116
#define ID_EDIT_EXT_PAGE_DOWN           21117
#define ID_EDIT_LINE_END                21118
#define ID_EDIT_EXT_LINE_END            21119
#define ID_EDIT_HOME                    21120
#define ID_EDIT_EXT_HOME                21121
#define ID_EDIT_TEXT_BEGIN              21122
#define ID_EDIT_EXT_TEXT_BEGIN          21123
#define ID_EDIT_TEXT_END                21124
#define ID_EDIT_EXT_TEXT_END            21125
#define ID_EDIT_TOGGLE_BOOKMARK0        21200
#define ID_EDIT_TOGGLE_BOOKMARK1        21201
#define ID_EDIT_TOGGLE_BOOKMARK2        21202
#define ID_EDIT_TOGGLE_BOOKMARK3        21203
#define ID_EDIT_TOGGLE_BOOKMARK4        21204
#define ID_EDIT_TOGGLE_BOOKMARK5        21205
#define ID_EDIT_TOGGLE_BOOKMARK6        21206
#define ID_EDIT_TOGGLE_BOOKMARK7        21207
#define ID_EDIT_TOGGLE_BOOKMARK8        21208
#define ID_EDIT_TOGGLE_BOOKMARK9        21209
#define ID_EDIT_GO_BOOKMARK0            21210
#define ID_EDIT_GO_BOOKMARK1            21211
#define ID_EDIT_GO_BOOKMARK2            21212
#define ID_EDIT_GO_BOOKMARK3            21213
#define ID_EDIT_GO_BOOKMARK4            21214
#define ID_EDIT_GO_BOOKMARK5            21215
#define ID_EDIT_GO_BOOKMARK6            21216
#define ID_EDIT_GO_BOOKMARK7            21217
#define ID_EDIT_GO_BOOKMARK8            21218
#define ID_EDIT_GO_BOOKMARK9            21219
#define ID_EDIT_CLEAR_BOOKMARKS         21220
#define ID_EDIT_SET_BREAKPOINT          21221
#define ID_EDIT_ENABLE_BREAKPOINT       21222
#define ID_EDIT_GOTO_LAST_CHANGE        21227
#define ID_EDIT_FIND_INCREMENTAL_FORWARD 21228
#define ID_EDIT_FIND_INCREMENTAL_BACKWARD 21229
#define ID_EDIT_AUTOCOMPLETE            21300
#define ID_EDIT_AUTOEXPAND              21301
#define ID_EDIT_MATCHBRACE              21302
#define ID_EDIT_LOWERCASE               21303
#define ID_EDIT_UPPERCASE               21304
#define ID_EDIT_CAPITALIZE              21305
#define ID_EDIT_SENTENCE                21306
#define ID_EDIT_SWAPCASE                21307
#define ID_EDIT_GOTO                    21308
#define ID_VIEW_OPTIONS                 21400
#define ID_VIEW_TOGGLE_SRC_HDR          21401
#define ID_VIEW_SELMARGIN               21402
#define ID_DATE_TIME                    21403
#define ID_READ_ONLY                    21405
#define ID_SOURCE_PLAIN                 21500
#define ID_SOURCE_ASP                   21501
#define ID_SOURCE_BASIC                 21502
#define ID_SOURCE_BATCH                 21503
#define ID_SOURCE_C                     21504
#define ID_SOURCE_AUTODCL               21505
#define ID_SOURCE_FORTRAN               21506
#define ID_SOURCE_HTML                  21507
#define ID_SOURCE_INSTALLSHIELD         21508
#define ID_SOURCE_JAVA                  21509
#define ID_SOURCE_AUTOLISP              21510
#define ID_SOURCE_PASCAL                21511
#define ID_SOURCE_PERL                  21512
#define ID_SOURCE_PHP                   21513
#define ID_SOURCE_PYTHON                21514
#define ID_SOURCE_REXX                  21515
#define ID_SOURCE_RSRC                  21516
#define ID_SOURCE_SGML                  21517
#define ID_SOURCE_SH                    21518
#define ID_SOURCE_SIOD                  21519
#define ID_SOURCE_SQL                   21520
#define ID_SOURCE_TCL                   21521
#define ID_SOURCE_TEX                   21522
#define ID_EDIT_INDICATOR_READ          21901
#define ID_EDIT_INDICATOR_CRLF          21902
#define ID_EDIT_INDICATOR_POSITION      21903
#define ID_INDICATOR_TIME               21904
#define ID_FORCE_REDRAW                 21999
#define ID_EDIT_LAST                    21999
#define ID_HELP_TIPOFTHEDAY             39000
#define ID_FORMAT_SHOW_ADDRESS          40001
#define ID_FORMAT_SHOW_HEX              40002
#define ID_FORMAT_SHOW_ASCII            40003
#define ID_FORMAT_WIDE_ADDRESS          40004
#define ID_FORMAT_BPR_FIRST             40011
#define ID_FORMAT_BPR_1                 40011
#define ID_FORMAT_BPR_2                 40012
#define ID_FORMAT_BPR_3                 40013
#define ID_FORMAT_BPR_4                 40014
#define ID_FORMAT_BPR_5                 40015
#define ID_FORMAT_BPR_6                 40016
#define ID_FORMAT_BPR_7                 40017
#define ID_FORMAT_BPR_8                 40018
#define ID_FORMAT_BPR_9                 40019
#define ID_FORMAT_BPR_10                40020
#define ID_FORMAT_BPR_11                40021
#define ID_FORMAT_BPR_12                40022
#define ID_FORMAT_BPR_13                40023
#define ID_FORMAT_BPR_14                40024
#define ID_FORMAT_BPR_15                40025
#define ID_FORMAT_BPR_16                40026
#define ID_FORMAT_BPR_LAST              40026

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1002
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1049
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
