//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by editres.rc
//
#define IDPREVIEW                       3
#define IDD_ABOUTBOX                    100
#define IDD_EDFILEOPEN                  101
#define IDD_EDITOR_PAGE                 102
#define IDB_LIGHTBULB                   102
#define IDM_POPUP_HLINK                 103
#define IDD_TIP                         103
#define IDD_HLINK_PROPERTIES            105
#define IDS_HLINK_PROPERTIES            105
#define IDS_RICHED_LOAD_FAIL            108
#define IDI_EDITPAD                     128
#define IDI_EDITPADTYPE                 129
#define IDC_HLINK                       130
#define IDI_EDITPADRICHTYPE             130
#define IDI_EDITPADBINTYPE              131
#define IDC_HLINK_BAD                   131
#define IDI_HLINK_URL                   132
#define IDD_SPLASH                      157
#define IDC_STATIC1                     158
#define IDB_BITMAP48                    162
#define IDS_TIP_DIDYOUKNOW              301
#define IDS_TIP_FILE_ABSENT             302
#define IDS_TIP_FILE_CORRUPT            303
#define IDB_LIGHTBULB2                  344
#define IDC_ME                          1000
#define IDC_BULB                        1000
#define IDC_ANDREI                      1001
#define IDC_STARTUP                     1001
#define IDR_POPUP_HEX_EDIT              1001
#define IDC_SVEN                        1002
#define IDC_INSERT_TABS                 1002
#define IDC_NEXTTIP                     1002
#define IDC_IMAGE                       1002
#define IDC_STAS                        1003
#define IDC_INSERT_SPACES               1003
#define IDC_DESC                        1003
#define IDC_MARKO                       1004
#define IDC_TAB_SIZE                    1004
#define IDC_TIPSTRING                   1004
#define IDC_ADOLF                       1005
#define IDC_NAME                        1005
#define IDC_SHOW_TABS                   1005
#define IDC_NUMBER                      1005
#define IDC_FRANKY                      1006
#define IDC_URL_PROMPT                  1006
#define IDC_AUTOINDENT                  1006
#define IDC_TEXT                        1006
#define IDC_URL                         1007
#define IDC_BACKSP_AT_BOL               1007
#define IDC_ENCODING                    1007
#define IDC_SELOM                       1008
#define IDC_SEL_MARGIN                  1008
#define IDC_FORMAT                      1008
#define IDC_NONE                        1009
#define IDC_ASP                         1010
#define IDC_HANS                        1010
#define IDC_BASIC                       1011
#define IDC_MICHAEL                     1011
#define IDC_BATCH                       1012
#define IDC_ROBERTO                     1012
#define IDC_C                           1013
#define IDC_AUTODCL                     1014
#define IDC_ROBERTO2                    1013
#define IDC_JOSH                        1013
#define IDC_FORTRAN                     1015
#define IDC_EXTENSIONS                  1014
#define IDC_JAN                         1014
#define IDC_HTML                        1016
#define IDC_PAUL                        1015
#define IDC_INSTALLSHIELD               1017
#define IDC_CRISTI                      1017
#define IDC_JAVA                        1018
#define IDC_AUTOLISP                    1019
#define IDC_WITOLD                      1018
#define IDC_MFCCODEGURU                 1019
#define IDC_PASCAL                      1020
#define IDC_PERL                        1021
#define IDC_PHP                         1022
#define IDC_PYTHON                      1023
#define IDC_RSRC                        1024
#define IDC_REXX                        1025
#define IDC_BIGICON                     1023
#define IDC_SGML                        1026
#define IDC_SH                          1027
#define IDC_SIOD                        1028
#define IDC_SQL                         1029
#define IDC_TCL                         1030
#define IDC_TEX                         1031
#define IDC_SELECT_ALL                  1032
#define IDC_UNSELECT_ALL                1033
#define IDC_BRACES_NO                   1032
#define IDC_BRACES_ANSI                 1033
#define IDC_BRACES_GNU                  1034
#define IDC_EOLN_AUTO                   1035
#define IDC_EOLN_DOS                    1036
#define IDC_EOLN_UNIX                   1037
#define IDC_EOLN_MAC                    1038
#define IDC_FNBRACE                     1039
#define IDC_WORDWRAP                    1040
#define IDC_MORE                        1041
#define IDC_EDITPAGE1                   1042
#define IDC_SRC                         1043
#define IDC_ALPHA_ONLY                  1044
#define IDC_PREVIEW                     1045
#define IDC_RECODE                      1046
#define stc32                           0x045f
#define IDD_EDIT_FIND                   8601
#define IDD_EDIT_REPLACE                8602
#define IDC_EDIT_WHOLE_WORD             8603
#define IDD_EDIT_GOTO                   8603
#define IDC_EDIT_MATCH_CASE             8604
#define IDD_EDIT_CHARCONV               8604
#define IDC_EDIT_TEXT                   8605
#define IDD_EDITOR_PAGE1                8605
#define IDC_EDIT_REGEXP                 8606
#define IDS_EDIT_TEXT_NOT_FOUND         8606
#define IDD_EDITOR_PAGE2                8606
#define IDC_DEST                        8606
#define IDC_EDIT_REPLACE                8607
#define IDD_EDFILEADD                   8607
#define IDC_EDIT_REPLACE_ALL            8608
#define IDD_EDITOR_PAGE3                8608
#define IDC_EDIT_REPLACE_WITH           8609
#define IDC_EDIT_SKIP                   8610
#define IDC_EDIT_DIRECTION_UP           8611
#define IDC_EDIT_DIRECTION_DOWN         8612
#define IDC_EDIT_SCOPE_SELECTION        8613
#define IDC_EDIT_SCOPE_WHOLE_FILE       8614
#define IDS_MENU_UNDO_FORMAT            8615
#define IDS_MENU_REDO_FORMAT            8616
#define IDS_MENU_UNDO_DEFAULT           8617
#define IDS_MENU_REDO_DEFAULT           8618
#define IDS_EDITOP_UNKNOWN              8619
#define IDS_EDITOP_PASTE                8620
#define IDS_EDITOP_DELSELECTION         8621
#define IDS_EDITOP_CUT                  8622
#define IDS_EDITOP_DELETE               8623
#define IDS_EDITOP_TYPING               8624
#define IDS_EDITOP_BACKSPACE            8625
#define IDS_EDITOP_INDENT               8626
#define IDS_EDITOP_DRAGDROP             8627
#define IDS_EDITOP_REPLACE              8628
#define IDS_EDITOP_AUTOINDENT           8629
#define IDS_EDITOP_AUTOCOMPLETE         8630
#define IDS_EDITOP_AUTOEXPAND           8631
#define IDS_EDITOP_LOWERCASE            8632
#define IDS_EDITOP_UPPERCASE            8633
#define IDS_EDITOP_SWAPCASE             8634
#define IDS_EDITOP_CAPITALIZE           8635
#define IDS_EDITOP_SENTENCIZE           8636
#define IDS_EDITOP_RECODE               8637
#define IDS_EDITOP_SPELL                8638
#define IDS_FIND_INCREMENTAL_FORWARD    8640
#define IDS_FIND_INCREMENTAL_BACKWARD   8641
#define IDS_FIND_INCREMENTAL_FAILED     8642
#define IDS_SHEET_OPTIONS               8700
#define IDR_MARGIN_CURSOR               22900
#define IDR_DEFAULT_ACCEL               22901
#define IDR_MARGIN_ICONS                22902
#define IDR_RTF_ACCEL                   22903
#define ID_EDIT_DELETE_WORD             32771
#define ID_POPUP_EDIT                   32774
#define ID_POPUP_PRINT                  32775
#define ID_POPUP_OPEN                   32780
#define ID_POPUP_COPYSHORTCUT           32781
#define ID_POPUP_ADDTOFAVORITES         32782
#define ID_POPUP_ADDTODESKTOP           32783
#define ID_POPUP_PROPERTIES             32784
#define ID_VIEW_FULL_SCREEN             32791
#define ID_CHAR_BOLD                    32799
#define ID_TOOLS_SPELLING               32800
#define ID_TOOLS_SPELLING_SET           32801
#define ID_CHAR_ITALIC                  32802
#define ID_TOOLS_CHARCODING             32803
#define ID_CHAR_UNDERLINE               32804
#define ID_PARA_LEFT                    32805
#define ID_PARA_CENTER                  32806
#define ID_PARA_RIGHT                   32807
#define ID_FILE_RELOAD                  36999
#define ID_EDIT_FIRST                   37000
#define ID_EDIT_DELETE                  37000
#define ID_EDIT_DELETE_BACK             37001
#define ID_EDIT_DELETE_WORD_BACK        37002
#define ID_EDIT_TAB                     37003
#define ID_EDIT_UNTAB                   37004
#define ID_EDIT_SWITCH_OVRMODE          37005
#define ID_EDIT_CHAR_LEFT               37100
#define ID_EDIT_EXT_CHAR_LEFT           37101
#define ID_EDIT_CHAR_RIGHT              37102
#define ID_EDIT_EXT_CHAR_RIGHT          37103
#define ID_EDIT_WORD_LEFT               37104
#define ID_EDIT_EXT_WORD_LEFT           37105
#define ID_EDIT_WORD_RIGHT              37106
#define ID_EDIT_EXT_WORD_RIGHT          37107
#define ID_EDIT_LINE_UP                 37108
#define ID_EDIT_EXT_LINE_UP             37109
#define ID_EDIT_LINE_DOWN               37110
#define ID_EDIT_EXT_LINE_DOWN           37111
#define ID_EDIT_SCROLL_UP               37112
#define ID_EDIT_SCROLL_DOWN             37113
#define ID_EDIT_PAGE_UP                 37114
#define ID_EDIT_EXT_PAGE_UP             37115
#define ID_EDIT_PAGE_DOWN               37116
#define ID_EDIT_EXT_PAGE_DOWN           37117
#define ID_EDIT_LINE_END                37118
#define ID_EDIT_EXT_LINE_END            37119
#define ID_EDIT_HOME                    37120
#define ID_EDIT_EXT_HOME                37121
#define ID_EDIT_TEXT_BEGIN              37122
#define ID_EDIT_EXT_TEXT_BEGIN          37123
#define ID_EDIT_TEXT_END                37124
#define ID_EDIT_EXT_TEXT_END            37125
#define ID_EDIT_FIND_PREVIOUS           37126
#define ID_EDIT_TOGGLE_BOOKMARK0        37200
#define ID_EDIT_TOGGLE_BOOKMARK1        37201
#define ID_EDIT_TOGGLE_BOOKMARK2        37202
#define ID_EDIT_TOGGLE_BOOKMARK3        37203
#define ID_EDIT_TOGGLE_BOOKMARK4        37204
#define ID_EDIT_TOGGLE_BOOKMARK5        37205
#define ID_EDIT_TOGGLE_BOOKMARK6        37206
#define ID_EDIT_TOGGLE_BOOKMARK7        37207
#define ID_EDIT_TOGGLE_BOOKMARK8        37208
#define ID_EDIT_TOGGLE_BOOKMARK9        37209
#define ID_EDIT_GO_BOOKMARK0            37210
#define ID_EDIT_GO_BOOKMARK1            37211
#define ID_EDIT_GO_BOOKMARK2            37212
#define ID_EDIT_GO_BOOKMARK3            37213
#define ID_EDIT_GO_BOOKMARK4            37214
#define ID_EDIT_GO_BOOKMARK5            37215
#define ID_EDIT_GO_BOOKMARK6            37216
#define ID_EDIT_GO_BOOKMARK7            37217
#define ID_EDIT_GO_BOOKMARK8            37218
#define ID_EDIT_GO_BOOKMARK9            37219
#define ID_EDIT_CLEAR_BOOKMARKS         37220
#define ID_EDIT_SET_BREAKPOINT          37221
#define ID_EDIT_ENABLE_BREAKPOINT       37222
#define ID_EDIT_TOGGLE_BOOKMARK         37223
#define ID_EDIT_GOTO_NEXT_BOOKMARK      37224
#define ID_EDIT_GOTO_PREV_BOOKMARK      37225
#define ID_EDIT_CLEAR_ALL_BOOKMARKS     37226
#define ID_EDIT_GOTO_LAST_CHANGE        37227
#define ID_EDIT_FIND_INCREMENTAL_FORWARD 37228
#define ID_EDIT_FIND_INCREMENTAL_BACKWARD 37229
#define ID_EDIT_AUTOCOMPLETE            37300
#define ID_EDIT_AUTOEXPAND              37301
#define ID_EDIT_MATCHBRACE              37302
#define ID_EDIT_LOWERCASE               37303
#define ID_EDIT_UPPERCASE               37304
#define ID_EDIT_CAPITALIZE              37305
#define ID_EDIT_SENTENCE                37306
#define ID_EDIT_SWAPCASE                37307
#define ID_EDIT_GOTO                    37308
#define ID_VIEW_OPTIONS                 37400
#define ID_VIEW_TOGGLE_SRC_HDR          37401
#define ID_VIEW_SELMARGIN               37402
#define ID_DATE_TIME                    37403
#define ID_VIEW_WORDWRAP                37404
#define ID_READ_ONLY                    37405
#define ID_SOURCE_PLAIN                 37500
#define ID_SOURCE_ASP                   37501
#define ID_SOURCE_BASIC                 37502
#define ID_SOURCE_BATCH                 37503
#define ID_SOURCE_C                     37504
#define ID_SOURCE_AUTODCL               37505
#define ID_SOURCE_FORTRAN               37506
#define ID_SOURCE_HTML                  37507
#define ID_SOURCE_INSTALLSHIELD         37508
#define ID_SOURCE_JAVA                  37509
#define ID_SOURCE_AUTOLISP              37510
#define ID_SOURCE_PASCAL                37511
#define ID_SOURCE_PERL                  37512
#define ID_SOURCE_PHP                   37513
#define ID_SOURCE_PYTHON                37514
#define ID_SOURCE_REXX                  37515
#define ID_SOURCE_RSRC                  37516
#define ID_SOURCE_SGML                  37517
#define ID_SOURCE_SH                    37518
#define ID_SOURCE_SIOD                  37519
#define ID_SOURCE_SQL                   37520
#define ID_SOURCE_TCL                   37521
#define ID_SOURCE_TEX                   37522
#define ID_EDIT_INDICATOR_READ          37901
#define ID_EDIT_INDICATOR_CRLF          37902
#define ID_EDIT_INDICATOR_POSITION      37903
#define ID_INDICATOR_TIME               37904
#define ID_FORCE_REDRAW                 37999
#define ID_EDIT_LAST                    37999
#define ID_HELP_TIPOFTHEDAY             39000
#define ID_FORMAT_SHOW_ADDRESS          40001
#define ID_FORMAT_SHOW_HEX              40002
#define ID_FORMAT_SHOW_ASCII            40003
#define ID_FORMAT_WIDE_ADDRESS          40004
#define ID_FORMAT_BPR_FIRST             40011
#define ID_FORMAT_BPR_1                 40011
#define ID_FORMAT_BPR_2                 40012
#define ID_FORMAT_BPR_3                 40013
#define ID_FORMAT_BPR_4                 40014
#define ID_FORMAT_BPR_5                 40015
#define ID_FORMAT_BPR_6                 40016
#define ID_FORMAT_BPR_7                 40017
#define ID_FORMAT_BPR_8                 40018
#define ID_FORMAT_BPR_9                 40019
#define ID_FORMAT_BPR_10                40020
#define ID_FORMAT_BPR_11                40021
#define ID_FORMAT_BPR_12                40022
#define ID_FORMAT_BPR_13                40023
#define ID_FORMAT_BPR_14                40024
#define ID_FORMAT_BPR_15                40025
#define ID_FORMAT_BPR_16                40026
#define ID_FORMAT_BPR_LAST              40026

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1002
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1049
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
