set MAJOR=2
set MINOR=13
set REVISION=13
set PATCHLEVEL=5
set PRIVATEBUILD=jp-5

set RCVER=%MAJOR%.%MINOR%.%REVISION%.%PATCHLEVEL%
rem set STRVER=%MAJOR%.%MINOR%.%REVISION%.%PATCHLEVEL%
set STRVER=%MAJOR%.%MINOR%.%REVISION%
set APPVER=%STRVER%+-%PRIVATEBUILD%
set SAFEAPPVER=%STRVER%-%PRIVATEBUILD%

