set MAJOR=2
set MINOR=14
set REVISION=0
set PATCHLEVEL=94
set PRIVATEBUILD=jp-94

set RCVER=%MAJOR%.%MINOR%.%REVISION%.%PATCHLEVEL%
rem set STRVER=%MAJOR%.%MINOR%.%REVISION%.%PATCHLEVEL%
set STRVER=%MAJOR%.%MINOR%.%REVISION%
set APPVER=%STRVER%+-%PRIVATEBUILD%
set SAFEAPPVER=%STRVER%-%PRIVATEBUILD%

