name: Question
description: Ask a question about using WinMerge.
title: "[QUESTION] "
labels:
  - question

body:
  - type: markdown
    attributes:
      value: |
        Ask a question about WinMerge usage or behavior.

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to ask?
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details (optional)
      description: Any additional context, examples, or screenshots.
    validations:
      required: false
