#define AND                              1
#define OR                               2
#define NOT                              3
#define TRUE_LITERAL                     4
#define FALSE_LITERAL                    5
#define INTEGER_LITERAL                  6
#define STRING_LITERAL                   7
#define SIZE_LITERAL                     8
#define DATETIME_LITERAL                 9
#define TIME_LITERAL                    10
#define VERSION_LITERAL                 11
#define IDENTIFIER                      12
#define EQ                              13
#define NE                              14
#define LT                              15
#define LE                              16
#define GT                              17
#define GE                              18
#define CONTAINS                        19
#define MATCHES                         20
#define LPAREN                          21
#define RPAREN                          22
#define PLUS                            23
#define MINUS                           24
#define STAR                            25
#define SLASH                           26
#define MOD                             27
#define COMMA                           28
