/* This file is automatically generated by Lemon from input grammar
** source file "E:\dev\winmerge\Src\FilterEngine\FilterParser.y".
*/
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifer prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#line 13 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"

#include "FilterLexer.h"
#include "FilterExpression.h"
#include "FilterEngine.h"
#line 35 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#ifndef AND
#define AND                             1
#define OR                              2
#define NOT                             3
#define TRUE_LITERAL                    4
#define FALSE_LITERAL                   5
#define INTEGER_LITERAL                 6
#define STRING_LITERAL                  7
#define SIZE_LITERAL                    8
#define DATETIME_LITERAL                9
#define DURATION_LITERAL                   10
#define VERSION_LITERAL                11
#define IDENTIFIER                     12
#define EQ                             13
#define NE                             14
#define LT                             15
#define LE                             16
#define GT                             17
#define GE                             18
#define CONTAINS                       19
#define MATCHES                        20
#define LPAREN                         21
#define RPAREN                         22
#define PLUS                           23
#define MINUS                          24
#define STAR                           25
#define SLASH                          26
#define MOD                            27
#define COMMA                          28
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    ParseTOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is ParseTOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    ParseARG_SDECL     A static variable declaration for the %extra_argument
**    ParseARG_PDECL     A parameter declaration for the %extra_argument
**    ParseARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    ParseARG_STORE     Code to store %extra_argument into yypParser
**    ParseARG_FETCH     Code to extract %extra_argument from yypParser
**    ParseCTX_*         As ParseARG_ except for %extra_context
**    YYREALLOC          Name of the realloc() function to use
**    YYFREE             Name of the free() function to use
**    YYDYNSTACK         True if stack space should be extended on heap
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
**    YY_MIN_DSTRCTR     Minimum symbol value that has a destructor
**    YY_MAX_DSTRCTR     Maximum symbol value that has a destructor
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 39
#define YYACTIONTYPE unsigned char
#define ParseTOKENTYPE YYSTYPE
typedef union {
  int yyinit;
  ParseTOKENTYPE yy0;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 100
#endif
#define ParseARG_SDECL  FilterContext* pCtx ;
#define ParseARG_PDECL , FilterContext* pCtx 
#define ParseARG_PARAM ,pCtx 
#define ParseARG_FETCH  FilterContext* pCtx =yypParser->pCtx ;
#define ParseARG_STORE yypParser->pCtx =pCtx ;
#define YYREALLOC realloc
#define YYFREE free
#define YYDYNSTACK 0
#define ParseCTX_SDECL
#define ParseCTX_PDECL
#define ParseCTX_PARAM
#define ParseCTX_FETCH
#define ParseCTX_STORE
#define YYNSTATE             39
#define YYNRULE              39
#define YYNRULE_WITH_ACTION  32
#define YYNTOKEN             29
#define YY_MAX_SHIFT         38
#define YY_MIN_SHIFTREDUCE   62
#define YY_MAX_SHIFTREDUCE   100
#define YY_ERROR_ACTION      101
#define YY_ACCEPT_ACTION     102
#define YY_NO_ACTION         103
#define YY_MIN_REDUCE        104
#define YY_MAX_REDUCE        142
#define YY_MIN_DSTRCTR       0
#define YY_MAX_DSTRCTR       0
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif

/* Macro to determine if stack space has the ability to grow using
** heap memory.
*/
#if YYSTACKDEPTH<=0 || YYDYNSTACK
# define YYGROWABLESTACK 1
#else
# define YYGROWABLESTACK 0
#endif

/* Guarantee a minimum number of initial stack slots.
*/
#if YYSTACKDEPTH<=0
# undef YYSTACKDEPTH
# define YYSTACKDEPTH 2  /* Need a minimum stack size */
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (175)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */   121,  103,  121,    5,   80,   81,   82,   83,   84,   85,
 /*    10 */    86,   87,   37,   36,   35,   35,   35,   21,   21,   34,
 /*    20 */    21,    2,   88,   91,   20,   19,   13,   12,   11,   10,
 /*    30 */     9,    8,    7,    6,    1,   18,   17,   16,   15,   14,
 /*    40 */     5,   80,   81,   82,   83,   84,   85,   86,   87,   37,
 /*    50 */     4,  102,   33,   35,   35,   35,   21,   21,    2,   21,
 /*    60 */   104,   20,    4,   80,   81,   82,   83,   84,   85,   86,
 /*    70 */    87,   37,   36,   35,   35,   35,   21,   21,  135,   21,
 /*    80 */     2,  103,  103,   20,   38,   38,   38,   21,   21,  103,
 /*    90 */    21,  103,   36,   35,   35,   35,   21,   21,  134,   21,
 /*   100 */    32,  107,  107,   21,   21,  103,   21,  106,  106,   21,
 /*   110 */    21,  103,   21,  103,   18,   17,   16,   15,   14,   22,
 /*   120 */    22,  103,   22,   23,   23,  103,   23,   24,   24,  103,
 /*   130 */    24,   25,   25,  103,   25,   26,   26,  103,   26,   27,
 /*   140 */    27,  103,   27,   28,   28,  103,   28,  120,  120,  103,
 /*   150 */   120,  119,  119,  103,  119,  118,  118,  103,  118,   30,
 /*   160 */    30,  103,   30,   31,   31,   89,   31,   29,   29,  103,
 /*   170 */    29,    3,   16,   15,   14,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */    35,   39,   37,    3,    4,    5,    6,    7,    8,    9,
 /*    10 */    10,   11,   12,   30,   31,   32,   33,   34,   35,   36,
 /*    20 */    37,   21,   22,   22,   24,   13,   14,   15,   16,   17,
 /*    30 */    18,   19,   20,    1,   21,   23,   24,   25,   26,   27,
 /*    40 */     3,    4,    5,    6,    7,    8,    9,   10,   11,   12,
 /*    50 */     2,   29,   30,   31,   32,   33,   34,   35,   21,   37,
 /*    60 */     0,   24,    2,    4,    5,    6,    7,    8,    9,   10,
 /*    70 */    11,   12,   30,   31,   32,   33,   34,   35,   36,   37,
 /*    80 */    21,   39,   39,   24,   31,   32,   33,   34,   35,   39,
 /*    90 */    37,   39,   30,   31,   32,   33,   34,   35,   36,   37,
 /*   100 */    38,   32,   33,   34,   35,   39,   37,   32,   33,   34,
 /*   110 */    35,   39,   37,   39,   23,   24,   25,   26,   27,   34,
 /*   120 */    35,   39,   37,   34,   35,   39,   37,   34,   35,   39,
 /*   130 */    37,   34,   35,   39,   37,   34,   35,   39,   37,   34,
 /*   140 */    35,   39,   37,   34,   35,   39,   37,   34,   35,   39,
 /*   150 */    37,   34,   35,   39,   37,   34,   35,   39,   37,   34,
 /*   160 */    35,   39,   37,   34,   35,   22,   37,   34,   35,   39,
 /*   170 */    37,   28,   25,   26,   27,   39,   39,   39,   39,   39,
 /*   180 */    39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
 /*   190 */    39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
 /*   200 */    39,   39,   29,   29,
};
#define YY_SHIFT_COUNT    (38)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (147)
static const unsigned char yy_shift_ofst[] = {
 /*     0 */    37,    0,   37,   37,   37,   37,   37,   59,   59,   59,
 /*    10 */    59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
 /*    20 */    59,   12,   91,   91,   91,   91,   91,   91,   91,   91,
 /*    30 */   147,  147,  143,   60,    1,   32,   48,   13,   32,
};
#define YY_REDUCE_COUNT (20)
#define YY_REDUCE_MIN   (-35)
#define YY_REDUCE_MAX   (133)
static const short yy_reduce_ofst[] = {
 /*     0 */    22,   62,  -17,   42,   53,   69,   75,   85,   89,   93,
 /*    10 */    97,  101,  105,  109,  113,  117,  121,  125,  129,  133,
 /*    20 */   -35,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */   101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
 /*    10 */   101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
 /*    20 */   101,  139,  115,  114,  113,  112,  111,  110,  109,  108,
 /*    30 */   117,  116,  101,  101,  101,  136,  141,  132,  105,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  ParseARG_SDECL                /* A place to hold %extra_argument */
  ParseCTX_SDECL                /* A place to hold %extra_context */
  yyStackEntry *yystackEnd;           /* Last entry in the stack */
  yyStackEntry *yystack;              /* The parser stack */
  yyStackEntry yystk0[YYSTACKDEPTH];  /* Initial stack space */
};
typedef struct yyParser yyParser;

#include <assert.h>
#ifndef NDEBUG
#include <stdio.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void ParseTrace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "AND",
  /*    2 */ "OR",
  /*    3 */ "NOT",
  /*    4 */ "TRUE_LITERAL",
  /*    5 */ "FALSE_LITERAL",
  /*    6 */ "INTEGER_LITERAL",
  /*    7 */ "STRING_LITERAL",
  /*    8 */ "SIZE_LITERAL",
  /*    9 */ "DATETIME_LITERAL",
  /*   10 */ "DURATION_LITERAL",
  /*   11 */ "VERSION_LITERAL",
  /*   12 */ "IDENTIFIER",
  /*   13 */ "EQ",
  /*   14 */ "NE",
  /*   15 */ "LT",
  /*   16 */ "LE",
  /*   17 */ "GT",
  /*   18 */ "GE",
  /*   19 */ "CONTAINS",
  /*   20 */ "MATCHES",
  /*   21 */ "LPAREN",
  /*   22 */ "RPAREN",
  /*   23 */ "PLUS",
  /*   24 */ "MINUS",
  /*   25 */ "STAR",
  /*   26 */ "SLASH",
  /*   27 */ "MOD",
  /*   28 */ "COMMA",
  /*   29 */ "filter_expr",
  /*   30 */ "or_expr",
  /*   31 */ "and_expr",
  /*   32 */ "not_expr",
  /*   33 */ "cmp_expr",
  /*   34 */ "arithmetic",
  /*   35 */ "unary",
  /*   36 */ "expr",
  /*   37 */ "term",
  /*   38 */ "expr_list",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "filter_expr ::= or_expr",
 /*   1 */ "or_expr ::= or_expr OR and_expr",
 /*   2 */ "and_expr ::= and_expr AND not_expr",
 /*   3 */ "not_expr ::= NOT not_expr",
 /*   4 */ "cmp_expr ::= arithmetic EQ arithmetic",
 /*   5 */ "cmp_expr ::= arithmetic NE arithmetic",
 /*   6 */ "cmp_expr ::= arithmetic LT arithmetic",
 /*   7 */ "cmp_expr ::= arithmetic LE arithmetic",
 /*   8 */ "cmp_expr ::= arithmetic GT arithmetic",
 /*   9 */ "cmp_expr ::= arithmetic GE arithmetic",
 /*  10 */ "cmp_expr ::= arithmetic CONTAINS arithmetic",
 /*  11 */ "cmp_expr ::= arithmetic MATCHES arithmetic",
 /*  12 */ "arithmetic ::= arithmetic PLUS arithmetic",
 /*  13 */ "arithmetic ::= arithmetic MINUS arithmetic",
 /*  14 */ "arithmetic ::= arithmetic STAR arithmetic",
 /*  15 */ "arithmetic ::= arithmetic SLASH arithmetic",
 /*  16 */ "arithmetic ::= arithmetic MOD arithmetic",
 /*  17 */ "unary ::= MINUS unary",
 /*  18 */ "term ::= TRUE_LITERAL",
 /*  19 */ "term ::= FALSE_LITERAL",
 /*  20 */ "term ::= INTEGER_LITERAL",
 /*  21 */ "term ::= STRING_LITERAL",
 /*  22 */ "term ::= SIZE_LITERAL",
 /*  23 */ "term ::= DATETIME_LITERAL",
 /*  24 */ "term ::= DURATION_LITERAL",
 /*  25 */ "term ::= VERSION_LITERAL",
 /*  26 */ "term ::= IDENTIFIER LPAREN RPAREN",
 /*  27 */ "term ::= IDENTIFIER LPAREN expr_list RPAREN",
 /*  28 */ "term ::= IDENTIFIER",
 /*  29 */ "term ::= LPAREN expr RPAREN",
 /*  30 */ "expr_list ::= expr",
 /*  31 */ "expr_list ::= expr_list COMMA expr",
 /*  32 */ "or_expr ::= and_expr",
 /*  33 */ "and_expr ::= not_expr",
 /*  34 */ "not_expr ::= cmp_expr",
 /*  35 */ "cmp_expr ::= arithmetic",
 /*  36 */ "arithmetic ::= unary",
 /*  37 */ "expr ::= or_expr",
 /*  38 */ "unary ::= term",
};
#endif /* NDEBUG */


#if YYGROWABLESTACK
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int oldSize = 1 + (int)(p->yystackEnd - p->yystack);
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = oldSize*2 + 100;
  idx = (int)(p->yytos - p->yystack);
  if( p->yystack==p->yystk0 ){
    pNew = YYREALLOC(0, newSize*sizeof(pNew[0]));
    if( pNew==0 ) return 1;
    memcpy(pNew, p->yystack, oldSize*sizeof(pNew[0]));
  }else{
    pNew = YYREALLOC(p->yystack, newSize*sizeof(pNew[0]));
    if( pNew==0 ) return 1;
  }
  p->yystack = pNew;
  p->yytos = &p->yystack[idx];
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
            yyTracePrompt, oldSize, newSize);
  }
#endif
  p->yystackEnd = &p->yystack[newSize-1];
  return 0;
}
#endif /* YYGROWABLESTACK */

#if !YYGROWABLESTACK
/* For builds that do no have a growable stack, yyGrowStack always
** returns an error.
*/
# define yyGrowStack(X) 1
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to ParseAlloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void ParseInit(void *yypRawParser ParseCTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  ParseCTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
  yypParser->yystack = yypParser->yystk0;
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to Parse and ParseFree.
*/
void *ParseAlloc(void *(*mallocProc)(YYMALLOCARGTYPE) ParseCTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    ParseCTX_STORE
    ParseInit(yypParser ParseCTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* Parse_ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  ParseARG_FETCH
  ParseCTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void ParseFinalize(void *p){
  yyParser *pParser = (yyParser*)p;

  /* In-lined version of calling yy_pop_parser_stack() for each
  ** element left in the stack */
  yyStackEntry *yytos = pParser->yytos;
  while( yytos>pParser->yystack ){
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sPopping %s\n",
        yyTracePrompt,
        yyTokenName[yytos->major]);
    }
#endif
    if( yytos->major>=YY_MIN_DSTRCTR ){
      yy_destructor(pParser, yytos->major, &yytos->minor);
    }
    yytos--;
  }

#if YYGROWABLESTACK
  if( pParser->yystack!=pParser->yystk0 ) YYFREE(pParser->yystack);
#endif
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void ParseFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  ParseFinalize(p);
  (*freeProc)(p);
}
#endif /* Parse_ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int ParseStackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int ParseCoverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   ParseARG_FETCH
   ParseCTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
/******** End %stack_overflow code ********************************************/
   ParseARG_STORE /* Suppress warning about unused %extra_argument var */
   ParseCTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  ParseTOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
  yytos = yypParser->yytos;
  if( yytos>yypParser->yystackEnd ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
    yytos = yypParser->yytos;
    assert( yytos <= yypParser->yystackEnd );
  }
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    29,  /* (0) filter_expr ::= or_expr */
    30,  /* (1) or_expr ::= or_expr OR and_expr */
    31,  /* (2) and_expr ::= and_expr AND not_expr */
    32,  /* (3) not_expr ::= NOT not_expr */
    33,  /* (4) cmp_expr ::= arithmetic EQ arithmetic */
    33,  /* (5) cmp_expr ::= arithmetic NE arithmetic */
    33,  /* (6) cmp_expr ::= arithmetic LT arithmetic */
    33,  /* (7) cmp_expr ::= arithmetic LE arithmetic */
    33,  /* (8) cmp_expr ::= arithmetic GT arithmetic */
    33,  /* (9) cmp_expr ::= arithmetic GE arithmetic */
    33,  /* (10) cmp_expr ::= arithmetic CONTAINS arithmetic */
    33,  /* (11) cmp_expr ::= arithmetic MATCHES arithmetic */
    34,  /* (12) arithmetic ::= arithmetic PLUS arithmetic */
    34,  /* (13) arithmetic ::= arithmetic MINUS arithmetic */
    34,  /* (14) arithmetic ::= arithmetic STAR arithmetic */
    34,  /* (15) arithmetic ::= arithmetic SLASH arithmetic */
    34,  /* (16) arithmetic ::= arithmetic MOD arithmetic */
    35,  /* (17) unary ::= MINUS unary */
    37,  /* (18) term ::= TRUE_LITERAL */
    37,  /* (19) term ::= FALSE_LITERAL */
    37,  /* (20) term ::= INTEGER_LITERAL */
    37,  /* (21) term ::= STRING_LITERAL */
    37,  /* (22) term ::= SIZE_LITERAL */
    37,  /* (23) term ::= DATETIME_LITERAL */
    37,  /* (24) term ::= DURATION_LITERAL */
    37,  /* (25) term ::= VERSION_LITERAL */
    37,  /* (26) term ::= IDENTIFIER LPAREN RPAREN */
    37,  /* (27) term ::= IDENTIFIER LPAREN expr_list RPAREN */
    37,  /* (28) term ::= IDENTIFIER */
    37,  /* (29) term ::= LPAREN expr RPAREN */
    38,  /* (30) expr_list ::= expr */
    38,  /* (31) expr_list ::= expr_list COMMA expr */
    30,  /* (32) or_expr ::= and_expr */
    31,  /* (33) and_expr ::= not_expr */
    32,  /* (34) not_expr ::= cmp_expr */
    33,  /* (35) cmp_expr ::= arithmetic */
    34,  /* (36) arithmetic ::= unary */
    36,  /* (37) expr ::= or_expr */
    35,  /* (38) unary ::= term */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -1,  /* (0) filter_expr ::= or_expr */
   -3,  /* (1) or_expr ::= or_expr OR and_expr */
   -3,  /* (2) and_expr ::= and_expr AND not_expr */
   -2,  /* (3) not_expr ::= NOT not_expr */
   -3,  /* (4) cmp_expr ::= arithmetic EQ arithmetic */
   -3,  /* (5) cmp_expr ::= arithmetic NE arithmetic */
   -3,  /* (6) cmp_expr ::= arithmetic LT arithmetic */
   -3,  /* (7) cmp_expr ::= arithmetic LE arithmetic */
   -3,  /* (8) cmp_expr ::= arithmetic GT arithmetic */
   -3,  /* (9) cmp_expr ::= arithmetic GE arithmetic */
   -3,  /* (10) cmp_expr ::= arithmetic CONTAINS arithmetic */
   -3,  /* (11) cmp_expr ::= arithmetic MATCHES arithmetic */
   -3,  /* (12) arithmetic ::= arithmetic PLUS arithmetic */
   -3,  /* (13) arithmetic ::= arithmetic MINUS arithmetic */
   -3,  /* (14) arithmetic ::= arithmetic STAR arithmetic */
   -3,  /* (15) arithmetic ::= arithmetic SLASH arithmetic */
   -3,  /* (16) arithmetic ::= arithmetic MOD arithmetic */
   -2,  /* (17) unary ::= MINUS unary */
   -1,  /* (18) term ::= TRUE_LITERAL */
   -1,  /* (19) term ::= FALSE_LITERAL */
   -1,  /* (20) term ::= INTEGER_LITERAL */
   -1,  /* (21) term ::= STRING_LITERAL */
   -1,  /* (22) term ::= SIZE_LITERAL */
   -1,  /* (23) term ::= DATETIME_LITERAL */
   -1,  /* (24) term ::= DURATION_LITERAL */
   -1,  /* (25) term ::= VERSION_LITERAL */
   -3,  /* (26) term ::= IDENTIFIER LPAREN RPAREN */
   -4,  /* (27) term ::= IDENTIFIER LPAREN expr_list RPAREN */
   -1,  /* (28) term ::= IDENTIFIER */
   -3,  /* (29) term ::= LPAREN expr RPAREN */
   -1,  /* (30) expr_list ::= expr */
   -3,  /* (31) expr_list ::= expr_list COMMA expr */
   -1,  /* (32) or_expr ::= and_expr */
   -1,  /* (33) and_expr ::= not_expr */
   -1,  /* (34) not_expr ::= cmp_expr */
   -1,  /* (35) cmp_expr ::= arithmetic */
   -1,  /* (36) arithmetic ::= unary */
   -1,  /* (37) expr ::= or_expr */
   -1,  /* (38) unary ::= term */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  ParseTOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  ParseCTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  ParseARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
        YYMINORTYPE yylhsminor;
      case 0: /* filter_expr ::= or_expr */
#line 27 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ pCtx->rootNode = yymsp[0].minor.yy0.node; }
#line 1050 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
        break;
      case 1: /* or_expr ::= or_expr OR and_expr */
#line 29 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yylhsminor.yy0.node = new OrNode(yymsp[-2].minor.yy0.node, yymsp[0].minor.yy0.node); }
#line 1055 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 2: /* and_expr ::= and_expr AND not_expr */
#line 32 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yylhsminor.yy0.node = new AndNode(yymsp[-2].minor.yy0.node, yymsp[0].minor.yy0.node); }
#line 1061 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 3: /* not_expr ::= NOT not_expr */
#line 35 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yymsp[-1].minor.yy0.node = new NotNode(yymsp[0].minor.yy0.node); }
#line 1067 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
        break;
      case 4: /* cmp_expr ::= arithmetic EQ arithmetic */
#line 38 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yylhsminor.yy0.node = new ComparisonNode(yymsp[-2].minor.yy0.node, "==", yymsp[0].minor.yy0.node); }
#line 1072 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 5: /* cmp_expr ::= arithmetic NE arithmetic */
#line 39 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yylhsminor.yy0.node = new ComparisonNode(yymsp[-2].minor.yy0.node, "!=", yymsp[0].minor.yy0.node); }
#line 1078 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 6: /* cmp_expr ::= arithmetic LT arithmetic */
#line 40 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yylhsminor.yy0.node = new ComparisonNode(yymsp[-2].minor.yy0.node, "<",  yymsp[0].minor.yy0.node); }
#line 1084 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 7: /* cmp_expr ::= arithmetic LE arithmetic */
#line 41 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yylhsminor.yy0.node = new ComparisonNode(yymsp[-2].minor.yy0.node, "<=", yymsp[0].minor.yy0.node); }
#line 1090 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 8: /* cmp_expr ::= arithmetic GT arithmetic */
#line 42 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yylhsminor.yy0.node = new ComparisonNode(yymsp[-2].minor.yy0.node, ">",  yymsp[0].minor.yy0.node); }
#line 1096 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 9: /* cmp_expr ::= arithmetic GE arithmetic */
#line 43 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yylhsminor.yy0.node = new ComparisonNode(yymsp[-2].minor.yy0.node, ">=", yymsp[0].minor.yy0.node); }
#line 1102 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 10: /* cmp_expr ::= arithmetic CONTAINS arithmetic */
#line 44 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yylhsminor.yy0.node = new ComparisonNode(yymsp[-2].minor.yy0.node, "CONTAINS", yymsp[0].minor.yy0.node); }
#line 1108 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 11: /* cmp_expr ::= arithmetic MATCHES arithmetic */
#line 45 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yylhsminor.yy0.node = new ComparisonNode(yymsp[-2].minor.yy0.node, "MATCHES", yymsp[0].minor.yy0.node); }
#line 1114 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 12: /* arithmetic ::= arithmetic PLUS arithmetic */
#line 48 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yylhsminor.yy0.node = new ArithmeticNode(yymsp[-2].minor.yy0.node, '+', yymsp[0].minor.yy0.node); }
#line 1120 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 13: /* arithmetic ::= arithmetic MINUS arithmetic */
#line 49 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yylhsminor.yy0.node = new ArithmeticNode(yymsp[-2].minor.yy0.node, '-', yymsp[0].minor.yy0.node); }
#line 1126 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 14: /* arithmetic ::= arithmetic STAR arithmetic */
#line 50 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yylhsminor.yy0.node = new ArithmeticNode(yymsp[-2].minor.yy0.node, '*', yymsp[0].minor.yy0.node); }
#line 1132 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 15: /* arithmetic ::= arithmetic SLASH arithmetic */
#line 51 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yylhsminor.yy0.node = new ArithmeticNode(yymsp[-2].minor.yy0.node, '/', yymsp[0].minor.yy0.node); }
#line 1138 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 16: /* arithmetic ::= arithmetic MOD arithmetic */
#line 52 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yylhsminor.yy0.node = new ArithmeticNode(yymsp[-2].minor.yy0.node, '%', yymsp[0].minor.yy0.node); }
#line 1144 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 17: /* unary ::= MINUS unary */
#line 57 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yymsp[-1].minor.yy0.node = new NegateNode(yymsp[0].minor.yy0.node); }
#line 1150 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
        break;
      case 18: /* term ::= TRUE_LITERAL */
#line 60 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yymsp[0].minor.yy0.node = new BoolLiteral(true); }
#line 1155 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
        break;
      case 19: /* term ::= FALSE_LITERAL */
#line 61 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yymsp[0].minor.yy0.node = new BoolLiteral(false); }
#line 1160 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
        break;
      case 20: /* term ::= INTEGER_LITERAL */
#line 62 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yylhsminor.yy0.node = new IntLiteral(yymsp[0].minor.yy0.integer); }
#line 1165 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 21: /* term ::= STRING_LITERAL */
#line 63 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yylhsminor.yy0.node = new StringLiteral(yymsp[0].minor.yy0.string); }
#line 1171 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 22: /* term ::= SIZE_LITERAL */
#line 64 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yylhsminor.yy0.node = new SizeLiteral(yymsp[0].minor.yy0.string); }
#line 1177 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 23: /* term ::= DATETIME_LITERAL */
#line 65 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yylhsminor.yy0.node = new DateTimeLiteral(yymsp[0].minor.yy0.string); }
#line 1183 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 24: /* term ::= DURATION_LITERAL */
#line 66 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yylhsminor.yy0.node = new DurationLiteral(yymsp[0].minor.yy0.string); }
#line 1189 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 25: /* term ::= VERSION_LITERAL */
#line 67 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yylhsminor.yy0.node = new VersionLiteral(yymsp[0].minor.yy0.string); }
#line 1195 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 26: /* term ::= IDENTIFIER LPAREN RPAREN */
#line 68 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yylhsminor.yy0.node = new FunctionNode(pCtx, yymsp[-2].minor.yy0.string, {}); }
#line 1201 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 27: /* term ::= IDENTIFIER LPAREN expr_list RPAREN */
#line 69 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yylhsminor.yy0.node = new FunctionNode(pCtx, yymsp[-3].minor.yy0.string, yymsp[-1].minor.yy0.nodeList); }
#line 1207 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
  yymsp[-3].minor.yy0 = yylhsminor.yy0;
        break;
      case 28: /* term ::= IDENTIFIER */
#line 70 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yylhsminor.yy0.node = new FieldNode(pCtx, yymsp[0].minor.yy0.string); }
#line 1213 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 29: /* term ::= LPAREN expr RPAREN */
#line 71 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yymsp[-2].minor.yy0 = yymsp[-1].minor.yy0; }
#line 1219 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
        break;
      case 30: /* expr_list ::= expr */
#line 73 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yylhsminor.yy0.nodeList = new std::vector<ExprNode*>{ yymsp[0].minor.yy0.node }; }
#line 1224 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 31: /* expr_list ::= expr_list COMMA expr */
#line 74 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"
{ yymsp[-2].minor.yy0.nodeList->push_back(yymsp[0].minor.yy0.node); yylhsminor.yy0.nodeList = yymsp[-2].minor.yy0.nodeList; }
#line 1230 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      default:
      /* (32) or_expr ::= and_expr */ yytestcase(yyruleno==32);
      /* (33) and_expr ::= not_expr (OPTIMIZED OUT) */ assert(yyruleno!=33);
      /* (34) not_expr ::= cmp_expr (OPTIMIZED OUT) */ assert(yyruleno!=34);
      /* (35) cmp_expr ::= arithmetic */ yytestcase(yyruleno==35);
      /* (36) arithmetic ::= unary (OPTIMIZED OUT) */ assert(yyruleno!=36);
      /* (37) expr ::= or_expr */ yytestcase(yyruleno==37);
      /* (38) unary ::= term (OPTIMIZED OUT) */ assert(yyruleno!=38);
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
#line 23 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"

    pCtx->errorCode = FilterEngine::ERROR_PARSE_FAILURE;
#line 1285 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
/************ End %parse_failure code *****************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  ParseTOKENTYPE yyminor         /* The minor type of the error token */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
#line 19 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.y"

    pCtx->errorCode = FilterEngine::ERROR_SYNTAX_ERROR;
#line 1307 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterParser.c"
/************ End %syntax_error code ******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
/*********** End %parse_accept code *******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "ParseAlloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void Parse(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  ParseTOKENTYPE yyminor       /* The value for the token */
  ParseARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  ParseCTX_FETCH
  ParseARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  while(1){ /* Exit by "break" */
    assert( yypParser->yytos>=yypParser->yystack );
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      unsigned int yyruleno = yyact - YY_MIN_REDUCE; /* Reduce by this rule */
#ifndef NDEBUG
      assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
      if( yyTraceFILE ){
        int yysize = yyRuleInfoNRhs[yyruleno];
        if( yysize ){
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
            yyTracePrompt,
            yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
            yypParser->yytos[yysize].stateno);
        }else{
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
            yyTracePrompt, yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
        }
      }
#endif /* NDEBUG */

      /* Check that the stack is large enough to grow by a single entry
      ** if the RHS of the rule is empty.  This ensures that there is room
      ** enough on the stack to push the LHS value */
      if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
        if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
          yypParser->yyhwm++;
          assert( yypParser->yyhwm ==
                  (int)(yypParser->yytos - yypParser->yystack));
        }
#endif
        if( yypParser->yytos>=yypParser->yystackEnd ){
          if( yyGrowStack(yypParser) ){
            yyStackOverflow(yypParser);
            break;
          }
        }
      }
      yyact = yy_reduce(yypParser,yyruleno,yymajor,yyminor ParseCTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos > yypParser->yystack ){
          yyact = yy_find_reduce_action(yypParser->yytos->stateno,
                                        YYERRORSYMBOL);
          if( yyact<=YY_MAX_SHIFTREDUCE ) break;
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos <= yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int ParseFallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
