/* Generated by re2c 3.1 on Wed May  7 21:24:42 2025 */
#line 1 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
#line 6 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"


#include "pch.h"
#include "FilterParser.h"
#include "FilterEngineInternal.h"
#include <string>
#include <iostream>
#include <vector>

int FilterLexer::yylex()
{
begin:
	
#line 18 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
{
	wchar_t yych;
	yych = *YYCURSOR;
	switch (yych) {
		case '\t':
		case '\n':
		case '\r':
		case ' ': goto yy3;
		case '!': goto yy5;
		case '"': goto yy6;
		case '%': goto yy7;
		case '(': goto yy8;
		case ')': goto yy9;
		case '*': goto yy10;
		case '+': goto yy11;
		case '-': goto yy12;
		case '/': goto yy13;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy14;
		case '<': goto yy16;
		case '=': goto yy18;
		case '>': goto yy19;
		case 'A':
		case 'a': goto yy21;
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy23;
		case 'F':
		case 'f': goto yy25;
		case 'N':
		case 'n': goto yy26;
		case 'O':
		case 'o': goto yy27;
		case 'T':
		case 't': goto yy28;
		default:
			if (YYLIMIT <= YYCURSOR) goto yy49;
			goto yy1;
	}
yy1:
	++YYCURSOR;
yy2:
#line 50 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ lexerError(L"?????"); return 0; }
#line 111 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy3:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\t':
		case '\n':
		case '\r':
		case ' ': goto yy3;
		default: goto yy4;
	}
yy4:
#line 19 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ goto begin; }
#line 124 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy5:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy29;
		default: goto yy2;
	}
yy6:
	++YYCURSOR;
#line 31 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{
		std::wstring str = unescapeQuotes(YYCURSOR);
		yylval.string = dupString(str.c_str());
		return STRING_LITERAL;
	}
#line 139 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy7:
	++YYCURSOR;
#line 48 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return MOD; }
#line 144 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy8:
	++YYCURSOR;
#line 42 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return LPAREN; }
#line 149 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy9:
	++YYCURSOR;
#line 43 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return RPAREN; }
#line 154 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy10:
	++YYCURSOR;
#line 46 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return STAR; }
#line 159 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy11:
	++YYCURSOR;
#line 44 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return PLUS; }
#line 164 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy12:
	++YYCURSOR;
#line 45 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return MINUS; }
#line 169 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy13:
	++YYCURSOR;
#line 47 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return SLASH; }
#line 174 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy14:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy14;
		default: goto yy15;
	}
yy15:
#line 30 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ yylval.integer = std::stoi(std::wstring((const wchar_t*)yycursor, YYCURSOR - yycursor)); return INTEGER_LITERAL; }
#line 193 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy16:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy30;
		default: goto yy17;
	}
yy17:
#line 38 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return LT; }
#line 203 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy18:
	++YYCURSOR;
#line 36 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return EQ; }
#line 208 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy19:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy31;
		default: goto yy20;
	}
yy20:
#line 40 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return GT; }
#line 218 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy21:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'N':
		case 'n': goto yy32;
		default: goto yy24;
	}
yy22:
#line 25 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{
						  std::wstring tmp = std::wstring((const wchar_t*)yycursor, YYCURSOR - yycursor);
						  yylval.string = dupString(tmp.c_str());
						  return IDENTIFIER;
						}
#line 234 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy23:
	yych = *++YYCURSOR;
yy24:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy23;
		default: goto yy22;
	}
yy25:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'A':
		case 'a': goto yy33;
		default: goto yy24;
	}
yy26:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'O':
		case 'o': goto yy34;
		default: goto yy24;
	}
yy27:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'R':
		case 'r': goto yy35;
		default: goto yy24;
	}
yy28:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'R':
		case 'r': goto yy37;
		default: goto yy24;
	}
yy29:
	++YYCURSOR;
#line 37 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return NE; }
#line 340 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy30:
	++YYCURSOR;
#line 39 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return LE; }
#line 345 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy31:
	++YYCURSOR;
#line 41 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return GE; }
#line 350 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy32:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'D':
		case 'd': goto yy38;
		default: goto yy24;
	}
yy33:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'L':
		case 'l': goto yy40;
		default: goto yy24;
	}
yy34:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'T':
		case 't': goto yy41;
		default: goto yy24;
	}
yy35:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy23;
		default: goto yy36;
	}
yy36:
#line 21 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return OR; }
#line 446 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy37:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'U':
		case 'u': goto yy43;
		default: goto yy24;
	}
yy38:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy23;
		default: goto yy39;
	}
yy39:
#line 20 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return AND; }
#line 526 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy40:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'S':
		case 's': goto yy44;
		default: goto yy24;
	}
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy23;
		default: goto yy42;
	}
yy42:
#line 22 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return NOT; }
#line 606 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy43:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'E':
		case 'e': goto yy45;
		default: goto yy24;
	}
yy44:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'E':
		case 'e': goto yy47;
		default: goto yy24;
	}
yy45:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy23;
		default: goto yy46;
	}
yy46:
#line 23 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ yylval.boolean = true; return TRUE_LITERAL; }
#line 694 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy47:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy23;
		default: goto yy48;
	}
yy48:
#line 24 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ yylval.boolean = false; return FALSE_LITERAL; }
#line 766 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy49:
#line 49 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return 0; }
#line 770 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
}
#line 51 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"

}
