/* Generated by re2c 3.1 on Mon May 19 09:06:49 2025 */
#line 1 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
#line 6 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"


#include "pch.h"
#include "FilterParser.h"
#include "FilterEngineInternal.h"
#include <string>
#include <iostream>
#include <vector>

int FilterLexer::yylex()
{
begin:
	
#line 18 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
{
	char yych;
	yych = *YYCURSOR;
	switch (yych) {
		case '\t':
		case '\n':
		case '\r':
		case ' ': goto yy3;
		case '!': goto yy5;
		case '"': goto yy6;
		case '%': goto yy7;
		case '(': goto yy8;
		case ')': goto yy9;
		case '*': goto yy10;
		case '+': goto yy11;
		case '-': goto yy12;
		case '/': goto yy13;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy14;
		case '<': goto yy16;
		case '=': goto yy18;
		case '>': goto yy19;
		case 'A':
		case 'a': goto yy21;
		case 'B':
		case 'D':
		case 'E':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'b':
		case 'd':
		case 'e':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy23;
		case 'C':
		case 'c': goto yy25;
		case 'F':
		case 'f': goto yy26;
		case 'M':
		case 'm': goto yy27;
		case 'N':
		case 'n': goto yy28;
		case 'O':
		case 'o': goto yy29;
		case 'T':
		case 't': goto yy30;
		default:
			if (YYLIMIT <= YYCURSOR) goto yy66;
			goto yy1;
	}
yy1:
	++YYCURSOR;
yy2:
#line 55 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ lexerError("?????"); return 0; }
#line 111 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy3:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\t':
		case '\n':
		case '\r':
		case ' ': goto yy3;
		default: goto yy4;
	}
yy4:
#line 19 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ goto begin; }
#line 124 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy5:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy31;
		default: goto yy2;
	}
yy6:
	++YYCURSOR;
#line 36 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{
		std::string str = unescapeQuotes(YYCURSOR);
		yylval.string = dupString(str.c_str());
		return STRING_LITERAL;
	}
#line 139 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy7:
	++YYCURSOR;
#line 53 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return MOD; }
#line 144 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy8:
	++YYCURSOR;
#line 47 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return LPAREN; }
#line 149 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy9:
	++YYCURSOR;
#line 48 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return RPAREN; }
#line 154 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy10:
	++YYCURSOR;
#line 51 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return STAR; }
#line 159 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy11:
	++YYCURSOR;
#line 49 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return PLUS; }
#line 164 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy12:
	++YYCURSOR;
#line 50 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return MINUS; }
#line 169 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy13:
	++YYCURSOR;
#line 52 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return SLASH; }
#line 174 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy14:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy14;
		default: goto yy15;
	}
yy15:
#line 35 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ yylval.integer = std::stoi(std::string((const char*)yycursor, YYCURSOR - yycursor)); return INTEGER_LITERAL; }
#line 193 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy16:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy32;
		default: goto yy17;
	}
yy17:
#line 43 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return LT; }
#line 203 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy18:
	++YYCURSOR;
#line 41 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return EQ; }
#line 208 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy19:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy33;
		default: goto yy20;
	}
yy20:
#line 45 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return GT; }
#line 218 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy21:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'N':
		case 'n': goto yy34;
		default: goto yy24;
	}
yy22:
#line 27 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{
		const char* p = yycursor;
		while (*p == ' ' || *p == '\t' || *p == '\r' || *p == '\n')
			p++;
		std::string tmp = std::string(p, YYCURSOR - p);
		yylval.string = dupString(tmp.c_str());
		return IDENTIFIER;
	}
#line 237 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy23:
	yych = *++YYCURSOR;
yy24:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy23;
		default: goto yy22;
	}
yy25:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'O':
		case 'o': goto yy35;
		default: goto yy24;
	}
yy26:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'A':
		case 'a': goto yy36;
		default: goto yy24;
	}
yy27:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'A':
		case 'a': goto yy37;
		default: goto yy24;
	}
yy28:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'O':
		case 'o': goto yy38;
		default: goto yy24;
	}
yy29:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'R':
		case 'r': goto yy39;
		default: goto yy24;
	}
yy30:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'R':
		case 'r': goto yy41;
		default: goto yy24;
	}
yy31:
	++YYCURSOR;
#line 42 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return NE; }
#line 359 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy32:
	++YYCURSOR;
#line 44 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return LE; }
#line 364 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy33:
	++YYCURSOR;
#line 46 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return GE; }
#line 369 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy34:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'D':
		case 'd': goto yy42;
		default: goto yy24;
	}
yy35:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'N':
		case 'n': goto yy44;
		default: goto yy24;
	}
yy36:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'L':
		case 'l': goto yy45;
		default: goto yy24;
	}
yy37:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'T':
		case 't': goto yy46;
		default: goto yy24;
	}
yy38:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'T':
		case 't': goto yy47;
		default: goto yy24;
	}
yy39:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy23;
		default: goto yy40;
	}
yy40:
#line 21 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return OR; }
#line 481 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'U':
		case 'u': goto yy49;
		default: goto yy24;
	}
yy42:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy23;
		default: goto yy43;
	}
yy43:
#line 20 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return AND; }
#line 561 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy44:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'T':
		case 't': goto yy50;
		default: goto yy24;
	}
yy45:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'S':
		case 's': goto yy51;
		default: goto yy24;
	}
yy46:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'C':
		case 'c': goto yy52;
		default: goto yy24;
	}
yy47:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy23;
		default: goto yy48;
	}
yy48:
#line 22 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return NOT; }
#line 657 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy49:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'E':
		case 'e': goto yy53;
		default: goto yy24;
	}
yy50:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'A':
		case 'a': goto yy55;
		default: goto yy24;
	}
yy51:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'E':
		case 'e': goto yy56;
		default: goto yy24;
	}
yy52:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'H':
		case 'h': goto yy58;
		default: goto yy24;
	}
yy53:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy23;
		default: goto yy54;
	}
yy54:
#line 23 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ yylval.boolean = true; return TRUE_LITERAL; }
#line 761 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'I':
		case 'i': goto yy59;
		default: goto yy24;
	}
yy56:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy23;
		default: goto yy57;
	}
yy57:
#line 24 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ yylval.boolean = false; return FALSE_LITERAL; }
#line 841 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy58:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'E':
		case 'e': goto yy60;
		default: goto yy24;
	}
yy59:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'N':
		case 'n': goto yy61;
		default: goto yy24;
	}
yy60:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'S':
		case 's': goto yy62;
		default: goto yy24;
	}
yy61:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy22;
		case 'S':
		case 's': goto yy64;
		default: goto yy24;
	}
yy62:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy23;
		default: goto yy63;
	}
yy63:
#line 26 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return MATCHES; }
#line 945 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy64:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy23;
		default: goto yy65;
	}
yy65:
#line 25 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return CONTAINS; }
#line 1017 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
yy66:
#line 54 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"
	{ return 0; }
#line 1021 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.cpp"
}
#line 56 "E:\\dev\\winmerge\\Src\\FilterEngine\\FilterLexer.re"

}
