#define AND                              1
#define OR                               2
#define NOT                              3
#define TRUE_LITERAL                     4
#define FALSE_LITERAL                    5
#define IDENTIFIER                       6
#define INTEGER_LITERAL                  7
#define STRING_LITERAL                   8
#define EQ                               9
#define NE                              10
#define LT                              11
#define LE                              12
#define GT                              13
#define GE                              14
#define CONTAINS                        15
#define MATCHES                         16
#define LPAREN                          17
#define RPAREN                          18
#define PLUS                            19
#define MINUS                           20
#define STAR                            21
#define SLASH                           22
#define MOD                             23
#define COMMA                           24
