/**
 * @file FilterError.h
 * @brief Defines error codes for the filter engine.
 */
#pragma once

enum FilterErrorCode
{
	FILTER_ERROR_NO_ERROR = 0,
	FILTER_ERROR_UNKNOWN_CHAR = 1,
	FILTER_ERROR_UNTERMINATED_STRING = 2,
	FILTER_ERROR_SYNTAX_ERROR = 3,
	FILTER_ERROR_PARSE_FAILURE = 4,
	FILTER_ERROR_INVALID_LITERAL = 5,
	FILTER_ERROR_INVALID_REGULAR_EXPRESSION = 6,
	FILTER_ERROR_UNDEFINED_IDENTIFIER = 7,
	FILTER_ERROR_INVALID_ARGUMENT_COUNT = 8,
	FILTER_ERROR_FILTER_NAME_NOT_FOUND = 9,
};
