#define TK_AND                              1
#define TK_OR                               2
#define TK_NOT                              3
#define TK_TRUE_LITERAL                     4
#define TK_FALSE_LITERAL                    5
#define TK_NONE_LITERAL                     6
#define TK_INTEGER_LITERAL                  7
#define TK_DOUBLE_LITERAL                   8
#define TK_STRING_LITERAL                   9
#define TK_SIZE_LITERAL                    10
#define TK_DATETIME_LITERAL                11
#define TK_DURATION_LITERAL                12
#define TK_VERSION_LITERAL                 13
#define TK_IDENTIFIER                      14
#define TK_EQ                              15
#define TK_NE                              16
#define TK_LT                              17
#define TK_LE                              18
#define TK_GT                              19
#define TK_GE                              20
#define TK_CONTAINS                        21
#define TK_RECONTAINS                      22
#define TK_LIKE                            23
#define TK_MATCHES                         24
#define TK_LPAREN                          25
#define TK_RPAREN                          26
#define TK_PLUS                            27
#define TK_MINUS                           28
#define TK_STAR                            29
#define TK_SLASH                           30
#define TK_MOD                             31
#define TK_COMMA                           32
