/* Generated by re2c 3.1 on Sun May  4 18:09:16 2025 */
#line 1 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
#line 6 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"


#include "parser.h"
#include "parser_internal.h"
#include <string>
#include <iostream>
#include <vector>

char* yycursor = nullptr;
char* YYMARKER = nullptr;
char* YYCURSOR = nullptr;
char* YYLIMIT = nullptr;

int yylex()
{
begin:
    
#line 22 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
{
	char yych;
	yych = *YYCURSOR;
	switch (yych) {
		case '\t':
		case '\n':
		case '\r':
		case ' ': goto yy3;
		case '!': goto yy5;
		case '"': goto yy6;
		case '(': goto yy7;
		case ')': goto yy8;
		case '+': goto yy9;
		case '-': goto yy10;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy11;
		case '<': goto yy13;
		case '=': goto yy15;
		case '>': goto yy16;
		case 'A':
		case 'a': goto yy18;
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy20;
		case 'F':
		case 'f': goto yy22;
		case 'N':
		case 'n': goto yy23;
		case 'O':
		case 'o': goto yy24;
		case 'T':
		case 't': goto yy25;
		default:
			if (YYLIMIT <= YYCURSOR) goto yy46;
			goto yy1;
	}
yy1:
	++YYCURSOR;
yy2:
#line 65 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ lexerError("?????"); return 0; }
#line 112 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy3:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\t':
		case '\n':
		case '\r':
		case ' ': goto yy3;
		default: goto yy4;
	}
yy4:
#line 23 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ goto begin; }
#line 125 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy5:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy26;
		default: goto yy2;
	}
yy6:
	++YYCURSOR;
#line 35 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{
		const char* start = YYCURSOR;
		std::string str;
		while (*YYCURSOR != '\0') {
			if (*YYCURSOR == '"') {
				if (*(YYCURSOR + 1) == '"') {
					str += '"';
					YYCURSOR += 2;
				} else {
					++YYCURSOR;
					break;
				}
			} else {
				str += *YYCURSOR++;
			}
		}
		yylval.string = dupString(str.c_str());
		return STRING_LITERAL;
    }
#line 154 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy7:
	++YYCURSOR;
#line 60 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return LPAREN; }
#line 159 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy8:
	++YYCURSOR;
#line 61 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return RPAREN; }
#line 164 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy9:
	++YYCURSOR;
#line 62 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return PLUS; }
#line 169 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy10:
	++YYCURSOR;
#line 63 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return MINUS; }
#line 174 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy11:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy11;
		default: goto yy12;
	}
yy12:
#line 34 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ yylval.integer = std::stoi(std::string((const char*)yycursor, YYCURSOR - yycursor)); return INTEGER_LITERAL; }
#line 193 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy13:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy27;
		default: goto yy14;
	}
yy14:
#line 56 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return LT; }
#line 203 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy15:
	++YYCURSOR;
#line 54 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return EQ; }
#line 208 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy16:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy28;
		default: goto yy17;
	}
yy17:
#line 58 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return GT; }
#line 218 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy18:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy19;
		case 'N':
		case 'n': goto yy29;
		default: goto yy21;
	}
yy19:
#line 29 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{
                          std::string tmp = std::string((const char*)yycursor, YYCURSOR - yycursor);
                          yylval.string = dupString(tmp.c_str());
                          return IDENTIFIER;
                        }
#line 234 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy20:
	yych = *++YYCURSOR;
yy21:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy20;
		default: goto yy19;
	}
yy22:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy19;
		case 'A':
		case 'a': goto yy30;
		default: goto yy21;
	}
yy23:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy19;
		case 'O':
		case 'o': goto yy31;
		default: goto yy21;
	}
yy24:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy19;
		case 'R':
		case 'r': goto yy32;
		default: goto yy21;
	}
yy25:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy19;
		case 'R':
		case 'r': goto yy34;
		default: goto yy21;
	}
yy26:
	++YYCURSOR;
#line 55 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return NE; }
#line 340 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy27:
	++YYCURSOR;
#line 57 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return LE; }
#line 345 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy28:
	++YYCURSOR;
#line 59 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return GE; }
#line 350 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy29:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy19;
		case 'D':
		case 'd': goto yy35;
		default: goto yy21;
	}
yy30:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy19;
		case 'L':
		case 'l': goto yy37;
		default: goto yy21;
	}
yy31:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy19;
		case 'T':
		case 't': goto yy38;
		default: goto yy21;
	}
yy32:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy20;
		default: goto yy33;
	}
yy33:
#line 25 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return OR; }
#line 446 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy34:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy19;
		case 'U':
		case 'u': goto yy40;
		default: goto yy21;
	}
yy35:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy20;
		default: goto yy36;
	}
yy36:
#line 24 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return AND; }
#line 526 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy37:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy19;
		case 'S':
		case 's': goto yy41;
		default: goto yy21;
	}
yy38:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy20;
		default: goto yy39;
	}
yy39:
#line 26 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return NOT; }
#line 606 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy40:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy19;
		case 'E':
		case 'e': goto yy42;
		default: goto yy21;
	}
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy19;
		case 'E':
		case 'e': goto yy44;
		default: goto yy21;
	}
yy42:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy20;
		default: goto yy43;
	}
yy43:
#line 27 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ yylval.boolean = true; return TRUE_LITERAL; }
#line 694 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy44:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy20;
		default: goto yy45;
	}
yy45:
#line 28 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ yylval.boolean = false; return FALSE_LITERAL; }
#line 766 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy46:
#line 64 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return 0; }
#line 770 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
}
#line 66 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"

}