/* Generated by re2c 3.1 on Sat May  3 19:53:51 2025 */
#line 1 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
#line 6 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"


#include "parser.h"
#include "parser_internal.h"
#include <string>
#include <iostream>
#include <vector>

YYSTYPE yylval;
std::vector<char*> strings;

void lexerError(const char* msg) {
    std::cerr << "Lexer Error: " << msg << std::endl;
}

const char* dupString(const char* str)
{
    char* newStr = _strdup(str);
    strings.push_back(newStr);
    return newStr;
}

char* yycursor = nullptr;
char* YYMARKER = nullptr;
char* YYCURSOR = nullptr;
char* YYLIMIT = nullptr;

int yylex()
{
begin:
    
#line 36 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
{
	char yych;
	yych = *YYCURSOR;
	switch (yych) {
		case '\t':
		case '\n':
		case '\r':
		case ' ': goto yy3;
		case '!': goto yy5;
		case '"': goto yy6;
		case '(': goto yy7;
		case ')': goto yy8;
		case '+': goto yy9;
		case '-': goto yy10;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy11;
		case '<': goto yy13;
		case '=': goto yy15;
		case '>': goto yy16;
		case 'A':
		case 'a': goto yy18;
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy20;
		case 'F':
		case 'f': goto yy22;
		case 'N':
		case 'n': goto yy23;
		case 'O':
		case 'o': goto yy24;
		case 'T':
		case 't': goto yy25;
		default:
			if (YYLIMIT <= YYCURSOR) goto yy49;
			goto yy1;
	}
yy1:
	++YYCURSOR;
yy2:
#line 65 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ lexerError("?????"); return 0; }
#line 126 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy3:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\t':
		case '\n':
		case '\r':
		case ' ': goto yy3;
		default: goto yy4;
	}
yy4:
#line 37 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ goto begin; }
#line 139 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy5:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy26;
		default: goto yy2;
	}
yy6:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= 0x00) {
		if (YYLIMIT <= YYCURSOR) goto yy2;
		goto yy27;
	}
	goto yy28;
yy7:
	++YYCURSOR;
#line 60 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return LPAREN; }
#line 157 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy8:
	++YYCURSOR;
#line 61 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return RPAREN; }
#line 162 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy9:
	++YYCURSOR;
#line 62 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return PLUS; }
#line 167 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy10:
	++YYCURSOR;
#line 63 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return MINUS; }
#line 172 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy11:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy11;
		default: goto yy12;
	}
yy12:
#line 48 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ yylval.integer = std::stoi(std::string((const char*)yycursor, YYCURSOR - yycursor)); return INTEGER_LITERAL; }
#line 191 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy13:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy30;
		default: goto yy14;
	}
yy14:
#line 56 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return LT; }
#line 201 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy15:
	++YYCURSOR;
#line 54 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return EQ; }
#line 206 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy16:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy31;
		default: goto yy17;
	}
yy17:
#line 58 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return GT; }
#line 216 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy18:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy19;
		case 'N':
		case 'n': goto yy32;
		default: goto yy21;
	}
yy19:
#line 43 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{
                          std::string tmp = std::string((const char*)yycursor, YYCURSOR - yycursor);
                          yylval.string = dupString(tmp.c_str());
                          return IDENTIFIER;
                        }
#line 232 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy20:
	yych = *++YYCURSOR;
yy21:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy20;
		default: goto yy19;
	}
yy22:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy19;
		case 'A':
		case 'a': goto yy33;
		default: goto yy21;
	}
yy23:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy19;
		case 'O':
		case 'o': goto yy34;
		default: goto yy21;
	}
yy24:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy19;
		case 'R':
		case 'r': goto yy35;
		default: goto yy21;
	}
yy25:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy19;
		case 'R':
		case 'r': goto yy37;
		default: goto yy21;
	}
yy26:
	++YYCURSOR;
#line 55 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return NE; }
#line 338 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy27:
	yych = *++YYCURSOR;
yy28:
	switch (yych) {
		case '"': goto yy29;
		default:
			if (YYLIMIT <= YYCURSOR) goto yy50;
			goto yy27;
	}
yy29:
	++YYCURSOR;
#line 49 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{
                          std::string tmp = std::string((const char*)yycursor, YYCURSOR - yycursor);
                          yylval.string = dupString(tmp.c_str());
                          return STRING_LITERAL;
                      }
#line 356 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy30:
	++YYCURSOR;
#line 57 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return LE; }
#line 361 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy31:
	++YYCURSOR;
#line 59 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return GE; }
#line 366 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy32:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy19;
		case 'D':
		case 'd': goto yy38;
		default: goto yy21;
	}
yy33:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy19;
		case 'L':
		case 'l': goto yy40;
		default: goto yy21;
	}
yy34:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy19;
		case 'T':
		case 't': goto yy41;
		default: goto yy21;
	}
yy35:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy20;
		default: goto yy36;
	}
yy36:
#line 39 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return OR; }
#line 462 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy37:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy19;
		case 'U':
		case 'u': goto yy43;
		default: goto yy21;
	}
yy38:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy20;
		default: goto yy39;
	}
yy39:
#line 38 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return AND; }
#line 542 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy40:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy19;
		case 'S':
		case 's': goto yy44;
		default: goto yy21;
	}
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy20;
		default: goto yy42;
	}
yy42:
#line 40 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return NOT; }
#line 622 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy43:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy19;
		case 'E':
		case 'e': goto yy45;
		default: goto yy21;
	}
yy44:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy19;
		case 'E':
		case 'e': goto yy47;
		default: goto yy21;
	}
yy45:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy20;
		default: goto yy46;
	}
yy46:
#line 41 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ yylval.boolean = true; return TRUE_LITERAL; }
#line 710 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy47:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy20;
		default: goto yy48;
	}
yy48:
#line 42 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ yylval.boolean = false; return FALSE_LITERAL; }
#line 782 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy49:
#line 64 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"
	{ return 0; }
#line 786 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.cpp"
yy50:
	YYCURSOR = YYMARKER;
	goto yy2;
}
#line 66 "C:\\dev\\winmerge\\Src\\FilterEngine\\lexer.re"

}