#pragma once

#include <string>
#include <vector>
#include <map>
#include <unordered_set>
#include <stack>
#include <list>
#include <array>
#include <algorithm>
#include <iostream>
#include <sstream>
#include <memory>
#include <functional>
#include <cassert>
#include <ctime>
#include <cctype>
#include <boost/flyweight.hpp>
#include <gtest/gtest.h>
#include <gtest/gtest-param-test.h>
#include <Windows.h>
#include <shlobj.h>
#include <shlwapi.h>
