//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Merge.rc
//
#define IDR_MAINFRAME                   100
#define IDB_TOOLBAR_ENABLED8BIT         100  // = IDR_MAINFRAME
#define IDR_MERGEPROJECT                101
#define IDR_POPUP_EDITOR_HEADERBAR      102
#define IDR_POPUP_PLUGINS_SETTINGS      103
#define IDR_POPUP_MERGEVIEW             104
#define IDR_POPUP_DIRVIEW               105
#define IDR_POPUP_LOCATIONBAR           106
#define IDD_SAVECLOSING                 107
#define IDR_MERGEDOCTYPE                109
#define IDR_MERGEVIEWMENU               109 // = IDR_MERGEDOCTYPE
#define IDR_DIRDOCTYPE                  110
#define IDR_DIRVIEWMENU                 110 // = IDR_DIRDOCTYPE
#define IDR_POPUP_DIFF_OPTIONS          113
#define IDR_POPUP_IMGMERGEVIEW          114
#define IDD_ABOUTBOX                    200
#define IDD_PROP_VSS                    201
#define IDD_OPEN                        202
#define IDD_EDITFILE                    203
#define IDD_VSS                         204
#define IDD_PROPPAGE_GENERAL            205
#define IDD_CLEARCASE                   206
#define IDD_PROPPAGE_FILTER             207
#define IDD_PROPPAGE_SYSTEM             209
#define IDD_EDITOR_HEADERBAR            210
#define IDD_GENERATE_PATCH              211
#define IDD_DIRCOLS                     212
#define IDD_SELECTUNPACKER              213
#define IDD_DIRCOMP_PROGRESS            214
#define IDD_WMGOTO                      215
#define IDD_PROPPAGE_COMPARE            216
#define IDD_PROPPAGE_EDITOR             217
#define IDD_FILEFILTERS                 218
#define IDD_MESSAGE_BOX                 219
#define IDD_EDIT_FIND                   220
#define IDD_EDIT_REPLACE                221
#define IDD_PROPPAGE_COLORS_WINMERGE    222
#define IDD_PROPPAGE_CODEPAGE           223
#define IDD_PREFERENCES                 224
#define IDD_PROPPAGE_COLORS_SYNTAX      225
#define IDD_DIRCMP_REPORT               226
#define IDD_SHARED_FILTER               227
#define IDD_PROP_ARCHIVE                228
#define IDD_COMPARE_STATISTICS          229
#define IDD_COMPARE_STATISTICS3         230
#define IDD_LOAD_SAVE_CODEPAGE          231
#define IDD_TEST_FILTER                 232
#define IDD_PROPPAGE_COLORS_TEXT        233
#define IDD_PROJFILES_PATHS             234
#define IDD_PROPPAGE_BACKUPS            235
#define IDD_CONFIRM_COPY                236
#define IDD_PLUGINS_LIST                237
#define IDD_PROPPAGE_SHELL              238
#define IDD_PROPPAGE_COMPARE_FOLDER     239
#define IDD_DIR_FILTER                  240
#define IDD_ENCODINGERROR               241
#define IDD_PROPPAGE_COMPARE_IMAGE      242
#define IDD_PROPPAGE_COMPARE_BINARY     243
#define IDD_PROPPAGE_COLORS_MARKER      244
#define IDD_EDIT_MARKER                 245
#define IDR_LOGO                        307
#define IDR_SPLASH                      308
#define IDB_WINMERGE                    309
#define IDB_EDIT_COPY                   316
#define IDB_EDIT_CUT                    317
#define IDB_EDIT_PASTE                  318
#define IDB_EDIT_SEARCH                 319
#define IDB_WINDOW_CASCADE              320
#define IDB_WINDOW_HORIZONTAL           321
#define IDB_WINDOW_VERTICAL             322
#define IDB_WINDOW_CLOSE                323
#define IDB_WINDOW_CHANGEPANE           324
#define IDB_EDIT_GOTO                   325
#define IDB_EDIT_REPLACE                326
#define IDB_VIEW_SELECTFONT             328
#define IDB_FILE_EXIT                   329
#define IDB_HELP_CONTENTS               330
#define IDB_EDIT_SELECTALL              333
#define IDB_TOOLS_FILTERS               334
#define IDB_TOOLS_COLUMNS               335
#define IDB_MERGE_DELETE                336
#define IDB_FILE_PRINT                  337
#define IDB_TOOLS_GENERATEPATCH         338
#define IDB_TOOLS_GENERATEREPORT        339
#define IDR_MARGIN_ICONS                340
#define IDR_MARGIN_CURSOR               341
#define IDB_EDIT_TOGGLE_BOOKMARK        342
#define IDB_EDIT_GOTO_NEXT_BOOKMARK     343
#define IDB_EDIT_GOTO_PREV_BOOKMARK     344
#define IDB_EDIT_CLEAR_ALL_BOOKMARKS    345
#define IDB_LEFT                        347
#define IDB_MIDDLE                      348
#define IDB_RIGHT                       349
#define IDB_BOTH                        350
#define IDB_ALL                         351
#define IDB_LEFT_TO_RIGHT               352
#define IDB_LEFT_TO_MIDDLE              353
#define IDB_RIGHT_TO_LEFT               354
#define IDB_RIGHT_TO_MIDDLE             355
#define IDB_MIDDLE_TO_LEFT              356
#define IDB_MIDDLE_TO_RIGHT             357
#define IDB_LEFT_TO_BROWSE              358
#define IDB_MIDDLE_TO_BROWSE            359
#define IDB_RIGHT_TO_BROWSE             360
#define IDB_MOVE_LEFT_TO_BROWSE         361
#define IDB_MOVE_MIDDLE_TO_BROWSE       362
#define IDB_MOVE_RIGHT_TO_BROWSE        363
#define IDB_TOOLBAR_ENABLED32           365
#define IDB_VIEW_ZOOMIN                 366
#define IDB_VIEW_ZOOMOUT                367
#define IDB_FILE_OPENCONFLICT           369
#define IDB_PLUGINS_LIST                370
#define IDB_MERGE_COMPARE               371
#define IDB_MERGE_COMPARE_LEFT1_LEFT2   372
#define IDB_MERGE_COMPARE_RIGHT1_RIGHT2 373
#define IDB_MERGE_COMPARE_LEFT1_RIGHT2  374
#define IDB_MERGE_COMPARE_LEFT2_RIGHT1  375
#define IDB_COPY_FROM_LEFT              376
#define IDB_COPY_FROM_RIGHT             377
#define IDB_TOOLBAR_ENABLED             378
#define IDB_TOOLBAR_ENABLED_MASK        379
#define IDB_TOOLBAR_ENABLED_MASK32      380
#define IDI_FOLDER                      500
#define IDI_LFOLDER                     501
#define IDI_MFOLDER                     502
#define IDI_RFOLDER                     503
#define IDI_FOLDERSKIP                  504
#define IDI_EQUALFILE                   505
#define IDI_NOTEQUALFILE                506
#define IDI_EQUALBINARY                 507
#define IDI_LFILE                       508
#define IDI_MFILE                       509
#define IDI_RFILE                       510
#define IDI_BINARYDIFF                  511
#define IDI_FILESKIP                    512
#define IDI_COMPARE_ERROR               513
#define IDI_FOLDERUP                    514
#define IDI_FOLDERUP_DISABLE            515
#define IDI_SIGMA                       516
#define IDI_FILEFILTER                  517
#define IDI_LINEFILTER                  518
#define IDI_COMPARE_ABORTED             519
#define IDI_MRFILE                      520
#define IDI_LRFILE                      521
#define IDI_LMFILE                      522
#define IDI_MRFOLDER                    523
#define IDI_LRFOLDER                    524
#define IDI_LMFOLDER                    525
#define IDI_EQUALFOLDER                 526
#define IDI_NOTEQUALFOLDER              527
#define IDI_EQUALTEXTFILE               528
#define IDI_NOTEQUALTEXTFILE            529
#define IDI_EQUALIMAGE                  530
#define IDI_NOTEQUALIMAGE               531
#define IDI_TREE_STATE_COLLAPSED        532
#define IDI_TREE_STATE_EXPANDED         533
#define IDC_PATH0_BUTTON                1001
#define IDC_PATH1_BUTTON                1002
#define IDC_PATH2_BUTTON                1003
#define IDC_PATH0_COMBO                 1004
#define IDC_PATH1_COMBO                 1005
#define IDC_PATH2_COMBO                 1006
#define IDC_PROJECT_COMBO               1007
#define IDC_MESSAGE                     1008
#define IDC_EXT_COMBO                   1009
#define IDC_PATH_EDIT                   1010
#define IDC_BROWSE_BUTTON               1011
#define IDC_SCROLL_CHECK                1012
#define IDC_VSS_L1                      1013
#define IDC_WHITESPACE_CHECK            1014
#define IDC_RECURS_CHECK                1015
#define IDC_VERSION                     1016
#define IDC_IGNBLANKS_CHECK             1017
#define IDC_TAB_EDIT                    1018
#define IDC_WWW                         1019
#define IDC_IGNCASE_CHECK               1020
#define IDC_COMPANY                     1021
#define IDC_COMMENTS                    1022
#define IDC_VER_SYS                     1024
#define IDC_HILITE_CHECK                1025
#define IDC_IGNOREREGEXP                1026
#define IDC_ALL_WHITE                   1027
#define IDC_WHITE_CHANGE                1028
#define IDC_WHITESPACE                  1029
#define IDC_USER                        1031
#define IDC_EOL_SENSITIVE               1032
#define IDC_CP_SENSITIVE                1033
#define IDC_PASSWORD                    1034
#define IDC_DIFFERENCE_COLOR            1035
#define IDC_SEL_DIFFERENCE_COLOR        1037
#define IDC_PROP_INSERT_TABS            1038
#define IDC_PROP_INSERT_SPACES          1040
#define IDC_LANGUAGE_LIST               1041
#define IDC_AUTOMRESCAN_CHECK           1042
#define IDC_DIFFERENCE_USE_TEXT_COLOR   1043
#define IDC_DIFFERENCE_TEXT_COLOR       1044
#define IDC_DIFFERENCE_DELETED_COLOR    1045
#define IDC_SEL_DIFFERENCE_DELETED_COLOR 1046
#define IDC_SEL_DIFFERENCE_USE_TEXT_COLOR 1047
#define IDC_SEL_DIFFERENCE_TEXT_COLOR   1048
#define IDC_EXPLORER_CONTEXT            1049
#define IDC_EXPLORER_ADVANCED           1050
#define IDC_TRIVIAL_DIFF_USE_TEXT_COLOR 1051
#define IDC_TRIVIAL_DIFF_TEXT_COLOR     1052
#define IDC_MOVEDBLOCK_COLOR            1053
#define IDC_MOVEDBLOCK_USE_TEXT_COLOR   1054
#define IDC_MOVEDBLOCK_TEXT_COLOR       1055
#define IDC_MOVEDBLOCK_DELETED_COLOR    1056
#define IDC_SEL_MOVEDBLOCK_COLOR        1057
#define IDC_SEL_MOVEDBLOCK_USE_TEXT_COLOR 1058
#define IDC_SEL_MOVEDBLOCK_TEXT_COLOR   1059
#define IDC_SEL_MOVEDBLOCK_DELETED_COLOR 1060
#define IDC_UP                          1061
#define IDC_DOWN                        1062
#define IDC_PRIVATEBUILD                1063
#define IDC_MIXED_EOL                   1064
#define IDC_DIFF_FILE1                  1065
#define IDC_DIFF_FILE2                  1066
#define IDC_DIFF_FILERESULT             1067
#define IDC_DIFF_STYLE                  1068
#define IDC_DIFF_CONTEXT                1069
#define IDC_DIFF_CASESENSITIVE          1070
#define IDC_DIFF_WHITESPACE_IGNOREBLANKS 1071
#define IDC_DIFF_WHITESPACE_COMPARE     1072
#define IDC_DIFF_WHITESPACE_IGNORE      1073
#define IDC_DIFF_WHITESPACE_IGNOREALL   1074
#define IDC_DIFF_BROWSE_FILE1           1075
#define IDC_DIFF_BROWSE_FILE2           1076
#define IDC_DIFF_BROWSE_RESULT          1077
#define IDC_DIFF_APPENDFILE             1078
#define IDC_DIFF_IGNOREEOL              1079
#define IDC_TRIVIAL_DIFF_COLOR          1080
#define IDC_TRIVIAL_DIFF_DELETED_COLOR  1081
#define IDC_FILES_DIRS_GROUP            1082
#define IDC_DATABASE_LIST               1083
#define IDC_MULTI_CHECKOUT              1084
#define IDC_CHECK2                      1085
#define IDC_BREAK_ON_WORDS              1086
#define IDC_CHECKIN                     1087
#define IDC_VCPROJ_SYNC                 1088
#define IDC_UNPACKER_NAME               1089
#define IDC_UNPACKER_ALLOW_ALL          1090
#define IDC_UNPACKER_SUPPORTED_EXTENSIONS 1091
#define IDC_UNPACKER_DESCRIPTION        1092
#define IDC_UNPACKER_EDIT               1093
#define IDC_SELECT_UNPACKER             1094
#define IDC_EXT_EDITOR_BROWSE           1095
#define IDC_EXT_EDITOR_PATH             1096
#define IDC_DIFF_SWAPFILES              1097
#define IDC_DIFF_OPENTOEDITOR           1098
#define IDC_COMPARISON_STOP             1106
#define IDC_DIFF_INCLCMDLINE            1108
#define IDC_WMGOTO_FILELEFT             1109
#define IDC_WMGOTO_FILEMIDDLE           1110
#define IDC_WMGOTO_FILERIGHT            1111
#define IDC_WMGOTO_TOLINE               1112
#define IDC_WMGOTO_TODIFF               1113
#define IDC_WMGOTO_PARAM                1114
#define IDC_OPEN_CONTRIBUTORS           1115
#define IDC_COMPAREMETHODCOMBO          1116
#define IDC_USE_RECYCLE_BIN             1117
#define IDC_COLORDEFAULTS_BTN           1118
#define IDC_COMPARE_DEFAULTS            1119
#define IDC_DIFF_DEFAULTS               1122
#define IDC_MOVED_BLOCKS                1123
#define IDC_RESET_ALL_MESSAGE_BOXES     1124
#define IDC_COUNT_FOLDER                1125
#define IDC_COLDLG_DEFAULTS             1126
#define IDC_OPEN_STATUS                 1128
#define IDC_FILTERFILE_EDITBTN          1129
#define IDC_FILTERFILE_LIST             1130
#define IDC_ESC_CLOSES_WINDOW           1131
#define IDC_SAVE_AS                     1132
#define IDC_STATIC_TITLE_PANE0          1133
#define IDC_STATIC_TITLE_PANE1          1134
#define IDC_STATIC_TITLE_PANE2          1135
#define IDC_SELECT_FILTER               1136
#define IDC_COLDLG_DESC                 1137
#define IDC_VERIFY_OPEN_PATHS           1138
#define IDC_DETECT_CODEPAGE             1139
#define IDC_SAVECLOSING_SAVELEFT        1140
#define IDC_SAVECLOSING_DISCARDLEFT     1141
#define IDC_SAVECLOSING_SAVEMIDDLE      1142
#define IDC_SAVECLOSING_DISCARDMIDDLE   1143
#define IDC_SAVECLOSING_SAVERIGHT       1144
#define IDC_SAVECLOSING_DISCARDRIGHT    1145
#define IDC_SAVECLOSING_RIGHTFILE       1146
#define IDC_SAVECLOSING_LEFTFILE        1147
#define IDC_SAVECLOSING_MIDDLEFILE      1148
#define IDC_SAVECLOSING_LEFTFRAME       1149
#define IDC_SAVECLOSING_MIDDLEFRAME     1150
#define IDC_SAVECLOSING_RIGHTFRAME      1151
#define IDC_CP_SYSTEM                   1152
#define IDC_CP_UI                       1153
#define IDC_CP_CUSTOM                   1154
#define IDC_CUSTOM_CP_NUMBER            1155
#define IDC_FILTERFILE_NEWBTN           1156
#define IDC_FILTERFILE_DELETEBTN        1157
#define IDC_WORDDIFF_COLOR              1158
#define IDC_SEL_WORDDIFF_COLOR          1159
#define IDC_WORDDIFF_USE_TEXT_COLOR     1160
#define IDC_WORDDIFF_TEXT_COLOR         1161
#define IDC_SEL_WORDDIFF_USE_TEXT_COLOR 1162
#define IDC_SEL_WORDDIFF_TEXT_COLOR     1163
#define IDC_SNP_COLOR                   1164
#define IDC_SNP_DELETED_COLOR           1165
#define IDC_SNP_USE_TEXT_COLOR          1166
#define IDC_SNP_TEXT_COLOR              1167
#define IDC_SEL_SNP_COLOR               1168
#define IDC_SEL_SNP_DELETED_COLOR       1169
#define IDC_SEL_SNP_USE_TEXT_COLOR      1170
#define IDC_SEL_SNP_TEXT_COLOR          1171
#define IDC_TREEOPT_PAGES               1172
#define IDC_TREEOPT_HOSTFRAME           1173
#define IDC_TREEOPT_HELP                1174
#define IDC_SINGLE_INSTANCE             1175
#define IDC_IGNORE_SMALLTIMEDIFF        1176
#define IDC_LINE_COLORING_GROUP         1177
#define IDC_VIEW_LINE_DIFFERENCES       1178
#define IDC_BREAK_TYPE                  1179
#define IDC_SCOLOR_KEYWORDS_BOLD        1180
#define IDC_SCOLOR_KEYWORDS             1181
#define IDC_SCOLOR_FUNCTIONS            1182
#define IDC_SCOLOR_COMMENTS             1183
#define IDC_SCOLOR_NUMBERS              1184
#define IDC_SCOLOR_OPERATORS            1185
#define IDC_SCOLOR_STRINGS              1186
#define IDC_SCOLORS_BDEFAULTS           1187
#define IDC_SCOLOR_PREPROCESSOR         1188
#define IDC_SCOLOR_USER1                1189
#define IDC_SCOLOR_USER2                1190
#define IDC_SCOLOR_COMMENTS_BOLD        1191
#define IDC_SCOLOR_FUNCTIONS_BOLD       1192
#define IDC_SCOLOR_NUMBERS_BOLD         1193
#define IDC_SCOLOR_OPERATORS_BOLD       1194
#define IDC_SCOLOR_STRINGS_BOLD         1195
#define IDC_SCOLOR_PREPROCESSOR_BOLD    1196
#define IDC_SCOLOR_USER1_BOLD           1197
#define IDC_SCOLOR_USER2_BOLD           1198
#define IDC_SAVECLOSING_DISCARDALL      1199
#define IDC_PROGRESSCOMPARE             1200
#define IDC_ITEMSCOMPARED               1201
#define IDC_ITEMSTOTAL                  1202
#define IDC_REPORT_STYLECOMBO           1203
#define IDC_REPORT_BROWSEFILE           1204
#define IDC_REPORT_FILE                 1205
#define IDC_SHARED                      1206
#define IDC_PRIVATE                     1207
#define IDC_COMPARE_STOPFIRST           1208
#define IDC_ARCHIVE_DETECTTYPE          1209
#define IDC_ARCHIVE_ENABLE              1210
#define IDC_DETECT_CODEPAGE2            1211
#define IDC_DETECT_AUTODETECTTYPE       1212
#define IDC_STAT_IDENTICFOLDER          1213
#define IDC_STAT_IDENTICFILE            1214
#define IDC_STAT_IDENTICBINARY          1215
#define IDC_STAT_DIFFFILE               1216
#define IDC_STAT_DIFFBINARY             1217
#define IDC_STAT_LUNIQFOLDER            1218
#define IDC_STAT_LUNIQFILE              1219
#define IDC_STAT_RUNIQFOLDER            1220
#define IDC_STAT_RUNIQFILE              1221
#define IDC_STAT_MUNIQFOLDER            1222
#define IDC_STAT_MUNIQFILE              1223
#define IDC_STAT_LMISSINGFOLDER         1224
#define IDC_STAT_LMISSINGFILE           1225
#define IDC_STAT_RMISSINGFOLDER         1226
#define IDC_STAT_RMISSINGFILE           1227
#define IDC_STAT_MMISSINGFOLDER         1228
#define IDC_STAT_MMISSINGFILE           1229
#define IDC_STAT_TOTALFOLDER            1230
#define IDC_STAT_TOTALFILE              1231
#define IDC_TREEOPT_IMPORT              1232
#define IDC_TREEOPT_EXPORT              1233
#define IDC_STAT_ILUNIQFOLDER           1234
#define IDC_STAT_IRUNIQFOLDER           1235
#define IDC_STAT_IMUNIQFOLDER           1236
#define IDC_STAT_ILMISSINGFOLDER        1237
#define IDC_STAT_IRMISSINGFOLDER        1238
#define IDC_STAT_IMMISSINGFOLDER        1239
#define IDC_STAT_IIDENTICFOLDER         1240
#define IDC_STAT_INOTEQUAL              1241
#define IDC_STAT_IDIFFBINFILE           1242
#define IDC_STAT_ILUNIQFILE             1243
#define IDC_STAT_IRUNIQFILE             1244
#define IDC_STAT_IMUNIQFILE             1245
#define IDC_STAT_ILMISSINGFILE          1246
#define IDC_STAT_IRMISSINGFILE          1247
#define IDC_STAT_IMMISSINGFILE          1248
#define IDC_STAT_IEQUALFILE             1249
#define IDC_STAT_IEQUALBINFILE          1250
#define IDC_EDITOR_CHARLEVEL            1251
#define IDC_EDITOR_WORDLEVEL            1252
#define IDC_AFFECTS_GROUP               1253
#define IDC_AFFECTS_LEFT_BTN            1254
#define IDC_AFFECTS_MIDDLE_BTN          1255
#define IDC_AFFECTS_RIGHT_BTN           1256
#define IDC_LOAD_FILES_LABEL            1257
#define IDC_LOAD_CODEPAGE_TEXTBOX       1258
#define IDC_LOAD_SAVE_SAME_CODEPAGE     1259
#define IDC_SAVE_FILES_LABEL            1260
#define IDC_SAVE_CODEPAGE_TEXTBOX       1261
#define IDC_LOADING_GROUP               1262
#define IDC_SAVING_GROUP                1263
#define IDC_LEFT_FILES_LABEL            1264
#define IDC_MIDDLE_FILES_LABEL          1265
#define IDC_RIGHT_FILES_LABEL           1266
#define IDC_FILTERFILE_TEST_BTN         1267
#define IDC_HEADER                      1268
#define IDC_PROMPT_LABEL                1269
#define IDC_TEST_BTN                    1270
#define IDC_TEST_TEXT                   1271
#define IDC_RESULTS                     1272
#define IDC_IS_DIRECTORY                1273
#define IDC_HEADER_FILTER_NAME          1274
#define IDC_DEFAULT_STANDARD_COLORS     1275
#define IDC_CUSTOM_COLORS_GROUP         1276
#define IDC_WHITESPACE_COLOR_LABEL      1277
#define IDC_TEXT_COLOR_LABEL            1278
#define IDC_SELECTION_COLOR_LABEL       1279
#define IDC_TEXT_COLUMN_LABEL           1280
#define IDC_BACKGROUND_COLUMN_LABEL     1281
#define IDC_WHITESPACE_BKGD_COLOR       1282
#define IDC_REGULAR_BKGD_COLOR          1283
#define IDC_SELECTION_BKGD_COLOR        1284
#define IDC_SELECTION_TEXT_COLOR        1285
#define IDC_REGULAR_TEXT_COLOR          1286
#define IDC_AUTO_COMPLETE_SOURCE        1287
#define IDC_PROJ_RFILE_EDIT             1288
#define IDC_PROJ_FILTER_EDIT            1289
#define IDC_PROJ_LFILE_BROWSE           1290
#define IDC_PROJ_RFILE_BROWSE           1291
#define IDC_PROJ_FILTER_SELECT          1292
#define IDC_PROJ_INC_SUBFOLDERS         1293
#define IDC_PROJ_SAVE                   1294
#define IDC_PROJ_OPEN                   1295
#define IDC_PROJ_LFILE_EDIT             1296
#define IDC_FILTER_USER_BROWSE          1297
#define IDC_FILTER_USER_PATH            1298
#define IDC_FILTERCOMMENTS_CHECK        1299
#define IDC_PROJFILE_LREADONLY          1300
#define IDC_PROJFILE_RREADONLY          1301
#define IDC_FINDDLG_DONTWRAP            1302
#define IDC_REPORT_COPYCLIPBOARD        1303
#define IDC_FILTERFILE_INSTALL          1304
#define IDC_MATCH_SIMILAR_LINES         1305
#define IDC_BACKUP_FILECMP              1306
#define IDC_BACKUP_FOLDERCMP            1307
#define IDC_BACKUP_ORIGFOLD             1308
#define IDC_BACKUP_GLOBALFOLD           1309
#define IDC_BACKUP_BROWSE               1310
#define IDC_BACKUP_FOLDER               1311
#define IDC_BACKUP_APPEND_BAK           1312
#define IDC_BACKUP_APPEND_TIME          1313
#define IDC_FLDCONFIRM_TO_PATH          1314
#define IDC_FLDCONFIRM_QUERY            1315
#define IDC_FLDCONFIRM_FROM_TEXT        1316
#define IDC_FLDCONFIRM_TO_TEXT          1317
#define IDC_FLDCONFIRM_FROM_PATH        1318
#define IDC_FLDCONFIRM_ICON             1319
#define IDC_LFILTER_LIST                1320
#define IDC_LFILTER_ADDBTN              1321
#define IDC_LFILTER_EDITBTN             1322
#define IDC_LFILTER_REMOVEBTN           1323
#define IDC_BUTTON2                     1324
#define IDC_ABOUTBOX_ICON               1325
#define IDC_ASK_MULTIWINDOW_CLOSE       1326
#define IDC_COLDLG_LIST                 1327
#define IDC_PRESERVE_FILETIME           1328
#define IDC_TMPFOLDER_SYSTEM            1329
#define IDC_TMPFOLDER_BROWSE            1330
#define IDC_TMPFOLDER_NAME              1331
#define IDC_PLUGINS_ENABLE              1332
#define IDC_PLUGINSLIST_LIST            1333
#define IDC_STARTUP_FOLDER_SELECT       1334
#define IDC_BREAK_CHARS                 1335
#define IDC_WORDDIFF_DELETED_COLOR      1336
#define IDC_SEL_WORDDIFF_DELETED_COLOR  1337
#define IDC_COMPAREFOLDER_DEFAULTS      1338
#define IDC_COMPARE_WALKSUBDIRS         1339
#define IDC_COMPARE_QUICKC_LIMIT        1340
#define IDC_REPORT_INCLUDEFILECMPREPORT 1341
#define IDC_COMPARE_THREAD_COUNT        1342
#define IDC_SWAP01_BUTTON               1343
#define IDC_SWAP12_BUTTON               1344
#define IDC_SWAP02_BUTTON               1345
#define IDC_COLORSCHEME_GITHUBBITBUCKET 1346
#define IDC_FINDDLG_DONTCLOSE           1347
#define IDC_PATH_COMPARING              1348
#define IDC_REGISTER_SHELLEXTENSION     1349
#define IDC_UNREGISTER_SHELLEXTENSION   1350
#define IDC_MARGIN_COLOR_LABEL          1351
#define IDC_MARGIN_BKGD_COLOR           1352
#define IDC_EDIT_WHOLE_WORD             8603
#define IDC_EDIT_MATCH_CASE             8604
#define IDC_EDIT_FINDTEXT               8605
#define IDC_EDIT_REGEXP                 8606
#define IDC_EDIT_REPLACE                8607
#define IDC_EDIT_REPLACE_ALL            8608
#define IDC_EDIT_REPLACE_WITH           8609
#define IDC_EDIT_SKIP                   8610
#define IDC_EDIT_SCOPE_SELECTION        8613
#define IDC_EDIT_SCOPE_WHOLE_FILE       8614
#define IDC_EDIT_SCOPE_DONT_WRAP        8615
#define IDC_EDIT_FINDPREV               8616
#define IDC_SCRIPT_FIRST                8700
#define IDC_SCRIPT_LAST                 8749
#define IDC_PREDIFFERS_FIRST            8750
#define IDC_PREDIFFERS_LAST             8799
#define IDC_EXPAND_SUBDIRS              8800
#define IDC_FILEENCODING                8801
#define IDC_PLUGIN                      8802
#define IDC_HEXVIEW                     8803
#define IDC_IGNORE_REPARSEPOINTS        8804
#define IDC_CLOSE_WITH_OK               8805
#define IDC_PATH0_READONLY              8806
#define IDC_PATH1_READONLY              8807
#define IDC_PATH2_READONLY              8808
#define IDC_MARKER_ENABLED              8809
#define IDC_MARKER_COLORS_GROUP         8810
#define IDC_MARKER0_COLOR_LABEL         8811
#define IDC_MARKER1_COLOR_LABEL         8812
#define IDC_MARKER2_COLOR_LABEL         8813
#define IDC_MARKER3_COLOR_LABEL         8814
#define IDC_MARKER0_BKGD_COLOR          8815
#define IDC_MARKER1_BKGD_COLOR          8816
#define IDC_MARKER2_BKGD_COLOR          8817
#define IDC_MARKER3_BKGD_COLOR          8818
#define IDC_EDIT_MARKERS_ENABLED        8819
#define IDC_EDIT_MARKER_LIST            8820
#define IDC_EDIT_MARKER_BGCOLORIDX      8821
#define IDC_EDIT_MARKER_NEW             8822
#define IDC_EDIT_MARKER_DELETE          8823
#define IDS_SPLASH_DEVELOPERS           8976
#define IDS_SPLASH_GPLTEXT              8977
#define IDS_MESSAGEBOX_OK               9001
#define IDS_MESSAGEBOX_CANCEL           9002
#define IDS_MESSAGEBOX_ABORT            9003
#define IDS_MESSAGEBOX_RETRY            9004
#define IDS_MESSAGEBOX_IGNORE           9005
#define IDS_MESSAGEBOX_IGNOREALL        9006
#define IDS_MESSAGEBOX_YES              9007
#define IDS_MESSAGEBOX_YES_TO_ALL       9008
#define IDS_MESSAGEBOX_NO               9009
#define IDS_MESSAGEBOX_NO_TO_ALL        9010
#define IDS_MESSAGEBOX_CONTINUE         9011
#define IDS_MESSAGEBOX_SKIP             9012
#define IDS_MESSAGEBOX_SKIPALL          9013
#define IDS_MESSAGEBOX_HELP             9014
#define IDS_MESSAGEBOX_DONT_DISPLAY_AGAIN 9015
#define IDS_MESSAGEBOX_DONT_ASK_AGAIN   9016
#define IDS_MESSAGEBOX_CHECKBOX_TOOLTIP 9017
#define IDS_OPTIONSPG_GENERAL           9041
#define IDS_OPTIONSPG_COMPARE           9042
#define IDS_OPTIONSPG_EDITOR            9043
#define IDS_OPTIONSPG_COLORS            9044
#define IDS_OPTIONSPG_TEXTCOLORS        9045
#define IDS_OPTIONSPG_SYNTAXCOLORS      9046
#define IDS_OPTIONSPG_MARKERCOLORS      9047
#define IDS_OPTIONSPG_SYSTEM            9048
#define IDS_OPTIONSPG_VERSIONCONTROL    9049
#define IDS_OPTIONSPG_CODEPAGE          9050
#define IDS_OPTIONSPG_ARCHIVE           9051
#define IDS_OPTIONSPG_BACKUPS           9052
#define IDS_OPTIONSPG_SHELL             9053
#define IDS_OPTIONSPG_MERGECOLORS       9054
#define IDS_OPTIONSPG_GENCOMPARE        9055
#define IDS_OPTIONSPG_FOLDERCOMPARE     9056
#define IDS_OPTIONSPG_IMAGECOMPARE      9057
#define IDS_OPTIONSPG_BINARYCOMPARE     9058
#define IDS_TO                          16000
#define IDS_FROM_LEFT                   16001
#define IDS_TO_LEFT                     16002
#define IDS_FROM_RIGHT                  16003
#define IDS_TO_RIGHT                    16004
#define IDS_VERSION_FMT                 16385
#define IDS_UNICODE                     16387
#define IDS_WINX64                      16388
#define IDS_OPTIONS_TITLE               16400
#define IDS_MESSAGE_BOX_ARE_RESET       16401
#define IDS_OPTIONS_INVALID_TABSIZE     16404
#define IDS_OPEN_TITLE                  16416
#define IDS_PROGRAMFILES                16417
#define IDS_ALLFILES                    16418
#define IDS_PROJECTFILES                16419
#define IDS_PROJECTFILES_EXT            16420
#define IDS_INIFILES                    16421
#define ID_COMPMETHOD_FULL_CONTENTS     16432
#define ID_COMPMETHOD_QUICK_CONTENTS    16433
#define ID_COMPMETHOD_BINARY_CONTENTS   16434
#define ID_COMPMETHOD_MODDATE           16435
#define ID_COMPMETHOD_DATESIZE          16436
#define ID_COMPMETHOD_SIZE              16437
#define IDS_FILTERFILE_NAMETITLE        16448
#define IDS_FILTERFILE_PATHTITLE        16449
#define IDS_FILTER_TITLE                16450
#define IDS_FILTER_PREFIX               16451
#define IDS_FILTERFILE_DESCTITLE        16452
#define IDS_FILEFILTER_SAVENEW          16453
#define IDS_FILEFILTER_FILEMASK         16454
#define IDS_FILEFILTER_TMPL_MISSING     16455
#define IDS_FILEFILTER_TMPL_COPY        16456
#define IDS_FILEFILTER_NO_USERFOLDER    16457
#define IDS_FILEFILTER_DELETE_FAIL      16458
#define IDS_FILEFILTER_INSTALL          16459
#define IDS_FILEFILTER_INSTALLFAIL      16460
#define IDS_FILEFILTER_OVERWRITE        16461
#define IDS_FILTERLINE_REGEXP           16480
#define IDS_FILTERCHANGED               16496
#define IDS_CC_CMD                      16720
#define IDS_VSS_CMD                     16721
#define IDS_DIRECTORY_WINDOW_TITLE      16800
#define IDS_FILE_COMPARISON_TITLE       16801
#define IDS_EMPTY_LEFT_FILE             16802
#define IDS_EMPTY_MIDDLE_FILE           16803
#define IDS_EMPTY_RIGHT_FILE            16804
#define IDS_CONFLICT_THEIRS_FILE        16805
#define IDS_CONFLICT_MINE_FILE          16806
#define IDS_LINE_STATUS_INFO_EOL        16832
#define IDS_EMPTY_LINE_STATUS_INFO      16833
#define IDS_LINE_STATUS_INFO            16834
#define IDS_MERGEMODE_MERGING           16835
#define IDS_DIFF_NUMBER_STATUS_FMT      16836
#define IDS_NO_DIFF_SEL_FMT             16837
#define IDS_1_DIFF_FOUND                16838
#define IDS_STATUSBAR_READONLY          16839
#define IDS_DIRVIEW_STATUS_FMT_FOCUS    16840
#define IDS_DIRVIEW_STATUS_FMT_NOFOCUS  16841
#define IDS_ERROR_INCOMPARABLE          17200
#define IDS_DIRSEL_TAG                  17201
#define IDS_OPEN_FILESDIRS              17202
#define IDS_OPEN_LEFTINVALID            17203
#define IDS_OPEN_MIDDLEINVALID          17204
#define IDS_OPEN_RIGHTINVALID           17205
#define IDS_OPEN_BOTHINVALID            17206
#define IDS_OPEN_LEFTMIDDLEINVALID      17207
#define IDS_OPEN_LEFTRIGHTINVALID       17208
#define IDS_OPEN_MIDDLERIGHTINVALID     17209
#define IDS_OPEN_ALLINVALID             17210
#define IDS_OPEN_UNPACKERDISABLED       17211
#define IDS_OPEN_MISMATCH               17212
#define IDS_ERROR_FILE_NOT_FOUND        17216
#define IDS_ERROR_FILE_NOT_UNPACKED     17217
#define IDS_ERROR_FILEOPEN              17221
#define IDS_ERROR_CONF_RESOLVE          17222
#define IDS_NOT_CONFLICT_FILE           17223
#define IDS_SAVE_AS_TITLE               17232
#define IDS_SAVE_FMT                    17233
#define IDS_SAVEREADONLY_FMT            17234
#define IDS_ERROR_BACKUP                17236
#define IDS_BACKUP_FAILED_PROMPT        17237
#define IDS_FILESAVE_FAILED             17238
#define IDS_FILEPACK_FAILED_LEFT        17239
#define IDS_FILEPACK_FAILED_MIDDLE      17240
#define IDS_FILEPACK_FAILED_RIGHT       17241
#define IDS_FILECHANGED_ONDISK          17242
#define IDS_SAVEREADONLY_MULTI          17243
#define IDS_FILECHANGED_RESCAN          17244
#define IDS_SAVE_LEFT_AS                17245
#define IDS_SAVE_MIDDLE_AS              17246
#define IDS_SAVE_RIGHT_AS               17247
#define IDS_FILE_DISAPPEARED            17248
#define IDS_NOPROJECT                   17264
#define IDS_VSS_CHECKOUT_STATUS         17265
#define IDS_VSSERROR                    17266
#define IDS_VSS_RUN_ERROR               17267
#define IDS_VSSFOLDER_AND_FILE_NOMATCH  17268
#define IDS_VSS_NODATABASES             17269
#define IDS_VSS_ERRORFROM               17270
#define IDS_VSS_CHECKINERROR            17271
#define IDS_VSS_UNCOERROR               17272
#define IDS_VIEWS_OUTOFSYNC             17300
#define ID_DIR_COPY_LEFT_TO_RIGHT       17600
#define ID_DIR_COPY_LEFT_TO_MIDDLE      17601
#define ID_DIR_COPY_LEFT_TO_BROWSE      17602
#define ID_DIR_COPY_MIDDLE_TO_LEFT      17603
#define ID_DIR_COPY_MIDDLE_TO_RIGHT     17604
#define ID_DIR_COPY_MIDDLE_TO_BROWSE    17605
#define ID_DIR_COPY_RIGHT_TO_LEFT       17606
#define ID_DIR_COPY_RIGHT_TO_MIDDLE     17607
#define ID_DIR_COPY_RIGHT_TO_BROWSE     17608
#define ID_DIR_COPY_LEFT_TO_CLIPBOARD   17609
#define ID_DIR_COPY_MIDDLE_TO_CLIPBOARD 17610
#define ID_DIR_COPY_RIGHT_TO_CLIPBOARD  17611
#define ID_DIR_COPY_BOTH_TO_CLIPBOARD   17612
#define ID_DIR_COPY_ALL_TO_CLIPBOARD    17613
#define ID_DIR_DEL_LEFT                 17614
#define ID_DIR_DEL_MIDDLE               17615
#define ID_DIR_DEL_RIGHT                17616
#define ID_DIR_DEL_BOTH                 17617
#define ID_DIR_DEL_ALL                  17618
#define IDS_COPY_RIGHT_TO_LEFT          17620
#define IDS_COPY_RIGHT_TO_MIDDLE        17621
#define IDS_COPY_MIDDLE_TO_LEFT         17622
#define IDS_COPY_MIDDLE_TO_RIGHT        17623
#define IDS_COPY_LEFT_TO_RIGHT          17624
#define IDS_COPY_LEFT_TO_MIDDLE         17625
#define IDS_COPY_RIGHT_TO_LEFT2         17626
#define IDS_COPY_RIGHT_TO_MIDDLE2       17627
#define IDS_COPY_MIDDLE_TO_LEFT2        17628
#define IDS_COPY_MIDDLE_TO_RIGHT2       17629
#define IDS_COPY_LEFT_TO_RIGHT2         17630
#define IDS_COPY_LEFT_TO_MIDDLE2        17631
#define IDS_COPY_LEFT_TO                17632
#define IDS_COPY_MIDDLE_TO              17633
#define IDS_COPY_RIGHT_TO               17634
#define IDS_COPY_BOTH_TO                17635
#define IDS_COPY_ALL_TO                 17638
#define IDS_COPY_DIFFERENCES_TO         17639
#define IDS_COPY_LEFT_TO2               17640
#define IDS_COPY_MIDDLE_TO2             17641
#define IDS_COPY_RIGHT_TO2              17642
#define IDS_COPY_BOTH_TO2               17643
#define IDS_COPY_ALL_TO2                17645
#define IDS_COPY_DIFFERENCES_TO2        17646
#define IDS_DEL_LEFT_FMT                17671
#define IDS_DEL_MIDDLE_FMT              17672
#define IDS_DEL_RIGHT_FMT               17673
#define IDS_DEL_BOTH_FMT                17674
#define IDS_DEL_ALL_FMT                 17675
#define IDS_DEL_LEFT_FMT2               17676
#define IDS_DEL_MIDDLE_FMT2             17677
#define IDS_DEL_RIGHT_FMT2              17678
#define IDS_DEL_BOTH_FMT2               17679
#define IDS_DEL_ALL_FMT2                17680
#define IDS_MOVE_LEFT_TO                17681
#define IDS_MOVE_MIDDLE_TO              17682
#define IDS_MOVE_RIGHT_TO               17683
#define IDS_MOVE_LEFT_TO2               17684
#define IDS_MOVE_MIDDLE_TO2             17685
#define IDS_MOVE_RIGHT_TO2              17686
#define IDS_SELECT_DEST_LEFT            17687
#define IDS_SELECT_DEST_MIDDLE          17688
#define IDS_SELECT_DEST_RIGHT           17689
#define IDS_FILES_AFFECTED_FMT          17690
#define IDS_FILES_AFFECTED_FMT2         17691
#define IDS_CONFIRM_DELETE_SINGLE       17692
#define IDS_CONFIRM_SINGLE_COPY         17693
#define IDS_CONFIRM_MULTIPLE_COPY       17694
#define IDS_DIRCMP_NOTSYNC              17695
#define IDS_CONFIRM_SINGLE_MOVE         17696
#define IDS_CONFIRM_MULTIPLE_MOVE       17697
#define IDS_CONFIRM_COPY_CAPTION        17698
#define IDS_CONFIRM_MOVE_CAPTION        17699
#define IDS_CONFIRM_CLOSE_WINDOW        17700
#define ID_DIR_OPEN_LEFT                17701
#define ID_DIR_OPEN_LEFT_WITHEDITOR     17702
#define ID_DIR_OPEN_LEFT_WITH           17703
#define ID_DIR_OPEN_LEFT_PARENT_FOLDER  17704
#define ID_DIR_OPEN_MIDDLE              17705
#define ID_DIR_OPEN_MIDDLE_WITHEDITOR   17706
#define ID_DIR_OPEN_MIDDLE_WITH         17707
#define ID_DIR_OPEN_MIDDLE_PARENT_FOLDER 17708
#define ID_DIR_OPEN_RIGHT               17709
#define ID_DIR_OPEN_RIGHT_WITHEDITOR    17710
#define ID_DIR_OPEN_RIGHT_WITH          17711
#define ID_DIR_OPEN_RIGHT_PARENT_FOLDER 17712
#define ID_DIR_COPY_FILENAMES           17713
#define ID_DIR_COPY_PATHNAMES_LEFT      17714
#define ID_DIR_COPY_PATHNAMES_MIDDLE    17715
#define ID_DIR_COPY_PATHNAMES_RIGHT     17716
#define ID_DIR_COPY_PATHNAMES_BOTH      17717
#define ID_DIR_COPY_PATHNAMES_ALL       17718
#define IDS_ERROR_EXECUTE_FILE          17719
#define IDS_UNKNOWN_ARCHIVE_FORMAT      17731
#define IDS_COLHDR_FILENAME             17751
#define IDS_COLHDR_DIR                  17752
#define IDS_COLHDR_RESULT               17753
#define IDS_COLHDR_LTIMEM               17754
#define IDS_COLHDR_RTIMEM               17755
#define IDS_COLHDR_MTIMEM               17756
#define IDS_COLHDR_EXTENSION            17757
#define IDS_COLHDR_LSIZE                17758
#define IDS_COLHDR_RSIZE                17759
#define IDS_COLHDR_MSIZE                17760
#define IDS_COLHDR_RSIZE_SHORT          17761
#define IDS_COLHDR_LSIZE_SHORT          17762
#define IDS_COLHDR_MSIZE_SHORT          17763
#define IDS_COLHDR_LTIMEC               17781
#define IDS_COLHDR_RTIMEC               17782
#define IDS_COLHDR_MTIMEC               17783
#define IDS_COLHDR_NEWER                17784
#define IDS_COLHDR_LVERSION             17785
#define IDS_COLHDR_RVERSION             17786
#define IDS_COLHDR_MVERSION             17787
#define IDS_COLHDR_RESULT_ABBR          17788
#define IDS_COLHDR_LATTRIBUTES          17789
#define IDS_COLHDR_RATTRIBUTES          17790
#define IDS_COLHDR_MATTRIBUTES          17791
#define IDS_COLHDR_LEOL_TYPE            17792
#define IDS_COLHDR_MEOL_TYPE            17793
#define IDS_COLHDR_REOL_TYPE            17794
#define IDS_COLHDR_LENCODING            17811
#define IDS_COLHDR_RENCODING            17812
#define IDS_COLHDR_MENCODING            17813
#define IDS_COLHDR_NIDIFFS              17814
#define IDS_COLHDR_NSDIFFS              17815
#define IDS_COLHDR_BINARY               17816
#define IDS_CANT_COMPARE_FILES          17831
#define IDS_ABORTED_ITEM                17832
#define IDS_FILE_SKIPPED                17833
#define IDS_DIR_SKIPPED                 17834
#define IDS_LEFT_ONLY_IN_FMT            17835
#define IDS_MIDDLE_ONLY_IN_FMT          17836
#define IDS_RIGHT_ONLY_IN_FMT           17837
#define IDS_DOES_NOT_EXIST_IN_FMT       17838
#define IDS_BIN_FILES_SAME              17839
#define IDS_IDENTICAL                   17840
#define IDS_BIN_FILES_DIFF              17841
#define IDS_FILES_ARE_DIFFERENT         17842
#define IDS_FOLDERS_ARE_DIFFERENT       17843
#define IDS_LEFTONLY                    17844
#define IDS_RIGHTONLY                   17845
#define IDS_MIDDLEONLY                  17846
#define IDS_NOITEMLEFT                  17847
#define IDS_NOITEMRIGHT                 17848
#define IDS_NOITEMMIDDLE                17849
#define IDS_DIFFERENT                   17850
#define IDS_CMPRES_ERROR                17851
#define IDS_TEXT_FILES_SAME             17852
#define IDS_TEXT_FILES_DIFF             17861
#define IDS_LEFTONLY_DIFF               17862
#define IDS_MIDDLEONLY_DIFF             17863
#define IDS_RIGHTONLY_DIFF              17864
#define IDS_ELAPSED_TIME                17881
#define IDS_STATUS_SELITEM1             17882
#define IDS_STATUS_SELITEMS             17883
#define IDS_COLDESC_FILENAME            17901
#define IDS_COLDESC_DIR                 17902
#define IDS_COLDESC_RESULT              17903
#define IDS_COLDESC_LTIMEM              17904
#define IDS_COLDESC_RTIMEM              17905
#define IDS_COLDESC_MTIMEM              17906
#define IDS_COLDESC_EXTENSION           17907
#define IDS_COLDESC_LSIZE               17908
#define IDS_COLDESC_RSIZE               17909
#define IDS_COLDESC_MSIZE               17910
#define IDS_COLDESC_LSIZE_SHORT         17911
#define IDS_COLDESC_RSIZE_SHORT         17912
#define IDS_COLDESC_MSIZE_SHORT         17913
#define IDS_COLDESC_LTIMEC              17914
#define IDS_COLDESC_RTIMEC              17915
#define IDS_COLDESC_MTIMEC              17916
#define IDS_COLDESC_NEWER               17917
#define IDS_COLDESC_LVERSION            17918
#define IDS_COLDESC_RVERSION            17919
#define IDS_COLDESC_MVERSION            17920
#define IDS_COLDESC_RESULT_ABBR         17921
#define IDS_COLDESC_LATTRIBUTES         17922
#define IDS_COLDESC_RATTRIBUTES         17923
#define IDS_COLDESC_MATTRIBUTES         17924
#define IDS_COLDESC_LEOL_TYPE           17925
#define IDS_COLDESC_REOL_TYPE           17926
#define IDS_COLDESC_MEOL_TYPE           17927
#define IDS_COLDESC_LENCODING           17941
#define IDS_COLDESC_RENCODING           17942
#define IDS_COLDESC_MENCODING           17943
#define IDS_COLDESC_NIDIFFS             17944
#define IDS_COLDESC_NSDIFFS             17945
#define IDS_COLDESC_BINARY              17946
#define IDS_DIRECTORY_REPORT_TITLE      17962
#define IDS_REPORT_COMMALIST            17963
#define IDS_REPORT_TABLIST              17964
#define IDS_REPORT_SIMPLEHTML           17965
#define IDS_REPORT_SIMPLEXML            17966
#define IDS_REPORT_FILEOVERWRITE        17967
#define IDS_REPORT_ERROR                17968
#define IDS_REPORT_SUCCESS              17969
#define IDS_FILE_TO_ITSELF              18100
#define IDS_FILESSAME                   18101
#define IDS_FILEERROR                   18103
#define IDS_TEMP_FILEERROR              18105
#define IDS_SUGGEST_IGNOREEOL           18107
#define IDS_INVALID_DIRECTORY           18108
#define IDS_CANNOT_OPEN_BINARYFILE      18109
#define IDS_CREATE_PAIR_FOLDER          18110
#define IDS_MOVE_TO_NEXTFILE            18111
#define IDS_MOVE_TO_PREVFILE            18112
#define IDS_MOVE_TO_NEXTPAGE            18113
#define IDS_MOVE_TO_PREVPAGE            18114
#define IDS_SUGGEST_IGNORECODEPAGE      18131
#define IDS_LOSSY_TRANSCODING_FIRST     18132
#define IDS_LOSSY_TRANSCODING_SECOND    18133
#define IDS_LOSSY_TRANSCODING_THIRD     18134
#define IDS_LOSSY_TRANSCODING_BOTH      18135
#define IDS_LINEDIFF_NODIFF             18151
#define IDS_LINEDIFF_NODIFF_CAPTION     18152
#define IDS_NUM_REPLACED                18161
#define IDS_EDIT_TEXT_NOT_FOUND         18162
#define IDS_MERGE_MODE                  18181
#define ID_EDITOR_COPY_PATH             18182
#define ID_EDITOR_COPY_FILENAME         18183
#define ID_EDITOR_COPY                  18184
#define IDS_LOCBAR_CAPTION              18201
#define IDS_DIFFBAR_CAPTION             18202
#define IDS_DIFF_SUCCEEDED              18400
#define IDS_DIFF_ITEM1NOTFOUND          18401
#define IDS_DIFF_ITEM2NOTFOUND          18402
#define IDS_DIFF_FILEOVERWRITE          18403
#define IDS_DIFF_SELECTEDFILES          18404
#define IDS_DIFF_NORMAL                 18405
#define IDS_DIFF_CONTEXT                18406
#define IDS_DIFF_UNIFIED                18407
#define IDS_DIFF_HTML                   18408
#define IDS_FILEWRITE_ERROR             18409
#define IDS_PATH_NOT_ABSOLUTE           18410
#define IDS_MUST_SPECIFY_OUTPUT         18411
#define IDS_CANNOT_CREATE_BINARYPATCH   18412
#define IDS_CANNOT_CREATE_DIRPATCH      18413
#define IDS_SAVEFILES_FORPATCH          18414
#define IDS_FOLDER_NOTEXIST             18415
#define IDS_NO_ZIP_SUPPORT              18449
#define IDS_OPT_EXPORT_CAPTION          18452
#define IDS_OPT_IMPORT_CAPTION          18453
#define IDS_OPT_IMPORT_DONE             18454
#define IDS_OPT_EXPORT_DONE             18455
#define IDS_OPT_IMPORT_ERR              18456
#define IDS_OPT_EXPORT_ERR              18457
#define IDS_CLOSEALL_WINDOWS            18458
#define IDS_VCS_NONE                    18471
#define IDS_VCS_VSS4                    18472
#define IDS_VCS_VSS5                    18473
#define IDS_VCS_CLEARCASE               18474
#define IDS_BREAK_ON_WHITESPACE         18491
#define IDS_BREAK_ON_PUNCTUATION        18492
#define IDS_UNK_ERROR_READING_PROJECT   18510
#define IDS_UNK_ERROR_SAVING_PROJECT    18511
#define IDS_PROJFILEDLG_CAPTION         18512
#define IDS_PROJFILE_LOAD_SUCCESS       18513
#define IDS_PROJFILE_SAVE_SUCCESS       18514
#define IDS_TEXT_REPORT_FILES           18540
#define IDS_HTML_REPORT_FILES           18541
#define IDS_XML_REPORT_FILES            18542
#define ID_EDIT_MARK                    21406 // editcmd.h
#define IDS_EOL_DOS                     30400
#define IDS_EOL_MAC                     30401
#define IDS_EOL_UNIX                    30402
#define IDS_EOL_MIXED                   30403
#define IDS_EOL_BIN                     30404
#define IDS_EOL_LF                      30405
#define IDS_EOL_CR                      30406
#define IDS_EOL_CRLF                    30407
#define IDS_EOL_NONE                    30408
#define IDS_SUFFIX_BYTE                 30416
#define IDS_SUFFIX_KILO                 30417
#define IDS_SUFFIX_MEGA                 30418
#define IDS_SUFFIX_GIGA                 30419
#define IDS_SUFFIX_TERA                 30420
#define IDS_SUFFIX_PETA                 30421
#define IDS_PLUGINSLIST_NAME            30432
#define IDS_PLUGINSLIST_TYPE            30433
#define IDS_PLUGINSLIST_DESC            30434
#define IDS_PLUGINS_TYPE_UNPACKER       30435
#define IDS_PLUGINS_TYPE_PREDIFFER      30436
#define IDS_PLUGINS_TYPE_EDITSCRIPT     30437
#define ID_FILE_NEW3                    32767
#define ID_FILE_SAVE_LEFT               32768
#define ID_FILE_SAVE_MIDDLE             32769
#define ID_FILE_SAVE_RIGHT              32770
#define ID_FILE_SAVEAS_LEFT             32771
#define ID_FILE_SAVEAS_MIDDLE           32772
#define ID_FILE_SAVEAS_RIGHT            32773
#define ID_FILE_LEFT_READONLY           32774
#define ID_FILE_MIDDLE_READONLY         32775
#define ID_FILE_RIGHT_READONLY          32776
#define ID_EOL_TO_DOS                   32777
#define ID_EOL_TO_UNIX                  32778
#define ID_EOL_TO_MAC                   32779
#define ID_FILE_MERGINGMODE             32780
#define ID_SELECTPREVLINEDIFF           32783
#define ID_SELECTLINEDIFF               32784
#define ID_EDIT_WMGOTO                  32785
#define ID_OPTIONS                      32786
#define ID_REFRESH                      32787
#define ID_EDIT_COPY_LINENUMBERS        32788
#define ID_RESCAN                       32789
#define ID_EDIT_FIND_PREVIOUS           32799
#define ID_OPTIONS_SHOWIDENTICAL        32800
#define ID_OPTIONS_SHOWDIFFERENT        32801
#define ID_OPTIONS_SHOWUNIQUELEFT       32802
#define ID_OPTIONS_SHOWUNIQUEMIDDLE     32803
#define ID_OPTIONS_SHOWUNIQUERIGHT      32804
#define ID_OPTIONS_SHOWBINARIES         32805
#define ID_OPTIONS_SHOWSKIPPED          32806
#define ID_OPTIONS_SHOWDIFFERENTLEFTONLY 32807
#define ID_OPTIONS_SHOWDIFFERENTMIDDLEONLY 32808
#define ID_OPTIONS_SHOWDIFFERENTRIGHTONLY 32809
#define ID_VIEW_SELECTFONT              32816
#define ID_VIEW_USEDEFAULTFONT          32817
#define ID_VIEW_WHITESPACE              32818
#define ID_VIEW_DETAIL_BAR              32819
#define ID_VIEW_LOCATION_BAR            32820
#define ID_VIEW_DIR_STATISTICS          32821
#define ID_VIEW_LINEDIFFS               32823
#define ID_VIEW_WORDWRAP                32824
#define ID_VIEW_LINENUMBERS             32825
#define ID_VIEW_TAB_BAR                 32826
#define ID_VIEW_TREEMODE                32827
#define ID_VIEW_EXPAND_ALLSUBDIRS       32828
#define ID_VIEW_COLLAPSE_ALLSUBDIRS     32829
#define ID_PREVDIFF                     32832
#define ID_NEXTDIFF                     32833
#define ID_PREVCONFLICT                 32834
#define ID_NEXTCONFLICT                 32835
#define ID_PREVDIFFLM                   32836
#define ID_NEXTDIFFLM                   32837
#define ID_PREVDIFFLR                   32838
#define ID_NEXTDIFFLR                   32839
#define ID_PREVDIFFMR                   32840
#define ID_NEXTDIFFMR                   32841
#define ID_PREVDIFFLO                   32842
#define ID_NEXTDIFFLO                   32845
#define ID_PREVDIFFMO                   32846
#define ID_NEXTDIFFMO                   32847
#define ID_PREVDIFFRO                   32848
#define ID_NEXTDIFFRO                   32849
#define ID_FIRSTDIFF                    32850
#define ID_CURDIFF                      32851
#define ID_LASTDIFF                     32852
#define ID_L2R                          32853
#define ID_R2L                          32854
#define ID_L2RNEXT                      32855
#define ID_R2LNEXT                      32856
#define ID_ALL_RIGHT                    32857
#define ID_ALL_LEFT                     32858
#define ID_AUTO_MERGE                   32859
#define ID_MERGE_DELETE                 32860
#define ID_TOOLS_CUSTOMIZECOLUMNS       32864
#define ID_TOOLS_GENERATEPATCH          32865
#define ID_TOOLS_FILTERS                32866
#define ID_TOOLS_GENERATEREPORT         32868
#define ID_MERGE_COMPARE                32869
#define ID_MERGE_COMPARE_XML            32870
#define ID_MERGE_COMPARE_HEX            32871
#define ID_MERGE_COMPARE_LEFT1_LEFT2    32872
#define ID_MERGE_COMPARE_RIGHT1_RIGHT2  32873
#define ID_MERGE_COMPARE_LEFT1_RIGHT2   32874
#define ID_MERGE_COMPARE_LEFT2_RIGHT1   32875
#define ID_UNPACK_MANUAL                32880
#define ID_UNPACK_AUTO                  32881
#define ID_POPUP_OPEN_WITH_UNPACKER     32882
#define ID_NO_PREDIFFER                 32883
#define ID_SUGGESTED_PLUGINS            32884
#define ID_NOT_SUGGESTED_PLUGINS        32885
#define ID_RELOAD_PLUGINS               32886
#define ID_WINDOW_CHANGE_PANE           32896
#define ID_WINDOW_CLOSEALL              32897
#define ID_HELP_CONTENTS                32912
#define ID_HELP_GETCONFIG               32913
#define ID_HELP_GNULICENSE              32914
#define ID_HELP_SEARCH                  32916
#define ID_PREDIFF_MANUAL               32929
#define ID_PREDIFF_AUTO                 32930
#define ID_NO_EDIT_SCRIPTS              32931
#define ID_NO_SCT_SCRIPTS               32932
#define ID_FILE_OPEN_REGISTERED         32944
#define ID_FILE_OPEN_WITHEDITOR         32945
#define ID_FILE_OPEN_WITH               32946
#define ID_STATUS_MERGINGMODE           32960
#define ID_STATUS_DIFFNUM               32961
#define ID_STATUS_RIGHTDIR_RO           32962
#define ID_STATUS_LEFTDIR_RO            32963
#define ID_STATUS_MIDDLEDIR_RO          32964
#define ID_STATUS_PANE0FILE_RO          32970
#define ID_STATUS_PANE1FILE_RO          32971
#define ID_STATUS_PANE2FILE_RO          32972
#define ID_STATUS_PANE0FILE_INFO        32973
#define ID_STATUS_PANE1FILE_INFO        32974
#define ID_STATUS_PANE2FILE_INFO        32975
#define ID_STATUS_PANE0FILE_EOL         32976
#define ID_STATUS_PANE1FILE_EOL         32977
#define ID_STATUS_PANE2FILE_EOL         32978
#define ID_STATUS_PANE0FILE_ENCODING    32979
#define ID_STATUS_PANE1FILE_ENCODING    32980
#define ID_STATUS_PANE2FILE_ENCODING    32981
#define ID_STATUS_FILTER                32982
#define ID_STATUS_PLUGIN                32983
#define ID_DIR_ZIP_LEFT                 32991
#define ID_DIR_ZIP_MIDDLE               32992
#define ID_DIR_ZIP_RIGHT                32993
#define ID_DIR_ZIP_BOTH                 32994
#define ID_DIR_ZIP_ALL                  32995
#define ID_DIR_ZIP_BOTH_DIFFS_ONLY      32996
#define ID_DIR_MOVE_LEFT_TO_BROWSE      32997
#define ID_DIR_MOVE_MIDDLE_TO_BROWSE    32998
#define ID_DIR_MOVE_RIGHT_TO_BROWSE     32999
#define ID_DIR_HIDE_FILENAMES           33000
#define ID_DIR_ITEM_RENAME              33001
#define ID_DIR_SHELL_CONTEXT_MENU_LEFT  33002
#define ID_DIR_SHELL_CONTEXT_MENU_MIDDLE 33003
#define ID_DIR_SHELL_CONTEXT_MENU_RIGHT 33004
#define ID_SCRIPT_FIRST                 33012
#define ID_SCRIPT_LAST                  33059
#define ID_PREDIFFERS_FIRST             33060
#define ID_PREDIFFERS_LAST              33107
#define ID_DISPLAY_MOVED_NONE           33111
#define ID_DISPLAY_MOVED_ALL            33112
#define ID_DISPLAY_MOVED_FOLLOW_DIFF    33113
#define ID_LOCBAR_GOTODIFF              33114
#define IDS_LOCBAR_GOTOLINE_FMT         33115
#define ID_FILE_OPENPROJECT             33116
#define ID_VIEW_SHOWHIDDENITEMS         33117
#define ID_VIEW_SWAPPANES               33118
#define ID_FILE_SAVEPROJECT             33119
#define ID_FILE_ENCODING                33120
#define ID_FILE_OPENCONFLICT            33121
#define IDS_AUTOCOMPLETE_DISABLED       33142
#define IDS_AUTOCOMPLETE_FILE_SYS       33143
#define IDS_AUTOCOMPLETE_MRU            33144
#define ID_EDIT_TOGGLE_BOOKMARK         33145
#define ID_EDIT_GOTO_NEXT_BOOKMARK      33146
#define ID_EDIT_GOTO_PREV_BOOKMARK      33147
#define ID_EDIT_CLEAR_ALL_BOOKMARKS     33148
#define ID_VIEW_FILEMARGIN              33150
#define ID_VIEW_CHANGESCHEME            33151
#define ID_COLORSCHEME_FIRST            33152
#define IDS_COLORSCHEME_PLAIN           33152 // = ID_COLORSCHEME_FIRST
#define IDS_COLORSCHEME_ASP             33153
#define IDS_COLORSCHEME_BASIC           33154
#define IDS_COLORSCHEME_BATCH           33155
#define IDS_COLORSCHEME_C               33156
#define IDS_COLORSCHEME_CSHARP          33157
#define IDS_COLORSCHEME_CSS             33158
#define IDS_COLORSCHEME_DCL             33159
#define IDS_COLORSCHEME_FORTRAN         33160
#define IDS_COLORSCHEME_GO              33161
#define IDS_COLORSCHEME_HTML            33162
#define IDS_COLORSCHEME_INI             33163
#define IDS_COLORSCHEME_INNOSETUP       33164
#define IDS_COLORSCHEME_INSTALLSHIELD   33165
#define IDS_COLORSCHEME_JAVA            33166
#define IDS_COLORSCHEME_LISP            33167
#define IDS_COLORSCHEME_NSIS            33168
#define IDS_COLORSCHEME_PASCAL          33169
#define IDS_COLORSCHEME_PERL            33170
#define IDS_COLORSCHEME_PHP             33171
#define IDS_COLORSCHEME_PO              33172
#define IDS_COLORSCHEME_POWERSHELL      33173
#define IDS_COLORSCHEME_PYTHON          33174
#define IDS_COLORSCHEME_REXX            33175
#define IDS_COLORSCHEME_RSRC            33176
#define IDS_COLORSCHEME_RUBY            33177
#define IDS_COLORSCHEME_RUST            33178
#define IDS_COLORSCHEME_SGML            33179
#define IDS_COLORSCHEME_SH              33180
#define IDS_COLORSCHEME_SIOD            33181
#define IDS_COLORSCHEME_SQL             33182
#define IDS_COLORSCHEME_TCL             33183
#define IDS_COLORSCHEME_TEX             33184
#define IDS_COLORSCHEME_VERILOG         33185
#define IDS_COLORSCHEME_VHDL            33186
#define IDS_COLORSCHEME_XML             33187
#define ID_COLORSCHEME_LAST             33187 // = IDS_COLORSCHEME_XML
#define ID_TOOLBAR_NONE                 33194
#define ID_TOOLBAR_SMALL                33195
#define ID_TOOLBAR_BIG                  33196
#define ID_TOOLBAR_HUGE                 33197
#define ID_VIEW_RESIZE_PANES            33198
#define ID_VIEW_ZOOMIN                  33199
#define ID_VIEW_ZOOMOUT                 33200
#define ID_VIEW_ZOOMNORMAL              33202
#define ID_PLUGINS_LIST                 33203
#define ID_PREDIFFER_MANUAL             33204
#define ID_PREDIFFER_AUTO               33205
#define ID_VIEW_EXPAND                  33206
#define ID_VIEW_COLLAPSE                33207
#define ID_VIEW_DIFFCONTEXT_ALL         33208
#define ID_VIEW_DIFFCONTEXT_0           33209
#define ID_VIEW_DIFFCONTEXT_1           33210
#define ID_VIEW_DIFFCONTEXT_3           33221
#define ID_VIEW_DIFFCONTEXT_5           33222
#define ID_VIEW_DIFFCONTEXT_7           33223
#define ID_VIEW_DIFFCONTEXT_9           33224
#define ID_VIEW_DIFFCONTEXT_TOGGLE      33225
#define ID_EDIT_LOWERCASE               33226
#define ID_EDIT_UPPERCASE               33227
#define ID_VIEW_SPLITVERTICALLY         33228
#define IDS_FRHED_NOTINSTALLED          33229
#define ID_ADD_SYNCPOINT                33230
#define ID_CLEAR_SYNCPOINTS             33231
#define ID_CLOSE_OTHER_TABS             33232
#define ID_CLOSE_RIGHT_TABS             33233
#define ID_CLOSE_LEFT_TABS              33234
#define IDS_AUTO_MERGE                  33241
#define ID_COPY_FROM_LEFT               33242
#define ID_COPY_FROM_RIGHT              33243
#define IDS_CODEPAGE_MERGED             33244
#define IDS_CODEPAGE_CONFLICT           33245
#define IDS_EOL_MERGED                  33246
#define IDS_EOL_CONFLICT                33247
#define ID_NO_MRU                       33248
#define ID_MRU_FIRST                    33249
#define ID_MRU_LAST                     33350
#define ID_TABBAR_AUTO_MAXWIDTH         33351
#define IDS_IMAGE_MENU                  33352
#define ID_IMG_VIEWDIFFERENCES          33353
#define ID_IMG_ZOOM_25                  33354
#define ID_IMG_ZOOM_50                  33355
#define ID_IMG_ZOOM_100                 33356
#define ID_IMG_ZOOM_200                 33357
#define ID_IMG_ZOOM_400                 33358
#define ID_IMG_ZOOM_800                 33359
#define ID_IMG_OVERLAY_NONE             33360
#define ID_IMG_OVERLAY_XOR              33361
#define ID_IMG_OVERLAY_ALPHABLEND       33362
#define ID_IMG_OVERLAY_ALPHABLEND_ANIM  33363
#define ID_IMG_DIFFBLOCKSIZE_1          33364
#define ID_IMG_DIFFBLOCKSIZE_2          33365
#define ID_IMG_DIFFBLOCKSIZE_4          33366
#define ID_IMG_DIFFBLOCKSIZE_8          33367
#define ID_IMG_DIFFBLOCKSIZE_16         33368
#define ID_IMG_DIFFBLOCKSIZE_32         33369
#define ID_IMG_PREVPAGE                 33370
#define ID_IMG_NEXTPAGE                 33371
#define ID_IMG_CURPANE_PREVPAGE         33372
#define ID_IMG_CURPANE_NEXTPAGE         33373
#define ID_IMG_USEBACKCOLOR             33374
#define ID_IMG_THRESHOLD_0              33375
#define ID_IMG_THRESHOLD_2              33376
#define ID_IMG_THRESHOLD_4              33377
#define ID_IMG_THRESHOLD_8              33378
#define ID_IMG_THRESHOLD_16             33379
#define ID_IMG_THRESHOLD_32             33380
#define ID_IMG_THRESHOLD_64             33381
#define ID_IMG_DRAGGINGMODE_NONE        33382
#define ID_IMG_DRAGGINGMODE_MOVE        33383
#define ID_IMG_DRAGGINGMODE_ADJUST_OFFSET 33384
#define IDC_COMPAREIMAGE_PATTERNS       33385
#define IDC_COMPAREIMAGE_DEFAULTS       33386
#define IDC_PLUGIN_SETTINGS             33387
#define IDC_COMPAREBINARY_PATTERNS      33388
#define IDC_COMPAREBINARY_VIEWSETTINGS  33389
#define IDC_COMPAREBINARY_BINARYMODE    33390
#define IDC_COMPAREBINARY_CHARACTERSET  33391
#define IDC_COMPAREBINARY_DEFAULTS      33392
#define ID_HELP_RELEASENOTES            33394
#define ID_HELP_TRANSLATIONS            33395
#define IDS_COMPMETHOD_FULL_CONTENTS    33398
#define IDS_COMPMETHOD_QUICK_CONTENTS   33399
#define IDS_COMPMETHOD_BINARY_CONTENTS  33400
#define IDS_COMPMETHOD_MODDATE          33401
#define IDS_COMPMETHOD_DATESIZE         33402
#define IDS_COMPMETHOD_SIZE             33403
#define IDS_UNPACK_AUTO                 33494
#define IDS_NO_PREDIFFER                33495
#define IDS_SUGGESTED_PLUGINS           33496
#define IDS_NOT_SUGGESTED_PLUGINS       33497
#define IDS_PRIVATEBUILD_FMT            33501
#define IDS_CHECKFORUPDATES_UPTODATE    33502
#define IDS_CHECKFORUPDATES_NEWVERSION  33503
#define IDS_CHECKFORUPDATES_FAILED      33504
#define IDS_TITLE_PLUGINS_SETTINGS      33521
#define IDS_NO_EDIT_SCRIPTS             33522
#define IDS_NO_SCT_SCRIPTS              33523
#define IDS_USERCHOICE_NONE             33524
#define IDS_USERCHOICE_AUTOMATIC        33525
#define IDS_CLOSE_LEFT_TABS             33541
#define IDS_CLOSE_RIGHT_TABS            33542
#define IDS_CLOSE_OTHER_TABS            33543
#define IDS_TABBAR_AUTO_MAXWIDTH        33544
#define ID_FILE_PROJECT_MRU_FIRST       33545
#define ID_FILE_PROJECT_MRU_LAST        33644
#define IDS_CREATE_FOLDER               33645
#define IDS_CREATE_FOLDER_ERROR         33646

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        247
#define _APS_NEXT_COMMAND_VALUE         33647
#define _APS_NEXT_CONTROL_VALUE         8817
#define _APS_NEXT_SYMED_VALUE           115
#endif
#endif
