//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Merge.rc
//
#define IDC_CUT                         3
#define IDC_COPY                        4
#define IDC_PASTE                       5
#define IDC_UNDO                        6
#define IDSAVEAS                        7
#define IDD_ABOUTBOX                    100
#define IDR_POPUP_DIFFVIEW              101
#define IDR_POPUP_DIRVIEW               102

#define IDD_PROP_VSS                    103
#define IDR_MAINFRAME                   104
#define IDR_MERGETYPE                   105
#define IDD_OPEN                        106
#define IDD_EDITFILE                    107
#define IDD_VSS                         108
#define IDD_PROPPAGE_LARGE              109
#define IDD_CLEARCASE                   110
#define IDD_PROPPAGE_FILTER             111
#define IDD_OUTPUT                      112
#define IDS_VERSION_FMT                 130

#define IDS_ALLFILES                    131
#define IDS_CONFIRM_ALL_LEFT            132
#define IDS_CONFIRM_ALL_RIGHT           133
#define IDS_ERRORS_TITLE                134
#define IDS_CONFIRM_COPY2DIR            135
#define IDS_FONT_CHANGE                 136
#define IDS_DIRECTORY_WINDOW_TITLE      137
#define IDS_DIRECTORY_WINDOW_STATUS_FMT 138
#define IDS_FILES_ARE_DIFFERENT         139
#define IDS_BIN_FILES_DIFF              140
#define IDS_ONLY_IN_FMT                 141
#define IDS_IDENTICAL                   142
#define IDS_CANT_COMPARE_FILES          143
#define IDS_SAVE_AS_TITLE               144
#define IDS_SELECT_FILES_OR_FOLDERS     145
#define IDS_BACKUP_FAILED_PROMPT        146
#define IDS_PROPERTIES_TITLE            147
#define IDS_OPEN_TITLE                  148
#define IDS_CONFIRM_DELETE              149
#define IDS_CONFIRM_DELETE_FILE         149
#define IDS_EDIT_WINDOW_TITLE_FMT       150
#define IDS_FILESSAME                   151
#define IDS_FILEUNIQUE                  152
#define IDS_FILEERROR                   153
#define IDS_SAVEREADONLY_FMT            154
#define IDS_SAVE_FMT                    155
#define IDS_FILEBINARY                  156
#define IDS_SAVEVSS_FMT                 157
#define IDS_VSSERROR                    158
#define IDS_NOPROJECT                   159
#define IDS_FILENAME_HEADER             160
#define IDS_DIR_HEADER                  161
#define IDS_RESULT_HEADER               162
#define IDS_FILE_COMPARISON_TITLE       163
#define IDS_DIFF_NUMBER_STATUS_FMT      164
#define IDS_NO_DIFF_SEL                 165
#define IDS_NO_DIFF_SEL_FMT             165
#define IDS_FILEISDIR                   166
#define IDS_CC_CMD                      167
#define IDS_VSS_CMD                     168
#define IDS_VSS_RUN_ERROR               169
#define IDS_DIFF_OPEN_NO_SET_PROPS      170
#define IDS_LTIME_HEADER                171
#define IDS_RTIME_HEADER                172
#define IDS_EXTENSION_HEADER            173
#define IDS_CONFIRM_DELETE_ITEMS        174
#define IDS_DEL_LEFT_FMT                175
#define IDS_DEL_RIGHT_FMT               176
#define IDS_DELETE_FAILED               177
#define IDS_DELETE_FILE_FAILED          177
#define IDS_CONFIRM_DELETE_DIR          178
#define IDS_REMOVE_DIR_FAILED           179
#define IDS_COPY_TO_LEFT                180
#define IDS_COPY_TO_LEFT_MAIN           181
#define IDS_DEL_BOTH_FMT                181
#define IDS_COPY_TO_RIGHT               182
#define IDS_COPY_TO_RIGHT_MAIN          183
#define IDS_DELETE_DIR_FAILED           184
#define IDS_COPY_FILE_FAILED            185
#define IDS_COPY_DIR_FAILED             186
#define IDS_ERROR_FILE_WRITEABLE        187
#define IDS_ERROR_BACKUP                188
#define IDS_CONFIRM_COPY_SINGLE         189
#define IDS_CONFIRM_DELETE_SINGLE       190
#define IDB_EQUAL                       213
#define IDB_NOTEQUAL                    214
#define IDB_RFOLDER                     215
#define IDB_UNKNOWN                     216
#define IDB_BINARY                      217
#define IDB_LFILE                       218
#define IDB_RFILE                       219
#define IDB_SPLASH                      220
#define IDB_WINMERGE                    221
#define IDB_OLDSPLASH                   222
#define IDB_LFOLDER                     223

#define IDC_LEFT_EDIT                   1000
#define IDC_FILE_EDIT                   1000
#define IDC_LEFT_BUTTON                 1001
#define IDC_RIGHT_EDIT                  1002
#define IDC_LEFT_COMBO                  1002
#define IDC_RIGHT_BUTTON                1003
#define IDC_RIGHT_COMBO                 1004
#define IDC_PROJECT_COMBO               1004
#define IDC_MESSAGE                     1005
#define IDC_EXT_COMBO                   1005
#define IDC_DOVSS_CHECK                 1006
#define IDC_PATH_EDIT                   1007
#define IDC_BROWSE_BUTTON               1008
#define IDC_BACKUP_CHECK                1009
#define IDC_SCROLL_CHECK                1010
#define IDC_VSS_L1                      1010
#define IDC_WHITESPACE_CHECK            1011
#define IDC_RECURS_CHECK                1011
#define IDC_VERSION                     1012
#define IDC_IGNBLANKS_CHECK             1012
#define IDC_TAB_EDIT                    1013
#define IDC_WWW                         1014
#define IDC_IGNCASE_CHECK               1014
#define IDC_EMAIL                       1015
#define IDC_COMPANY                     1016
#define IDC_COMMENTS                    1017
#define IDC_VER_SYS                     1018
#define IDC_HILITE_CHECK                1019
#define IDC_IGNOREREGEXP                1020
#define IDC_EDITPATTERN                 1021
#define IDC_DISABLE_SPLASH              1023
#define IDC_ALL_WHITE                   1024
#define IDC_WHITE_CHANGE                1025
#define IDC_WHITESPACE                  1026
#define IDC_USER                        1027
#define IDC_EOL_SENSITIVE               1027
#define IDC_PASSWORD                    1028
#define IDC_DIFFERENCE_COLOR            1031
#define IDC_SEL_DIFFERENCE_COLOR        1032
#define IDC_EDIT1                       1033
#define IDC_PROP_INSERT_TABS            1034
#define IDC_PROP_INSERT_SPACES          1035
#define IDR_MARGIN_CURSOR               22900
#define IDD_LANGUAGE_SELECT             30000
#define IDD_PROPSYNTAX                  30001
#define IDD_PROPPAGE_COLORS             30002
#define IDS_AFRIKAANS                   30003
#define IDS_ALBANIAN                    30004
#define IDS_ARABIC_SAUDI                30005
#define IDS_ARABIC_IRAQ                 30006
#define IDS_ARABIC_EGYPT                30007
#define IDS_ARABIC_LIBYA                30008
#define IDS_ARABIC_ALGERIA              30009
#define IDS_ARABIC_MOROCCO              30010
#define IDS_ARABIC_TUNISIA              30011
#define IDS_ARABIC_OMAN                 30012
#define IDS_ARABIC_YEMEN                30013
#define IDS_ARABIC_SYRIA                30014
#define IDS_ARABIC_JORDAN               30015
#define IDS_ARABIC_LEBANON              30016
#define IDS_ARABIC_KUWAIT               30017
#define IDS_ARABIC_UAE                  30018
#define IDS_ARABIC_BAHRAIN              30019
#define IDS_ARABIC_QATAR                30020
#define IDS_BASQUE                      30021
#define IDS_BELARUSIAN                  30022
#define IDS_BULGARIAN                   30023
#define IDS_CATALAN                     30024
#define IDS_CHINESE_TRADITIONAL         30025
#define IDS_CHINESE_SIMPLIFIED          30026
#define IDS_CHINESE_HONGKONG            30027
#define IDS_CHINESE_SINGAPORE           30028
#define IDS_CROATIAN                    30029
#define IDS_CZECH                       30030
#define IDS_DANISH                      30031
#define IDS_DUTCH                       30032
#define IDS_ENGLISH_US                  30033
#define IDS_ENGLISH_UK                  30034
#define IDS_ENGLISH_AUS                 30035
#define IDS_ENGLISH_CAN                 30036
#define IDS_ENGLISH_NZ                  30037
#define IDS_ENGLISH_EIRE                30038
#define IDS_ENGLISH_SOUTH_AFRICA        30039
#define IDS_ENGLISH_JAMAICA             30040
#define IDS_ENGLISH_CARIBBEAN           30041
#define IDS_ENGLISH_BELIZE              30042
#define IDS_ENGLISH_TRINIDAD            30043
#define IDS_ESTONIAN                    30044
#define IDS_FAEROESE                    30045
#define IDS_FARSI                       30046
#define IDS_FINNISH                     30047
#define IDS_FRENCH                      30048
#define IDS_FRENCH_BELGIAN              30049
#define IDS_FRENCH_CANADIAN             30050
#define IDS_FRENCH_SWISS                30051
#define IDS_FRENCH_LUXEMBOURG           30052
#define IDS_GERMAN                      30053
#define IDS_GERMAN_SWISS                30054
#define IDS_GERMAN_AUSTRIAN             30055
#define IDS_GERMAN_LUXEMBOURG           30056
#define IDS_GERMAN_LIECHTENSTEIN        30057
#define IDS_GREEK                       30058
#define IDS_HEBREW                      30059
#define IDS_HUNGARIAN                   30060
#define IDS_ICELANDIC                   30061
#define IDS_INDONESIAN                  30062
#define IDS_ITALIAN                     30063
#define IDS_ITALIAN_SWISS               30064
#define IDS_JAPANESE                    30065
#define IDS_KOREAN                      30066
#define IDS_KOREAN_JOHAB                30067
#define IDS_LATVIAN                     30068
#define IDS_LITHUANIAN                  30069
#define IDS_NORWEGIAN_BOKMAL            30070
#define IDS_NORWEGIAN_NYNORSK           30071
#define IDS_POLISH                      30072
#define IDS_PORTUGUESE                  30073
#define IDS_PORTUGUESE_BRAZILIAN        30074
#define IDS_ROMANIAN                    30075
#define IDS_RUSSIAN                     30076
#define IDS_SERBIAN_LATIN               30077
#define IDS_SERBIAN_CYRILLIC            30078
#define IDS_SLOVAK                      30079
#define IDS_SLOVENIAN                   30080
#define IDS_SPANISH                     30081
#define IDS_SPANISH_MEXICAN             30082
#define IDS_SPANISH_MODERN              30083
#define IDS_SPANISH_GUATEMALA           30084
#define IDS_SPANISH_COSTA_RICA          30085
#define IDS_SPANISH_PANAMA              30086
#define IDS_SPANISH_DOMINICAN           30087
#define IDS_SPANISH_VENEZUELA           30088
#define IDS_SPANISH_COLOMBIA            30089
#define IDS_SPANISH_PERU                30090
#define IDS_SPANISH_ARGENTINA           30091
#define IDS_SPANISH_ECUADOR             30092
#define IDS_SPANISH_CHILE               30093
#define IDS_SPANISH_URUGUAY             30094
#define IDS_SPANISH_PARAGUAY            30095
#define IDS_SPANISH_BOLIVIA             30096
#define IDS_SPANISH_EL_SALVADOR         30097
#define IDS_SPANISH_HONDURAS            30098
#define IDS_SPANISH_NICARAGUA           30099
#define IDS_SPANISH_PUERTO_RICO         30100
#define IDS_SWEDISH                     30101
#define IDS_SWEDISH_FINLAND             30102
#define IDS_THAI                        30103
#define IDS_TURKISH                     30104
#define IDS_UKRANIAN                    30105
#define IDS_VIETNAMESE                  30106
#define ID_L2R                          32771
#define ID_R2L                          32772
#define ID_UNDO                         32773
#define ID_OPTIONS_SHOWIDENTICAL        32774
#define ID_OPTIONS_SHOWDIFFERENT        32775
#define ID_OPTIONS_SHOWUNIQUE           32776
#define ID_POPUP_COPYTOOTHERSIDE        32777
#define ID_POPUP_COPYFROMOTHERSIDE      32778
#define ID_PREVDIFF                     32779
#define ID_POPUP_SAVE                   32780
#define ID_NEXTDIFF                     32781
#define ID_OPTIONS_BACKUPORIGINALFILE   32782
#define ID_OPTIONS_SCROLLTOFIRSTDIFFERENCE 32784
#define ID_POPUP_EDITFILE               32787
#define ID_OPTIONS_IGNOREWHITESPACE     32788
#define ID_HIDE_BACKUP_FILES            32789
#define ID_HELP_GNULICENSE              32790
#define ID_USEVSS                       32791
#define ID_PROPERTIES                   32792
#define ID_ALL_LEFT                     32793
#define ID_ALL_RIGHT                    32794
#define ID_VIEW_SELECTFONT              32795
#define ID_VIEW_USEDEFAULTFONT          32796
#define ID_POPUP_COPYALLDIFFSTOOTHERSIDE 32797
#define ID_POPUP_COPYALLDIFFSFROMOTHERSIDE 32798
#define ID_DIR_COPY_FILE_TO_LEFT        32799
#define ID_DIR_COPY_FILE_TO_RIGHT       32800
#define ID_VIEW_LANGUAGE                32801
#define ID_HELP_CONTENTS                32802
#define ID_FIRSTDIFF                    32803
#define ID_CURDIFF                      32804
#define ID_LASTDIFF                     32805
#define ID_DIFFNUM                      32806
#define ID_DIR_DEL_LEFT                 32807
#define ID_DIR_DEL_RIGHT                32808
#define ID_DIFFSTATUS                   32809
#define ID_OPTIONS_SHOWUNIQUELEFT       32810
#define ID_OPTIONS_SHOWUNIQUERIGHT      32811
#define ID_DIR_DEL_BOTH                 32812
#define ID_DIR_OPEN_LEFT                32813
#define ID_DIR_OPEN_LEFT_WITH           32814
#define ID_DIR_OPEN_RIGHT               32815
#define ID_DIR_OPEN_RIGHT_WITH          32816

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        113
#define _APS_NEXT_COMMAND_VALUE         32817
#define _APS_NEXT_CONTROL_VALUE         1036
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
