//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Merge.rc
//
#define IDR_MAINFRAME                   100
#define IDB_TOOLBAR_ENABLED8BIT         100
#define IDR_MERGEPROJECT                101
#define IDR_POPUP_EDITOR_HEADERBAR      102
#define IDR_POPUP_PLUGINS_SETTINGS      103
#define IDR_POPUP_MERGEVIEW             104
#define IDR_POPUP_DIRVIEW               105
#define IDR_POPUP_LOCATIONBAR           106
#define IDR_MERGEDOCTYPE                109
#define IDR_DIRDOCTYPE                  110
#define IDR_POPUP_MERGEVIEWHEADER       111
#define IDR_POPUP_WEBPAGEDIFFVIEW       112
#define IDR_POPUP_DIFF_OPTIONS          113
#define IDR_POPUP_IMGMERGEVIEW          114
#define IDR_POPUP_PROJECT               115
#define IDR_POPUP_MERGEEDITFRAME_STATUSBAR_EOL 116
#define IDR_POPUP_NEW                   117
#define IDR_POPUP_OPEN                  118
#define IDR_POPUP_COMPARE               119
#define IDR_POPUP_SAVE                  120
#define IDR_POPUP_IMG_CTXT              121
#define IDR_POPUP_PROJECT_DIFF_OPTIONS  122
#define IDR_POPUP_WEBPAGE_COMPARE       123
#define IDD_ABOUTBOX                    200
#define IDD_OPEN                        202
#define IDD_SAVECLOSING                 203
#define IDD_EDITOR_HEADERBAR            210
#define IDD_GENERATE_PATCH              211
#define IDD_DIRCOLS                     212
#define IDD_DIRADDITIONALPROPS          213
#define IDD_DIRCOMP_PROGRESS            214
#define IDD_WMGOTO                      215
#define IDD_MESSAGE_BOX                 219
#define IDD_PREFERENCES                 224
#define IDD_DIRCMP_REPORT               226
#define IDD_COMPARE_STATISTICS          229
#define IDD_COMPARE_STATISTICS3         230
#define IDD_LOAD_SAVE_CODEPAGE          231
#define IDD_CONFIRM_COPY                236
#define IDD_PLUGINS_LIST                237
#define IDD_PLUGINS_SELECTPLUGIN        238
#define IDD_DIR_FILTER                  240
#define IDD_ENCODINGERROR               241
#define IDD_SELECT_FILES_OR_FOLDERS     247
#define IDD_DIALOG_WINDOWSMANAGER       251
#define IDD_OPEN_TABLE                  252
#define IDD_WEB_SIZE                    254
#define IDD_FILTERS_FILEFILTERS         255
#define IDD_FILTERS_LINEFILTERS         256
#define IDD_FILTERS_SUBSTITUTIONFILTERS 257
#define IDD_FILTERS_FILEFILTERS_SHARED  258
#define IDD_FILTERS_FILEFILTERS_TEST    259
#define IDD_PROPPAGE_ARCHIVE            260
#define IDD_PROPPAGE_BACKUPS            261
#define IDD_PROPPAGE_CODEPAGE           262
#define IDD_PROPPAGE_COLOR_SCHEMES      263
#define IDD_PROPPAGE_COLORS_DIR         264
#define IDD_PROPPAGE_COLORS_MARKER      265
#define IDD_PROPPAGE_COLORS_SYNTAX      266
#define IDD_PROPPAGE_COLORS_TEXT        267
#define IDD_PROPPAGE_COLORS_WINMERGE    268
#define IDD_PROPPAGE_COMPARE            269
#define IDD_PROPPAGE_COMPARE_BINARY     270
#define IDD_PROPPAGE_COMPARE_FOLDER     271
#define IDD_PROPPAGE_COMPARE_IMAGE      272
#define IDD_PROPPAGE_COMPARE_TABLE      273
#define IDD_PROPPAGE_COMPARE_WEBPAGE    274
#define IDD_PROPPAGE_EDITOR             275
#define IDD_PROPPAGE_EDITOR_SYNTAX      276
#define IDD_PROPPAGE_GENERAL            277
#define IDD_PROPPAGE_SHELL              278
#define IDD_PROPPAGE_SYSTEM             279
#define IDD_PROPPAGE_MESSAGEBOXES       280
#define IDD_PROPPAGE_PROJECT            281
#define IDD_EDIT_FIND                   282
#define IDD_EDIT_MARKER                 283
#define IDD_EDIT_REPLACE                284
#define IDD_WEBPAGEDIFF_BAR             285
#define IDI_ROTATE2                     302
#define IDR_LOGO                        307
#define IDR_SPLASH                      308
#define IDR_MARGIN_ICONS_PNG            310
#define IDB_EDIT_COPY                   316
#define IDB_EDIT_CUT                    317
#define IDB_EDIT_PASTE                  318
#define IDB_EDIT_SEARCH                 319
#define IDB_WINDOW_CASCADE              320
#define IDB_WINDOW_HORIZONTAL           321
#define IDB_WINDOW_VERTICAL             322
#define IDB_WINDOW_CLOSE                323
#define IDB_WINDOW_CHANGEPANE           324
#define IDB_EDIT_GOTO                   325
#define IDB_EDIT_REPLACE                326
#define IDB_VIEW_SELECTFONT             328
#define IDB_FILE_EXIT                   329
#define IDB_HELP_CONTENTS               330
#define IDB_EDIT_SELECTALL              333
#define IDB_TOOLS_FILTERS               334
#define IDB_TOOLS_COLUMNS               335
#define IDB_MERGE_DELETE                336
#define IDB_FILE_PRINT                  337
#define IDB_TOOLS_GENERATEPATCH         338
#define IDB_TOOLS_GENERATEREPORT        339
#define IDR_MARGIN_ICONS                340
#define IDR_MARGIN_CURSOR               341
#define IDB_EDIT_TOGGLE_BOOKMARK        342
#define IDB_EDIT_GOTO_NEXT_BOOKMARK     343
#define IDB_EDIT_GOTO_PREV_BOOKMARK     344
#define IDB_EDIT_CLEAR_ALL_BOOKMARKS    345
#define IDB_LEFT                        347
#define IDB_MIDDLE                      348
#define IDB_RIGHT                       349
#define IDB_BOTH                        350
#define IDB_ALL                         351
#define IDB_COPY_LEFT_TO_RIGHT          352
#define IDB_COPY_LEFT_TO_MIDDLE         353
#define IDB_COPY_RIGHT_TO_LEFT          354
#define IDB_COPY_RIGHT_TO_MIDDLE        355
#define IDB_COPY_MIDDLE_TO_LEFT         356
#define IDB_COPY_MIDDLE_TO_RIGHT        357
#define IDB_COPY_LEFT_TO_BROWSE         358
#define IDB_COPY_MIDDLE_TO_BROWSE       359
#define IDB_COPY_RIGHT_TO_BROWSE        360
#define IDB_MOVE_LEFT_TO_RIGHT          361
#define IDB_MOVE_LEFT_TO_MIDDLE         362
#define IDB_MOVE_RIGHT_TO_LEFT          363
#define IDB_MOVE_RIGHT_TO_MIDDLE        364
#define IDB_MOVE_MIDDLE_TO_LEFT         365
#define IDB_MOVE_MIDDLE_TO_RIGHT        366
#define IDB_MOVE_LEFT_TO_BROWSE         367
#define IDB_MOVE_MIDDLE_TO_BROWSE       368
#define IDB_MOVE_RIGHT_TO_BROWSE        369
#define IDB_TOOLBAR_ENABLED32           370
#define IDB_VIEW_ZOOMIN                 371
#define IDB_VIEW_ZOOMOUT                372
#define IDB_FILE_NEW3                   373
#define IDB_FILE_OPENCONFLICT           374
#define IDB_PLUGINS_LIST                375
#define IDB_MERGE_COMPARE               376
#define IDB_MERGE_COMPARE_LEFT1_LEFT2   377
#define IDB_MERGE_COMPARE_RIGHT1_RIGHT2 378
#define IDB_MERGE_COMPARE_LEFT1_RIGHT2  379
#define IDB_MERGE_COMPARE_LEFT2_RIGHT1  380
#define IDB_COPY_FROM_LEFT              381
#define IDB_COPY_FROM_RIGHT             382
#define IDB_TOOLBAR_ENABLED             383
#define IDB_FILE_NEW_TABLE              384
#define IDB_FILE_NEW_HEX                385
#define IDB_FILE_NEW_IMAGE              386
#define IDB_FILE_NEW_WEBPAGE            387
#define IDB_FILE_NEW3_TABLE             388
#define IDB_FILE_NEW3_HEX               389
#define IDB_FILE_NEW3_IMAGE             390
#define IDB_FILE_NEW3_WEBPAGE           391
#define IDB_COPY_SELECTED_LINES_FROM_LEFT 392
#define IDB_COPY_SELECTED_LINES_FROM_RIGHT 393
#define IDB_COPY_SELECTED_LINES_LEFT_TO_RIGHT 394
#define IDB_COPY_SELECTED_LINES_LEFT_TO_MIDDLE 395
#define IDB_COPY_SELECTED_LINES_MIDDLE_TO_LEFT 396
#define IDB_COPY_SELECTED_LINES_MIDDLE_TO_RIGHT 397
#define IDB_COPY_SELECTED_LINES_RIGHT_TO_MIDDLE 398
#define IDB_COPY_SELECTED_LINES_RIGHT_TO_LEFT 399
#define IDI_FOLDER                      500
#define IDI_LFOLDER                     501
#define IDI_MFOLDER                     502
#define IDI_RFOLDER                     503
#define IDI_FOLDERSKIP                  504
#define IDI_EQUALFILE                   505
#define IDI_NOTEQUALFILE                506
#define IDI_EQUALBINARY                 507
#define IDI_LFILE                       508
#define IDI_MFILE                       509
#define IDI_RFILE                       510
#define IDI_BINARYDIFF                  511
#define IDI_FILESKIP                    512
#define IDI_COMPARE_ERROR               513
#define IDI_FOLDERUP                    514
#define IDI_FOLDERUP_DISABLE            515
#define IDI_FILEFILTER                  517
#define IDI_LINEFILTER                  518
#define IDI_SUBSTITUTIONFILTER          519
#define IDI_COMPARE_ABORTED             520
#define IDI_MRFILE                      521
#define IDI_LRFILE                      522
#define IDI_LMFILE                      523
#define IDI_MRFOLDER                    524
#define IDI_LRFOLDER                    525
#define IDI_LMFOLDER                    526
#define IDI_EQUALFOLDER                 527
#define IDI_NOTEQUALFOLDER              528
#define IDI_EQUALTEXTFILE               529
#define IDI_NOTEQUALTEXTFILE            530
#define IDI_EQUALIMAGE                  531
#define IDI_NOTEQUALIMAGE               532
#define IDI_EQUALWEBPAGE                533
#define IDI_NOTEQUALWEBPAGE             534
#define IDI_TREE_STATE_COLLAPSED        535
#define IDI_TREE_STATE_EXPANDED         536
#define IDI_FILE                        537
#define IDC_PATH0_BUTTON                1001
#define IDC_PATH1_BUTTON                1002
#define IDC_PATH2_BUTTON                1003
#define IDC_PATH0_COMBO                 1004
#define IDC_PATH1_COMBO                 1005
#define IDC_PATH2_COMBO                 1006
#define IDC_EXT_COMBO                   1009
#define IDC_SCROLL_CHECK                1012
#define IDC_SCROLL_TO_FIRST_INLINE_DIFF_CHECK 1013
#define IDC_RECURS_CHECK                1015
#define IDC_VERSION                     1016
#define IDC_IGNBLANKS_CHECK             1017
#define IDC_TAB_EDIT                    1018
#define IDC_WWW                         1019
#define IDC_IGNCASE_CHECK               1020
#define IDC_COMPANY                     1021
#define IDC_GNU_ASCII                   1022
#define IDC_HILITE_CHECK                1025
#define IDC_IGNOREREGEXP                1026
#define IDC_ALL_WHITE                   1027
#define IDC_WHITE_CHANGE                1028
#define IDC_WHITESPACE                  1029
#define IDC_IGNORED_SUSBSTITUTIONS_ENABLED 1030
#define IDC_EOL_SENSITIVE               1032
#define IDC_CP_SENSITIVE                1033
#define IDC_IGNORE_NUMBERS              1034
#define IDC_DIFFERENCE_COLOR            1035
#define IDC_SEL_DIFFERENCE_COLOR        1037
#define IDC_PROP_INSERT_TABS            1038
#define IDC_PROP_INSERT_SPACES          1040
#define IDC_LANGUAGE_LIST               1041
#define IDC_AUTOMRESCAN_CHECK           1042
#define IDC_DIFFERENCE_USE_TEXT_COLOR   1043
#define IDC_DIFFERENCE_TEXT_COLOR       1044
#define IDC_DIFFERENCE_DELETED_COLOR    1045
#define IDC_SEL_DIFFERENCE_DELETED_COLOR 1046
#define IDC_SEL_DIFFERENCE_USE_TEXT_COLOR 1047
#define IDC_SEL_DIFFERENCE_TEXT_COLOR   1048
#define IDC_EXPLORER_CONTEXT            1049
#define IDC_EXPLORER_ADVANCED           1050
#define IDC_EXPLORER_COMPARE_AS         1051
#define IDC_TRIVIAL_DIFF_USE_TEXT_COLOR 1052
#define IDC_TRIVIAL_DIFF_TEXT_COLOR     1053
#define IDC_MOVEDBLOCK_COLOR            1054
#define IDC_MOVEDBLOCK_USE_TEXT_COLOR   1055
#define IDC_MOVEDBLOCK_TEXT_COLOR       1056
#define IDC_MOVEDBLOCK_DELETED_COLOR    1057
#define IDC_SEL_MOVEDBLOCK_COLOR        1058
#define IDC_SEL_MOVEDBLOCK_USE_TEXT_COLOR 1059
#define IDC_SEL_MOVEDBLOCK_TEXT_COLOR   1060
#define IDC_SEL_MOVEDBLOCK_DELETED_COLOR 1061
#define IDC_UP                          1062
#define IDC_DOWN                        1063
#define IDC_MIXED_EOL                   1064
#define IDC_DIFF_FILE1                  1065
#define IDC_DIFF_FILE2                  1066
#define IDC_DIFF_FILERESULT             1067
#define IDC_DIFF_STYLE                  1068
#define IDC_DIFF_CONTEXT                1069
#define IDC_DIFF_BROWSE_FILE1           1075
#define IDC_DIFF_BROWSE_FILE2           1076
#define IDC_DIFF_BROWSE_RESULT          1077
#define IDC_DIFF_APPENDFILE             1078
#define IDC_DIFF_COPYCLIPBOARD          1079
#define IDC_TRIVIAL_DIFF_COLOR          1080
#define IDC_TRIVIAL_DIFF_DELETED_COLOR  1081
#define IDC_FILES_DIRS_GROUP0           1082
#define IDC_FILES_DIRS_GROUP1           1083
#define IDC_FILES_DIRS_GROUP2           1084
#define IDC_FILES_DIRS_GROUP3           1085
#define IDC_FILES_DIRS_GROUP4           1086
#define IDC_FILES_DIRS_GROUP5           1087
#define IDC_PLUGIN_NAME                 1088
#define IDC_PLUGIN_ALLOW_ALL            1089
#define IDC_PLUGIN_SUPPORTED_EXTENSIONS 1090
#define IDC_PLUGIN_DESCRIPTION          1091
#define IDC_PLUGIN_ARGUMENTS            1092
#define IDC_PLUGIN_PIPELINE             1094
#define IDC_PLUGIN_ADDPIPE              1095
#define IDC_PLUGIN_OPEN_IN_SAME_FRAME_TYPE 1096
#define IDC_UNPACKER_COMBO              1097
#define IDC_PREDIFFER_COMBO              1098
#define IDC_SELECT_UNPACKER             1099
#define IDC_SELECT_PREDIFFER            1100
#define IDC_EXT_EDITOR_BROWSE           1101
#define IDC_EXT_EDITOR_PATH             1102
#define IDC_DIFF_SWAPFILES              1103
#define IDC_DIFF_OPENTOEDITOR           1105
#define IDC_FILES_DIRS_GROUP3X          1106
#define IDC_FILES_DIRS_GROUP4X          1107
#define IDC_COMPARISON_STOP             1108
#define IDC_COMPARISON_PAUSE            1109
#define IDC_COMPARISON_CONTINUE         1110
#define IDC_DIFF_INCLCMDLINE            1111
#define IDC_WMGOTO_FILELEFT             1112
#define IDC_WMGOTO_FILEMIDDLE           1113
#define IDC_WMGOTO_FILERIGHT            1114
#define IDC_WMGOTO_TOLINE               1115
#define IDC_WMGOTO_TODIFF               1116
#define IDC_WMGOTO_PARAM                1117
#define IDC_OPEN_CONTRIBUTORS           1118
#define IDC_COMPAREMETHODCOMBO          1119
#define IDC_USE_RECYCLE_BIN             1120
#define IDC_COMPARE_DEFAULTS            1121
#define IDC_DIFF_DEFAULTS               1122
#define IDC_MOVED_BLOCKS                1123
#define IDC_RESET_ALL_MESSAGE_BOXES     1124
#define IDC_COLDLG_DEFAULTS             1126
#define IDC_COLDLG_ADDITIONAL_PROPERTIES 1127
#define IDC_OPEN_STATUS                 1128
#define IDC_FILTERFILE_EDITBTN          1129
#define IDC_FILTERFILE_LIST             1130
#define IDC_ESC_CLOSES_WINDOW           1131
#define IDC_STATIC_TITLE_PANE0          1133
#define IDC_STATIC_TITLE_PANE1          1134
#define IDC_STATIC_TITLE_PANE2          1135
#define IDC_SELECT_FILTER               1136
#define IDC_COLDLG_DESC                 1137
#define IDC_VERIFY_OPEN_PATHS           1138
#define IDC_DETECT_CODEPAGE             1139
#define IDC_SAVECLOSING_SAVELEFT        1140
#define IDC_SAVECLOSING_DISCARDLEFT     1141
#define IDC_SAVECLOSING_SAVEMIDDLE      1142
#define IDC_SAVECLOSING_DISCARDMIDDLE   1143
#define IDC_SAVECLOSING_SAVERIGHT       1144
#define IDC_SAVECLOSING_DISCARDRIGHT    1145
#define IDC_SAVECLOSING_RIGHTFILE       1146
#define IDC_SAVECLOSING_LEFTFILE        1147
#define IDC_SAVECLOSING_MIDDLEFILE      1148
#define IDC_SAVECLOSING_LEFTFRAME       1149
#define IDC_SAVECLOSING_MIDDLEFRAME     1150
#define IDC_SAVECLOSING_RIGHTFRAME      1151
#define IDC_CP_SYSTEM                   1152
#define IDC_CP_UI                       1153
#define IDC_CP_CUSTOM                   1154
#define IDC_CUSTOM_CP_NUMBER            1155
#define IDC_FILTERFILE_NEWBTN           1156
#define IDC_FILTERFILE_DELETEBTN        1157
#define IDC_WORDDIFF_COLOR              1158
#define IDC_SEL_WORDDIFF_COLOR          1159
#define IDC_WORDDIFF_USE_TEXT_COLOR     1160
#define IDC_WORDDIFF_TEXT_COLOR         1161
#define IDC_SEL_WORDDIFF_USE_TEXT_COLOR 1162
#define IDC_SEL_WORDDIFF_TEXT_COLOR     1163
#define IDC_SNP_COLOR                   1164
#define IDC_SNP_DELETED_COLOR           1165
#define IDC_SNP_USE_TEXT_COLOR          1166
#define IDC_SNP_TEXT_COLOR              1167
#define IDC_SEL_SNP_COLOR               1168
#define IDC_SEL_SNP_DELETED_COLOR       1169
#define IDC_SEL_SNP_USE_TEXT_COLOR      1170
#define IDC_SEL_SNP_TEXT_COLOR          1171
#define IDC_TREEOPT_PAGES               1172
#define IDC_TREEOPT_HOSTFRAME           1173
#define IDC_TREEOPT_HELP                1174
#define IDC_SINGLE_INSTANCE             1175
#define IDC_IGNORE_SMALLTIMEDIFF        1176
#define IDC_LINE_COLORING_GROUP         1177
#define IDC_VIEW_LINE_DIFFERENCES       1178
#define IDC_BREAK_TYPE                  1179
#define IDC_SCOLOR_KEYWORDS_BOLD        1180
#define IDC_SCOLOR_KEYWORDS             1181
#define IDC_SCOLOR_FUNCTIONS            1182
#define IDC_SCOLOR_COMMENTS             1183
#define IDC_SCOLOR_NUMBERS              1184
#define IDC_SCOLOR_OPERATORS            1185
#define IDC_SCOLOR_STRINGS              1186
#define IDC_SCOLOR_PREPROCESSOR         1188
#define IDC_SCOLOR_USER1                1189
#define IDC_SCOLOR_USER2                1190
#define IDC_SCOLOR_COMMENTS_BOLD        1191
#define IDC_SCOLOR_FUNCTIONS_BOLD       1192
#define IDC_SCOLOR_NUMBERS_BOLD         1193
#define IDC_SCOLOR_OPERATORS_BOLD       1194
#define IDC_SCOLOR_STRINGS_BOLD         1195
#define IDC_SCOLOR_PREPROCESSOR_BOLD    1196
#define IDC_SCOLOR_USER1_BOLD           1197
#define IDC_SCOLOR_USER2_BOLD           1198
#define IDC_SAVECLOSING_DISCARDALL      1199
#define IDC_PROGRESSCOMPARE             1200
#define IDC_ITEMSCOMPARED               1201
#define IDC_ITEMSTOTAL                  1202
#define IDC_REPORT_STYLECOMBO           1203
#define IDC_REPORT_BROWSEFILE           1204
#define IDC_REPORT_FILE                 1205
#define IDC_SHARED                      1206
#define IDC_PRIVATE                     1207
#define IDC_COMPARE_STOPFIRST           1208
#define IDC_ARCHIVE_DETECTTYPE          1209
#define IDC_ARCHIVE_ENABLE              1210
#define IDC_DETECT_CODEPAGE2            1211
#define IDC_DETECT_AUTODETECTTYPE       1212
#define IDC_STAT_IDENTICFOLDER          1213
#define IDC_STAT_IDENTICFILE            1214
#define IDC_STAT_IDENTICBINARY          1215
#define IDC_STAT_DIFFFOLDER             1216
#define IDC_STAT_DIFFFILE               1217
#define IDC_STAT_DIFFBINARY             1218
#define IDC_STAT_LUNIQFOLDER            1219
#define IDC_STAT_LUNIQFILE              1220
#define IDC_STAT_RUNIQFOLDER            1221
#define IDC_STAT_RUNIQFILE              1222
#define IDC_STAT_MUNIQFOLDER            1223
#define IDC_STAT_MUNIQFILE              1224
#define IDC_STAT_LMISSINGFOLDER         1225
#define IDC_STAT_LMISSINGFILE           1226
#define IDC_STAT_RMISSINGFOLDER         1227
#define IDC_STAT_RMISSINGFILE           1228
#define IDC_STAT_MMISSINGFOLDER         1229
#define IDC_STAT_MMISSINGFILE           1230
#define IDC_STAT_TOTALFOLDER            1231
#define IDC_STAT_TOTALFILE              1232
#define IDC_TREEOPT_IMPORT              1233
#define IDC_TREEOPT_EXPORT              1234
#define IDC_STAT_ILUNIQFOLDER           1235
#define IDC_STAT_IRUNIQFOLDER           1236
#define IDC_STAT_IMUNIQFOLDER           1237
#define IDC_STAT_ILMISSINGFOLDER        1238
#define IDC_STAT_IRMISSINGFOLDER        1239
#define IDC_STAT_IMMISSINGFOLDER        1240
#define IDC_STAT_IIDENTICFOLDER         1241
#define IDC_STAT_INOTEQUAL              1242
#define IDC_STAT_INOTEQUALFOLDER        1243
#define IDC_STAT_IDIFFBINFILE           1244
#define IDC_STAT_ILUNIQFILE             1245
#define IDC_STAT_IRUNIQFILE             1246
#define IDC_STAT_IMUNIQFILE             1247
#define IDC_STAT_ILMISSINGFILE          1248
#define IDC_STAT_IRMISSINGFILE          1249
#define IDC_STAT_IMMISSINGFILE          1250
#define IDC_STAT_IEQUALFILE             1251
#define IDC_STAT_IEQUALBINFILE          1252
#define IDC_EDITOR_CHARLEVEL            1253
#define IDC_EDITOR_WORDLEVEL            1254
#define IDC_AFFECTS_GROUP               1255
#define IDC_AFFECTS_LEFT_BTN            1256
#define IDC_AFFECTS_MIDDLE_BTN          1257
#define IDC_AFFECTS_RIGHT_BTN           1258
#define IDC_LOAD_FILES_LABEL            1259
#define IDC_LOAD_CODEPAGE_TEXTBOX       1260
#define IDC_LOAD_SAVE_SAME_CODEPAGE     1261
#define IDC_SAVE_FILES_LABEL            1262
#define IDC_SAVE_CODEPAGE_TEXTBOX       1264
#define IDC_LOADING_GROUP               1265
#define IDC_LEFT_FILES_LABEL            1266
#define IDC_MIDDLE_FILES_LABEL          1267
#define IDC_RIGHT_FILES_LABEL           1268
#define IDC_FILTERFILE_TEST_BTN         1269
#define IDC_HEADER                      1270
#define IDC_PROMPT_LABEL                1271
#define IDC_TEST_BTN                    1272
#define IDC_TEST_TEXT                   1273
#define IDC_RESULTS                     1274
#define IDC_IS_DIRECTORY                1275
#define IDC_HEADER_FILTER_NAME          1276
#define IDC_DEFAULT_STANDARD_COLORS     1277
#define IDC_WHITESPACE_COLOR_LABEL      1279
#define IDC_TEXT_COLOR_LABEL            1280
#define IDC_SELECTION_COLOR_LABEL       1281
#define IDC_TEXT_COLUMN_LABEL           1282
#define IDC_BACKGROUND_COLUMN_LABEL     1283
#define IDC_WHITESPACE_BKGD_COLOR       1284
#define IDC_REGULAR_BKGD_COLOR          1285
#define IDC_SELECTION_BKGD_COLOR        1286
#define IDC_SELECTION_TEXT_COLOR        1287
#define IDC_REGULAR_TEXT_COLOR          1288
#define IDC_AUTO_COMPLETE_SOURCE        1289
#define IDC_FILTER_USER_BROWSE          1297
#define IDC_FILTER_USER_PATH            1298
#define IDC_FILTERCOMMENTS_CHECK        1299
#define IDC_FINDDLG_DONTWRAP            1302
#define IDC_REPORT_COPYCLIPBOARD        1303
#define IDC_FILTERFILE_INSTALL          1304
#define IDC_MATCH_SIMILAR_LINES         1305
#define IDC_BACKUP_FILECMP              1306
#define IDC_BACKUP_FOLDERCMP            1307
#define IDC_BACKUP_ORIGFOLD             1308
#define IDC_BACKUP_GLOBALFOLD           1309
#define IDC_BACKUP_BROWSE               1310
#define IDC_BACKUP_FOLDER               1311
#define IDC_BACKUP_APPEND_BAK           1312
#define IDC_BACKUP_APPEND_TIME          1313
#define IDC_FLDCONFIRM_TO_PATH          1314
#define IDC_FLDCONFIRM_QUERY            1315
#define IDC_FLDCONFIRM_FROM_TEXT        1316
#define IDC_FLDCONFIRM_TO_TEXT          1317
#define IDC_FLDCONFIRM_FROM_PATH        1318
#define IDC_FLDCONFIRM_ICON             1319
#define IDC_LFILTER_LIST                1320
#define IDC_LFILTER_ADDBTN              1321
#define IDC_LFILTER_EDITBTN             1322
#define IDC_LFILTER_REMOVEBTN           1323
#define IDC_SUBSTITUTION_FILTERS        1324
#define IDC_SAVE_CODEPAGE_BOM           1325
#define IDC_ASK_MULTIWINDOW_CLOSE       1326
#define IDC_COLDLG_LIST                 1327
#define IDC_PRESERVE_FILETIME           1328
#define IDC_TMPFOLDER_SYSTEM            1329
#define IDC_TMPFOLDER_BROWSE            1330
#define IDC_TMPFOLDER_NAME              1331
#define IDC_PLUGINS_ENABLE              1332
#define IDC_PLUGINSLIST_LIST            1333
#define IDC_STARTUP_FOLDER_SELECT       1334
#define IDC_BREAK_CHARS                 1335
#define IDC_WORDDIFF_DELETED_COLOR      1336
#define IDC_SEL_WORDDIFF_DELETED_COLOR  1337
#define IDC_COMPARE_WALKSUBDIRS         1339
#define IDC_COMPARE_QUICKC_LIMIT        1340
#define IDC_REPORT_INCLUDEFILECMPREPORT 1341
#define IDC_COMPARE_THREAD_COUNT        1342
#define IDC_SWAP01_BUTTON               1343
#define IDC_SWAP12_BUTTON               1344
#define IDC_SWAP02_BUTTON               1345
#define IDC_FINDDLG_DONTCLOSE           1347
#define IDC_PATH_COMPARING              1348
#define IDC_REGISTER_SHELLEXTENSION     1349
#define IDC_UNREGISTER_SHELLEXTENSION   1350
#define IDC_MARGIN_COLOR_LABEL          1351
#define IDC_MARGIN_BKGD_COLOR           1352
#define IDC_COMPARE_BINARYC_LIMIT       1353
#define IDC_REGISTER_SHELLEXTENSION_PERUSER 1354
#define IDC_UNREGISTER_SHELLEXTENSION_PERUSER 1355
#define IDC_DIR_ITEM_DIFF_COLOR         1356
#define IDC_DIR_ITEM_DIFF_TEXT_COLOR    1357
#define IDC_DIR_ITEM_NOTEXISTALL_COLOR  1358
#define IDC_DIR_ITEM_NOTEXISTALL_TEXT_COLOR 1359
#define IDC_DIR_ITEM_FILTERED_COLOR     1360
#define IDC_DIR_ITEM_FILTERED_TEXT_COLOR 1361
#define IDC_DIR_ITEM_EQUAL_COLOR        1362
#define IDC_DIR_ITEM_EQUAL_TEXT_COLOR   1363
#define IDC_USE_DIR_COMPARE_COLORS      1364
#define IDC_PLUGIN_FILEFILTERS          1365
#define IDC_PLUGIN_DEFAULTS             1366
#define IDC_PLUGIN_AUTOMATIC            1367
#define IDC_RENDERING_MODE              1368
#define IDC_REGISTER_WINMERGECONTEXTMENU 1369
#define IDC_UNREGISTER_WINMERGECONTEXTMENU 1370
#define IDC_RESET                       1378
#define IDC_LEFT1                       1379
#define IDC_MIDDLE1                     1380
#define IDC_RIGHT1                      1381
#define IDC_LEFT2                       1382
#define IDC_MIDDLE2                     1383
#define IDC_RIGHT2                      1384
#define IDC_LEFT3                       1385
#define IDC_MIDDLE3                     1386
#define IDC_RIGHT3                      1387
#define IDC_FIRST                       1388
#define IDC_SECOND                      1389
#define IDC_THIRD                       1390
#define IDC_COLOR_SCHEMES               1391
#define IDC_DIR_MARGIN_COLOR            1392
#define IDC_SYNTAX_LIST                 1393
#define IDC_COMPAREIMAGE_PATTERNS       1394
#define IDC_PLUGIN_SETTINGS             1395
#define IDC_COMPAREIMAGE_OCR_RESULT_TYPE 1396
#define IDC_COMPAREBINARY_PATTERNS      1397
#define IDC_COMPAREBINARY_VIEWSETTINGS  1398
#define IDC_COMPAREBINARY_BINARYMODE    1399
#define IDC_COMPAREBINARY_CHARACTERSET  1400
#define IDC_ENABLE_IMGCMP_IN_DIRCMP     1401
#define IDC_COMPARETABLE_CSV            1402
#define IDC_COMPARETABLE_TSV            1403
#define IDC_COMPARETABLE_DSV            1404
#define IDC_COMPARETABLE_CSV_PATTERNS   1405
#define IDC_COMPARETABLE_TSV_PATTERNS   1406
#define IDC_COMPARETABLE_DSV_PATTERNS   1407
#define IDC_COMPARETABLE_CSV_DELIM_CHAR 1408
#define IDC_COMPARETABLE_DSV_DELIM_CHAR 1409
#define IDC_COMPARETABLE_ALLOWNEWLINE   1410
#define IDC_COMPARETABLE_QUOTE_CHAR     1411
#define IDC_OPTIONS                     1412
#define IDC_SWAP01_STATIC               1413
#define IDC_SWAP12_STATIC               1414
#define IDC_SWAP02_STATIC               1415
#define IDC_DIFF_ALGORITHM              1416
#define IDC_INDENT_HEURISTIC            1417
#define IDC_LIST_FILE                   1418
#define IDC_FLDCONFIRM_DONTASKAGAIN     1419
#define IDC_COMPLETELY_BLANK_OUT_IGNORED_DIFFERENCES 1420
#define IDC_LFILTER_CLEARBTN            1421
#define IDC_MESSAGEBOX_LIST             1422
#define IDC_PROJECT_LIST                1423
#define IDC_DIFF_IGNORENUMBERS          1424
#define IDC_COMPAREWEBPAGE_USERDATAFOLDER_PERPANE 1425
#define IDC_COMPAREWEBPAGE_USERDATAFOLDER_TYPE 1426
#define IDC_COMPAREWEBPAGE_URLPATTERNTOINCLUDE 1427
#define IDC_COMPAREWEBPAGE_URLPATTERNTOEXCLUDE 1428
#define IDC_JUMP_LIST                   1429
#define IDC_CLEAR_ALL_RECENT_ITEMS      1430
#define IDC_EXPAND_SUBDIRS              1600
#define IDC_FILEENCODING                1601
#define IDC_PLUGIN                      1602
#define IDC_HEXVIEW                     1603
#define IDC_IGNORE_REPARSEPOINTS        1604
#define IDC_CLOSE_WITH_OK               1605
#define IDC_PATH0_READONLY              1606
#define IDC_PATH1_READONLY              1607
#define IDC_PATH2_READONLY              1608
#define IDC_AUTO_RELOAD_MODIFIED_FILES            1609
#define IDC_MARKER0_COLOR_LABEL         1611
#define IDC_MARKER1_COLOR_LABEL         1612
#define IDC_MARKER2_COLOR_LABEL         1613
#define IDC_MARKER3_COLOR_LABEL         1614
#define IDC_MARKER0_BKGD_COLOR          1615
#define IDC_MARKER1_BKGD_COLOR          1616
#define IDC_MARKER2_BKGD_COLOR          1617
#define IDC_MARKER3_BKGD_COLOR          1618
#define IDC_PROPS_TREEVIEW              1619
#define IDC_PROPS_ADD                   1620
#define IDC_PROPS_DEL                   1621
#define IDC_PROPS_DELALL                1622
#define IDC_PROPS_LISTVIEW              1623
#define IDC_FITTOWINDOW                 1624
#define IDC_WIDTH                       1625
#define IDC_HEIGHT                      1626
#define IDC_ZOOM                        1627
#define IDC_USERAGENT                   1628
#define IDC_COMPARE                     1630
#define IDC_SHOWDIFFERENCES             1631
#define IDC_EDIT_WHOLE_WORD             8603
#define IDC_EDIT_MATCH_CASE             8604
#define IDC_EDIT_FINDTEXT               8605
#define IDC_EDIT_REGEXP                 8606
#define IDC_EDIT_REPLACE                8607
#define IDC_EDIT_REPLACE_ALL            8608
#define IDC_EDIT_REPLACE_WITH           8609
#define IDC_EDIT_SKIP                   8610
#define IDC_EDIT_SCOPE_SELECTION        8613
#define IDC_EDIT_SCOPE_WHOLE_FILE       8614
#define IDC_EDIT_SCOPE_DONT_WRAP        8615
#define IDC_EDIT_FINDPREV               8616
#define IDC_EDIT_MARKERS_ENABLED        8819
#define IDC_EDIT_MARKER_LIST            8820
#define IDC_EDIT_MARKER_BGCOLORIDX      8821
#define IDC_EDIT_MARKER_NEW             8822
#define IDC_EDIT_MARKER_DELETE          8823
#define ID_DIFF_OPTIONS_WHITESPACE_COMPARE 16423
#define ID_DIFF_OPTIONS_WHITESPACE_IGNORE 16424
#define ID_DIFF_OPTIONS_WHITESPACE_IGNOREALL 16425
#define ID_DIFF_OPTIONS_IGNORE_BLANKLINES 16426
#define ID_DIFF_OPTIONS_IGNORE_CASE     16427
#define ID_DIFF_OPTIONS_IGNORE_EOL      16428
#define ID_DIFF_OPTIONS_IGNORE_CODEPAGE 16429
#define ID_DIFF_OPTIONS_IGNORE_COMMENTS 16430
#define ID_DIFF_OPTIONS_INCLUDE_SUBFOLDERS 16431
#define ID_DIFF_OPTIONS_COMPMETHOD_FULL_CONTENTS 16432
#define ID_DIFF_OPTIONS_COMPMETHOD_QUICK_CONTENTS 16433
#define ID_DIFF_OPTIONS_COMPMETHOD_BINARY_CONTENTS 16434
#define ID_DIFF_OPTIONS_COMPMETHOD_MODDATE 16435
#define ID_DIFF_OPTIONS_COMPMETHOD_DATESIZE 16436
#define ID_DIFF_OPTIONS_COMPMETHOD_SIZE 16437
#define ID_DIR_COPY_LEFT_TO_RIGHT       17600
#define ID_DIR_COPY_LEFT_TO_MIDDLE      17601
#define ID_DIR_COPY_LEFT_TO_BROWSE      17602
#define ID_DIR_COPY_MIDDLE_TO_LEFT      17603
#define ID_DIR_COPY_MIDDLE_TO_RIGHT     17604
#define ID_DIR_COPY_MIDDLE_TO_BROWSE    17605
#define ID_DIR_COPY_RIGHT_TO_LEFT       17606
#define ID_DIR_COPY_RIGHT_TO_MIDDLE     17607
#define ID_DIR_COPY_RIGHT_TO_BROWSE     17608
#define ID_DIR_COPY_LEFT_TO_CLIPBOARD   17609
#define ID_DIR_COPY_MIDDLE_TO_CLIPBOARD 17610
#define ID_DIR_COPY_RIGHT_TO_CLIPBOARD  17611
#define ID_DIR_COPY_BOTH_TO_CLIPBOARD   17612
#define ID_DIR_COPY_ALL_TO_CLIPBOARD    17613
#define ID_DIR_COPY_ALL_DISP_COLUMNS    17614
#define ID_DIR_DEL_LEFT                 17615
#define ID_DIR_DEL_MIDDLE               17616
#define ID_DIR_DEL_RIGHT                17617
#define ID_DIR_DEL_BOTH                 17618
#define ID_DIR_DEL_ALL                  17619
#define ID_DIR_OPEN_LEFT                17701
#define ID_DIR_OPEN_LEFT_WITHEDITOR     17702
#define ID_DIR_OPEN_LEFT_WITH           17703
#define ID_DIR_OPEN_LEFT_PARENT_FOLDER  17704
#define ID_DIR_OPEN_MIDDLE              17705
#define ID_DIR_OPEN_MIDDLE_WITHEDITOR   17706
#define ID_DIR_OPEN_MIDDLE_WITH         17707
#define ID_DIR_OPEN_MIDDLE_PARENT_FOLDER 17708
#define ID_DIR_OPEN_RIGHT               17709
#define ID_DIR_OPEN_RIGHT_WITHEDITOR    17710
#define ID_DIR_OPEN_RIGHT_WITH          17711
#define ID_DIR_OPEN_RIGHT_PARENT_FOLDER 17712
#define ID_DIR_COPY_FILENAMES           17713
#define ID_DIR_COPY_PATHNAMES_LEFT      17714
#define ID_DIR_COPY_PATHNAMES_MIDDLE    17715
#define ID_DIR_COPY_PATHNAMES_RIGHT     17716
#define ID_DIR_COPY_PATHNAMES_BOTH      17717
#define ID_DIR_COPY_PATHNAMES_ALL       17718
#define ID_EDITOR_COPY_PATH             18182
#define ID_EDITOR_COPY_FILENAME         18183
#define ID_EDITOR_COPY                  18184
#define ID_EDITOR_EDIT_CAPTION          18185
#define ID_EDITOR_SELECT_FILE           18186
#define ID_FILE_NEW3                    32767
#define ID_FILE_SAVE_LEFT               32768
#define ID_FILE_SAVE_MIDDLE             32769
#define ID_FILE_SAVE_RIGHT              32770
#define ID_FILE_SAVEAS_LEFT             32771
#define ID_FILE_SAVEAS_MIDDLE           32772
#define ID_FILE_SAVEAS_RIGHT            32773
#define ID_FILE_LEFT_READONLY           32774
#define ID_FILE_MIDDLE_READONLY         32775
#define ID_FILE_RIGHT_READONLY          32776
#define ID_EOL_TO_DOS                   32777
#define ID_EOL_TO_UNIX                  32778
#define ID_EOL_TO_MAC                   32779
#define ID_FILE_MERGINGMODE             32780
#define ID_SELECTPREVLINEDIFF           32783
#define ID_SELECTLINEDIFF               32784
#define ID_EDIT_WMGOTO                  32785
#define ID_OPTIONS                      32786
#define ID_REFRESH                      32787
#define ID_EDIT_COPY_LINENUMBERS        32788
#define ID_RESCAN                       32789
#define ID_GOTO_MOVED_LINE_LM           32790
#define ID_GOTO_MOVED_LINE_MR           32791
#define ID_OPTIONS_SHOWIDENTICAL        32800
#define ID_OPTIONS_SHOWDIFFERENT        32801
#define ID_OPTIONS_SHOWUNIQUELEFT       32802
#define ID_OPTIONS_SHOWUNIQUEMIDDLE     32803
#define ID_OPTIONS_SHOWUNIQUERIGHT      32804
#define ID_OPTIONS_SHOWBINARIES         32805
#define ID_OPTIONS_SHOWSKIPPED          32806
#define ID_OPTIONS_SHOWDIFFERENTLEFTONLY 32807
#define ID_OPTIONS_SHOWDIFFERENTMIDDLEONLY 32808
#define ID_OPTIONS_SHOWDIFFERENTRIGHTONLY 32809
#define ID_OPTIONS_SHOWMISSINGLEFTONLY  32810
#define ID_OPTIONS_SHOWMISSINGMIDDLEONLY 32811
#define ID_OPTIONS_SHOWMISSINGRIGHTONLY 32812
#define ID_VIEW_EOL                     32815
#define ID_VIEW_SELECTFONT              32816
#define ID_VIEW_USEDEFAULTFONT          32817
#define ID_VIEW_WHITESPACE              32818
#define ID_VIEW_DETAIL_BAR              32819
#define ID_VIEW_LOCATION_BAR            32820
#define ID_VIEW_DIR_STATISTICS          32821
#define ID_VIEW_LINEDIFFS               32823
#define ID_VIEW_LINENUMBERS             32825
#define ID_VIEW_TAB_BAR                 32826
#define ID_VIEW_TREEMODE                32827
#define ID_VIEW_EXPAND_ALLSUBDIRS       32828
#define ID_VIEW_COLLAPSE_ALLSUBDIRS     32829
#define ID_PREVDIFF                     32832
#define ID_NEXTDIFF                     32833
#define ID_PREVCONFLICT                 32834
#define ID_NEXTCONFLICT                 32835
#define ID_PREVDIFFLM                   32836
#define ID_NEXTDIFFLM                   32837
#define ID_PREVDIFFLR                   32838
#define ID_NEXTDIFFLR                   32839
#define ID_PREVDIFFMR                   32840
#define ID_NEXTDIFFMR                   32841
#define ID_PREVDIFFLO                   32842
#define ID_NEXTDIFFLO                   32845
#define ID_PREVDIFFMO                   32846
#define ID_NEXTDIFFMO                   32847
#define ID_PREVDIFFRO                   32848
#define ID_NEXTDIFFRO                   32849
#define ID_FIRSTDIFF                    32850
#define ID_CURDIFF                      32851
#define ID_LASTDIFF                     32852
#define ID_L2R                          32853
#define ID_R2L                          32854
#define ID_L2RNEXT                      32855
#define ID_R2LNEXT                      32856
#define ID_ALL_RIGHT                    32857
#define ID_ALL_LEFT                     32858
#define ID_AUTO_MERGE                   32859
#define ID_MERGE_DELETE                 32860
#define ID_TOOLS_CUSTOMIZECOLUMNS       32864
#define ID_TOOLS_GENERATEPATCH          32865
#define ID_TOOLS_FILTERS                32866
#define ID_TOOLS_GENERATEREPORT         32868
#define ID_MERGE_COMPARE                32869
#define ID_MERGE_COMPARE_IN_NEW_WINDOW  32870
#define ID_MERGE_COMPARE_TEXT           32871
#define ID_MERGE_COMPARE_TABLE          32872
#define ID_MERGE_COMPARE_HEX            32873
#define ID_MERGE_COMPARE_IMAGE          32874
#define ID_MERGE_COMPARE_WEBPAGE        32875
#define ID_MERGE_COMPARE_LEFT1_LEFT2    32876
#define ID_MERGE_COMPARE_RIGHT1_RIGHT2  32877
#define ID_MERGE_COMPARE_LEFT1_RIGHT2   32878
#define ID_MERGE_COMPARE_LEFT2_RIGHT1   32879
#define ID_UNPACK_MANUAL                32880
#define ID_UNPACK_AUTO                  32881
#define ID_OPEN_WITH_UNPACKER           32882
#define ID_NO_PREDIFFER                 32883
#define ID_SUGGESTED_PLUGINS            32884
#define ID_NOT_SUGGESTED_PLUGINS        32885
#define ID_RELOAD_PLUGINS               32886
#define ID_NO_UNPACKER                  32887
#define ID_APPLY_PREDIFFER              32888
#define ID_TRANSFORM_WITH_SCRIPT        32889
#define ID_WINDOW_CLOSEALL              32897
#define ID_HELP_CONTENTS                32912
#define ID_HELP_GETCONFIG               32913
#define ID_HELP_GNULICENSE              32914
#define ID_PREDIFFER_SETTINGS_NONE      32920
#define ID_PREDIFFER_SETTINGS_AUTO      32921
#define ID_PREDIFFER_SETTINGS_SELECT    32922
#define ID_UNPACKER_SETTINGS_NONE       32923
#define ID_UNPACKER_SETTINGS_AUTO       32924
#define ID_UNPACKER_SETTINGS_SELECT     32925
#define ID_NO_EDIT_SCRIPTS              32931
#define ID_FILE_OPEN_REGISTERED         32944
#define ID_FILE_OPEN_WITHEDITOR         32945
#define ID_FILE_OPEN_WITH               32946
#define ID_FILE_OPEN_PARENT_FOLDER      32947
#define ID_STATUS_MERGINGMODE           32960
#define ID_STATUS_DIFFNUM               32961
#define ID_STATUS_RIGHTDIR_RO           32962
#define ID_STATUS_LEFTDIR_RO            32963
#define ID_STATUS_MIDDLEDIR_RO          32964
#define ID_STATUS_PANE0FILE_RO          32970
#define ID_STATUS_PANE1FILE_RO          32971
#define ID_STATUS_PANE2FILE_RO          32972
#define ID_STATUS_PANE0FILE_INFO        32973
#define ID_STATUS_PANE1FILE_INFO        32974
#define ID_STATUS_PANE2FILE_INFO        32975
#define ID_STATUS_PANE0FILE_EOL         32976
#define ID_STATUS_PANE1FILE_EOL         32977
#define ID_STATUS_PANE2FILE_EOL         32978
#define ID_STATUS_PANE0FILE_ENCODING    32979
#define ID_STATUS_PANE1FILE_ENCODING    32980
#define ID_STATUS_PANE2FILE_ENCODING    32981
#define ID_STATUS_FILTER                32982
#define ID_STATUS_PLUGIN                32983
#define ID_DIR_ZIP_LEFT                 32991
#define ID_DIR_ZIP_MIDDLE               32992
#define ID_DIR_ZIP_RIGHT                32993
#define ID_DIR_ZIP_BOTH                 32994
#define ID_DIR_ZIP_ALL                  32995
#define ID_DIR_ZIP_BOTH_DIFFS_ONLY      32996
#define ID_DIR_MOVE_LEFT_TO_RIGHT       32997
#define ID_DIR_MOVE_LEFT_TO_MIDDLE      32998
#define ID_DIR_MOVE_LEFT_TO_BROWSE      32999
#define ID_DIR_MOVE_MIDDLE_TO_LEFT      33000
#define ID_DIR_MOVE_MIDDLE_TO_RIGHT     33001
#define ID_DIR_MOVE_MIDDLE_TO_BROWSE    33002
#define ID_DIR_MOVE_RIGHT_TO_LEFT       33003
#define ID_DIR_MOVE_RIGHT_TO_MIDDLE     33004
#define ID_DIR_MOVE_RIGHT_TO_BROWSE     33005
#define ID_DIR_HIDE_FILENAMES           33006
#define ID_DIR_ITEM_RENAME              33007
#define ID_DIR_SHELL_CONTEXT_MENU_LEFT  33008
#define ID_DIR_SHELL_CONTEXT_MENU_MIDDLE 33009
#define ID_DIR_SHELL_CONTEXT_MENU_RIGHT 33010
#define ID_DISPLAY_MOVED_NONE           33111
#define ID_DISPLAY_MOVED_ALL            33112
#define ID_LOCBAR_GOTODIFF              33114
#define ID_FILE_OPENPROJECT             33116
#define ID_VIEW_SHOWHIDDENITEMS         33117
#define ID_FILE_SAVEPROJECT             33119
#define ID_FILE_ENCODING                33120
#define ID_FILE_OPENCONFLICT            33121
#define ID_LOAD_PROJECT                 33122
#define ID_SAVE_PROJECT                 33123
#define ID_PROJECT_DIFF_OPTIONS_WHITESPACE_COMPARE 33124
#define ID_PROJECT_DIFF_OPTIONS_WHITESPACE_IGNORE 33125
#define ID_PROJECT_DIFF_OPTIONS_WHITESPACE_IGNOREALL 33126
#define ID_PROJECT_DIFF_OPTIONS_IGNORE_BLANKLINES 33127
#define ID_PROJECT_DIFF_OPTIONS_IGNORE_CASE 33128
#define ID_PROJECT_DIFF_OPTIONS_IGNORE_EOL 33129
#define ID_PROJECT_DIFF_OPTIONS_IGNORE_NUMBERS 33130
#define ID_PROJECT_DIFF_OPTIONS_IGNORE_CODEPAGE 33131
#define ID_PROJECT_DIFF_OPTIONS_IGNORE_COMMENTS 33132
#define ID_PROJECT_DIFF_OPTIONS_COMPMETHOD_FULL_CONTENTS 33133
#define ID_PROJECT_DIFF_OPTIONS_COMPMETHOD_QUICK_CONTENTS 33134
#define ID_PROJECT_DIFF_OPTIONS_COMPMETHOD_BINARY_CONTENTS 33135
#define ID_PROJECT_DIFF_OPTIONS_COMPMETHOD_MODDATE 33136
#define ID_PROJECT_DIFF_OPTIONS_COMPMETHOD_DATESIZE 33137
#define ID_PROJECT_DIFF_OPTIONS_COMPMETHOD_SIZE 33138
#define ID_FILE_OPENCLIPBOARD           33140
#define ID_EDIT_TOGGLE_BOOKMARK         33145
#define ID_EDIT_GOTO_NEXT_BOOKMARK      33146
#define ID_EDIT_GOTO_PREV_BOOKMARK      33147
#define ID_EDIT_CLEAR_ALL_BOOKMARKS     33148
#define ID_VIEW_CHANGESCHEME            33150
#define ID_COLORSCHEME_FIRST            33151
#define IDS_COLORSCHEME_PLAIN           33151
#define IDS_COLORSCHEME_ABAP            33152
#define IDS_COLORSCHEME_ASP             33153
#define IDS_COLORSCHEME_AUTOIT          33154
#define IDS_COLORSCHEME_BASIC           33155
#define IDS_COLORSCHEME_BATCH           33156
#define IDS_COLORSCHEME_C               33157
#define IDS_COLORSCHEME_CSHARP          33158
#define IDS_COLORSCHEME_CSS             33159
#define IDS_COLORSCHEME_DCL             33160
#define IDS_COLORSCHEME_DLANG           33161
#define IDS_COLORSCHEME_FORTRAN         33162
#define IDS_COLORSCHEME_GO              33163
#define IDS_COLORSCHEME_HTML            33164
#define IDS_COLORSCHEME_INI             33165
#define IDS_COLORSCHEME_INNOSETUP       33166
#define IDS_COLORSCHEME_INSTALLSHIELD   33167
#define IDS_COLORSCHEME_JAVA            33168
#define IDS_COLORSCHEME_JAVASCRIPT      33169
#define IDS_COLORSCHEME_JSON            33170
#define IDS_COLORSCHEME_LISP            33171
#define IDS_COLORSCHEME_LUA             33172
#define IDS_COLORSCHEME_MATLAB          33173
#define IDS_COLORSCHEME_NSIS            33174
#define IDS_COLORSCHEME_PASCAL          33175
#define IDS_COLORSCHEME_PERL            33176
#define IDS_COLORSCHEME_PHP             33177
#define IDS_COLORSCHEME_PO              33178
#define IDS_COLORSCHEME_POWERSHELL      33179
#define IDS_COLORSCHEME_PYTHON          33180
#define IDS_COLORSCHEME_REXX            33181
#define IDS_COLORSCHEME_RSRC            33182
#define IDS_COLORSCHEME_RUBY            33183
#define IDS_COLORSCHEME_RUST            33184
#define IDS_COLORSCHEME_SGML            33185
#define IDS_COLORSCHEME_SH              33186
#define IDS_COLORSCHEME_SIOD            33187
#define IDS_COLORSCHEME_SMARTY          33188
#define IDS_COLORSCHEME_SQL             33189
#define IDS_COLORSCHEME_TCL             33190
#define IDS_COLORSCHEME_TEX             33191
#define IDS_COLORSCHEME_VERILOG         33192
#define IDS_COLORSCHEME_VHDL            33193
#define IDS_COLORSCHEME_XML             33194
#define ID_COLORSCHEME_LAST             33194
#define ID_TOOLBAR_NONE                 33195
#define ID_TOOLBAR_SMALL                33196
#define ID_TOOLBAR_BIG                  33197
#define ID_TOOLBAR_HUGE                 33198
#define ID_VIEW_RESIZE_PANES            33199
#define ID_VIEW_ZOOMIN                  33200
#define ID_VIEW_ZOOMOUT                 33201
#define ID_VIEW_ZOOMNORMAL              33202
#define ID_PLUGINS_LIST                 33203
#define ID_PREDIFFER_MANUAL             33204
#define ID_PREDIFFER_AUTO               33205
#define ID_VIEW_DIFFCONTEXT_ALL         33208
#define ID_VIEW_DIFFCONTEXT_0           33209
#define ID_VIEW_DIFFCONTEXT_1           33210
#define ID_VIEW_DIFFCONTEXT_3           33221
#define ID_VIEW_DIFFCONTEXT_5           33222
#define ID_VIEW_DIFFCONTEXT_7           33223
#define ID_VIEW_DIFFCONTEXT_9           33224
#define ID_VIEW_DIFFCONTEXT_TOGGLE      33225
#define ID_VIEW_DIFFCONTEXT_INVERT      33226
#define ID_VIEW_SPLITVERTICALLY         33228
#define ID_ADD_SYNCPOINT                33230
#define ID_CLEAR_SYNCPOINTS             33231
#define ID_CLOSE_OTHER_TABS             33232
#define ID_CLOSE_RIGHT_TABS             33233
#define ID_CLOSE_LEFT_TABS              33234
#define ID_COPY_TO_MIDDLE_L             33235
#define ID_COPY_TO_RIGHT_L              33236
#define ID_COPY_FROM_MIDDLE_L           33237
#define ID_COPY_FROM_RIGHT_L            33238
#define ID_COPY_TO_LEFT_M               33239
#define ID_COPY_TO_RIGHT_M              33240
#define ID_COPY_FROM_LEFT_M             33241
#define ID_COPY_FROM_RIGHT_M            33242
#define ID_COPY_TO_MIDDLE_R             33243
#define ID_COPY_TO_LEFT_R               33244
#define ID_COPY_FROM_MIDDLE_R           33245
#define ID_COPY_FROM_LEFT_R             33246
#define ID_COPY_FROM_LEFT               33247
#define ID_COPY_FROM_RIGHT              33248
#define ID_COPY_LINES_TO_MIDDLE_L       33251
#define ID_COPY_LINES_TO_RIGHT_L        33252
#define ID_COPY_LINES_FROM_MIDDLE_L     33253
#define ID_COPY_LINES_FROM_RIGHT_L      33254
#define ID_COPY_LINES_TO_LEFT_M         33255
#define ID_COPY_LINES_TO_RIGHT_M        33256
#define ID_COPY_LINES_FROM_LEFT_M       33257
#define ID_COPY_LINES_FROM_RIGHT_M      33258
#define ID_COPY_LINES_TO_MIDDLE_R       33259
#define ID_COPY_LINES_TO_LEFT_R         33260
#define ID_COPY_LINES_FROM_MIDDLE_R     33261
#define ID_COPY_LINES_FROM_LEFT_R       33262
#define ID_COPY_LINES_FROM_LEFT         33263
#define ID_COPY_LINES_FROM_RIGHT        33264
#define ID_LINES_L2R                    33265
#define ID_LINES_R2L                    33266
#define ID_TABBAR_AUTO_MAXWIDTH         33351
#define ID_IMG_VIEWDIFFERENCES          33353
#define ID_IMG_ZOOM_25                  33354
#define ID_IMG_ZOOM_50                  33355
#define ID_IMG_ZOOM_100                 33356
#define ID_IMG_ZOOM_200                 33357
#define ID_IMG_ZOOM_400                 33358
#define ID_IMG_ZOOM_800                 33359
#define ID_IMG_OVERLAY_NONE             33360
#define ID_IMG_OVERLAY_XOR              33361
#define ID_IMG_OVERLAY_ALPHABLEND       33362
#define ID_IMG_OVERLAY_ALPHABLEND_ANIM  33363
#define ID_IMG_DIFFBLOCKSIZE_1          33364
#define ID_IMG_DIFFBLOCKSIZE_2          33365
#define ID_IMG_DIFFBLOCKSIZE_4          33366
#define ID_IMG_DIFFBLOCKSIZE_8          33367
#define ID_IMG_DIFFBLOCKSIZE_16         33368
#define ID_IMG_DIFFBLOCKSIZE_32         33369
#define ID_IMG_PREVPAGE                 33370
#define ID_IMG_NEXTPAGE                 33371
#define ID_IMG_USEBACKCOLOR             33374
#define ID_IMG_THRESHOLD_0              33375
#define ID_IMG_THRESHOLD_2              33376
#define ID_IMG_THRESHOLD_4              33377
#define ID_IMG_THRESHOLD_8              33378
#define ID_IMG_THRESHOLD_16             33379
#define ID_IMG_THRESHOLD_32             33380
#define ID_IMG_THRESHOLD_64             33381
#define ID_IMG_INSERTIONDELETIONDETECTION_NONE 33382
#define ID_IMG_INSERTIONDELETIONDETECTION_VERTICAL 33383
#define ID_IMG_INSERTIONDELETIONDETECTION_HORIZONTAL 33384
#define ID_IMG_DRAGGINGMODE_NONE        33385
#define ID_IMG_DRAGGINGMODE_MOVE        33386
#define ID_IMG_DRAGGINGMODE_ADJUST_OFFSET 33387
#define ID_IMG_DRAGGINGMODE_VERTICAL_WIPE 33388
#define ID_IMG_DRAGGINGMODE_HORIZONTAL_WIPE 33389
#define ID_IMG_DRAGGINGMODE_RECTANGLE_SELECT 33390
#define ID_IMG_CURPANE_ROTATE_RIGHT_90  33391
#define ID_IMG_CURPANE_ROTATE_LEFT_90   33392
#define ID_IMG_CURPANE_FLIP_VERTICALLY  33393
#define ID_IMG_CURPANE_FLIP_HORIZONTALLY 33394
#define ID_IMG_CURPANE_PREVPAGE         33395
#define ID_IMG_CURPANE_NEXTPAGE         33396
#define ID_HELP_RELEASENOTES            33401
#define ID_HELP_TRANSLATIONS            33402
#define ID_HELP_CHECKFORUPDATES         33403
#define ID_FILE_SHELLMENU               33659
#define ID_MERGE_COMPARE_NONHORIZONTALLY 33660
#define ID_ACCEL_QUIT                   33661
#define ID_IMG_VECTORIMAGESCALING_25    33719
#define ID_IMG_VECTORIMAGESCALING_50    33720
#define ID_IMG_VECTORIMAGESCALING_100   33721
#define ID_IMG_VECTORIMAGESCALING_200   33722
#define ID_IMG_VECTORIMAGESCALING_400   33723
#define ID_IMG_VECTORIMAGESCALING_800   33724
#define ID_IMG_COMPARE_EXTRACTED_TEXT   33725
#define ID_WEB_SIZE_FIT_TO_WINDOW       33750
#define ID_WEB_SIZE_320x512             33751
#define ID_WEB_SIZE_375x600             33752
#define ID_WEB_SIZE_1024x640            33753
#define ID_WEB_SIZE_1280x800            33754
#define ID_WEB_SIZE_1440x900            33755
#define ID_WEB_COMPARE_SCREENSHOTS      33760
#define ID_WEB_COMPARE_FULLSIZE_SCREENSHOTS 33761
#define ID_WEB_COMPARE_HTMLS            33762
#define ID_WEB_COMPARE_TEXTS            33763
#define ID_WEB_COMPARE_RESOURCETREES    33764
#define ID_WEB_CLEAR_DISK_CACHE         33765
#define ID_WEB_CLEAR_COOKIES            33766
#define ID_WEB_CLEAR_BROWSING_HISTORY   33767
#define ID_WEB_CLEAR_ALL_PROFILE        33768
#define ID_FILE_NEW_TABLE               34164
#define ID_FILE_NEW_HEX                 34165
#define ID_FILE_NEW_IMAGE               34166
#define ID_FILE_NEW_WEBPAGE             34167
#define ID_FILE_NEW3_TABLE              34168
#define ID_FILE_NEW3_HEX                34169
#define ID_FILE_NEW3_IMAGE              34170
#define ID_FILE_NEW3_WEBPAGE            34171
#define ID_SWAPPANES_SWAP12             34172
#define ID_SWAPPANES_SWAP23             34173
#define ID_SWAPPANES_SWAP13             34174
#define ID_ADD_TO_IGNORED_SUBSTITUTIONS 34175
#define ID_ADD_TO_LINE_FILTERS          34176
#define ID_FIRSTFILE                    34182
#define ID_PREVFILE                     34183
#define ID_NEXTFILE                     34184
#define ID_LASTFILE                     34185
#define ID_USE_FIRST_LINE_AS_HEADERS    34190
#define ID_AUTO_FIT_ALL_COLUMNS         34191
#define ID_UNPACKERS_FIRST              35001
#define ID_UNPACKERS_LAST               35200
#define ID_PREDIFFERS_FIRST             35201
#define ID_PREDIFFERS_LAST              35300
#define ID_SCRIPT_FIRST                 35301
#define ID_SCRIPT_LAST                  35400
#define ID_FILE_PROJECT_MRU_FIRST       35401
#define ID_FILE_PROJECT_MRU_LAST        35450
#define ID_NO_MRU                       35451
#define ID_MRU_FIRST                    35452
#define ID_MRU_LAST                     35500
#define IDS_SPLASH_GPLTEXT              38977
#define IDS_MESSAGEBOX_OK               39001
#define IDS_MESSAGEBOX_CANCEL           39002
#define IDS_MESSAGEBOX_ABORT            39003
#define IDS_MESSAGEBOX_RETRY            39004
#define IDS_MESSAGEBOX_IGNORE           39005
#define IDS_MESSAGEBOX_IGNOREALL        39006
#define IDS_MESSAGEBOX_YES              39007
#define IDS_MESSAGEBOX_YES_TO_ALL       39008
#define IDS_MESSAGEBOX_NO               39009
#define IDS_MESSAGEBOX_NO_TO_ALL        39010
#define IDS_MESSAGEBOX_CONTINUE         39011
#define IDS_MESSAGEBOX_SKIP             39012
#define IDS_MESSAGEBOX_SKIPALL          39013
#define IDS_MESSAGEBOX_HELP             39014
#define IDS_MESSAGEBOX_DONT_DISPLAY_AGAIN 39015
#define IDS_MESSAGEBOX_DONT_ASK_AGAIN   39016
#define IDS_MESSAGEBOX_CHECKBOX_TOOLTIP 39017
#define IDS_OPTIONSPG_GENERAL           39041
#define IDS_OPTIONSPG_COMPARE           39042
#define IDS_OPTIONSPG_EDITOR            39043
#define IDS_OPTIONSPG_COLORS            39044
#define IDS_OPTIONSPG_TEXTCOLORS        39045
#define IDS_OPTIONSPG_SYNTAXCOLORS      39046
#define IDS_OPTIONSPG_MARKERCOLORS      39047
#define IDS_OPTIONSPG_SYSTEM            39048
#define IDS_OPTIONSPG_CODEPAGE          39050
#define IDS_OPTIONSPG_ARCHIVE           39051
#define IDS_OPTIONSPG_BACKUPS           39052
#define IDS_OPTIONSPG_SHELL             39053
#define IDS_OPTIONSPG_MERGECOLORS       39054
#define IDS_OPTIONSPG_GENCOMPARE        39055
#define IDS_OPTIONSPG_FOLDERCOMPARE     39056
#define IDS_OPTIONSPG_TABLECOMPARE      39057
#define IDS_OPTIONSPG_BINARYCOMPARE     39058
#define IDS_OPTIONSPG_IMAGECOMPARE      39059
#define IDS_OPTIONSPG_WEBPAGECOMPARE    39060
#define IDS_OPTIONSPG_DIRCOLORS         39061
#define IDS_OPTIONSPG_COLOR_SCHEMES     39062
#define IDS_OPTIONSPG_GENEDITOR         39063
#define IDS_OPTIONSPG_EDITOR_SYNTAX     39064
#define IDS_OPTIONSPG_MESSAGEBOXES      39065
#define IDS_OPTIONSPG_PROJECT           39066
#define IDS_TO                          40000
#define IDS_FROM_LEFT                   40001
#define IDS_TO_LEFT                     40002
#define IDS_FROM_RIGHT                  40003
#define IDS_TO_RIGHT                    40004
#define IDS_FROM_MIDDLE                 40005
#define IDS_TO_MIDDLE                   40006
#define IDS_VERSION_FMT                 40385
#define IDS_WINX64                      40388
#define IDS_OPTIONS_TITLE               40400
#define IDS_MESSAGE_BOX_ARE_RESET       40401
#define IDS_OPTIONS_INVALID_TABSIZE     40404
#define IDS_OPEN_TITLE                  40416
#define IDS_PROGRAMFILES                40417
#define IDS_ALLFILES                    40418
#define IDS_PROJECTFILES                40419
#define IDS_PROJECTFILES_EXT            40420
#define IDS_INIFILES                    40421
#define IDS_FILTERFILE_NAMETITLE        40448
#define IDS_FILTERFILE_PATHTITLE        40449
#define IDS_FILTER_TITLE                40450
#define IDS_FILTER_PREFIX               40451
#define IDS_FILTERFILE_DESCTITLE        40452
#define IDS_FILEFILTER_SAVENEW          40453
#define IDS_FILEFILTER_FILEMASK         40454
#define IDS_FILEFILTER_TMPL_MISSING     40455
#define IDS_FILEFILTER_TMPL_COPY        40456
#define IDS_FILEFILTER_NO_USERFOLDER    40457
#define IDS_FILEFILTER_DELETE_FAIL      40458
#define IDS_FILEFILTER_INSTALL          40459
#define IDS_FILEFILTER_INSTALLFAIL      40460
#define IDS_FILEFILTER_OVERWRITE        40461
#define IDS_FILTERLINE_REGEXP           40480
#define IDS_FILTERCHANGED               40496
#define IDS_DIRECTORY_WINDOW_TITLE      40800
#define IDS_FILE_COMPARISON_TITLE       40801
#define IDS_EMPTY_LEFT_FILE             40802
#define IDS_EMPTY_MIDDLE_FILE           40803
#define IDS_EMPTY_RIGHT_FILE            40804
#define IDS_CONFLICT_BASE_FILE          40805
#define IDS_CONFLICT_THEIRS_FILE        40806
#define IDS_CONFLICT_MINE_FILE          40807
#define IDS_SELFCOMPARE_ORIGINAL_FILE   40808
#define IDS_LINE_STATUS_INFO_SEL        40831
#define IDS_LINE_STATUS_INFO_EOL        40832
#define IDS_EMPTY_LINE_STATUS_INFO      40833
#define IDS_LINE_STATUS_INFO            40834
#define IDS_MERGEMODE_MERGING           40835
#define IDS_DIFF_NUMBER_STATUS_FMT      40836
#define IDS_NO_DIFF_SEL_FMT             40837
#define IDS_1_DIFF_FOUND                40838
#define IDS_STATUSBAR_READONLY          40839
#define IDS_DIRVIEW_STATUS_FMT_FOCUS    40840
#define IDS_DIRVIEW_STATUS_FMT_NOFOCUS  40841
#define IDS_ERROR_INCOMPARABLE          41200
#define IDS_DIRSEL_TAG                  41201
#define IDS_OPEN_FILESDIRS              41202
#define IDS_OPEN_LEFTINVALID            41203
#define IDS_OPEN_MIDDLEINVALID          41204
#define IDS_OPEN_RIGHTINVALID2          41205
#define IDS_OPEN_BOTHINVALID            41206
#define IDS_OPEN_LEFTMIDDLEINVALID      41207
#define IDS_OPEN_LEFTRIGHTINVALID       41208
#define IDS_OPEN_MIDDLERIGHTINVALID     41209
#define IDS_OPEN_ALLINVALID             41210
#define IDS_OPEN_UNPACKERDISABLED       41211
#define IDS_OPEN_MISMATCH               41212
#define IDS_OPEN_RIGHTINVALID3          41213
#define IDS_ERROR_FILE_NOT_FOUND        41216
#define IDS_ERROR_FILE_NOT_UNPACKED     41217
#define IDS_ERROR_FILEOPEN              41221
#define IDS_ERROR_CONF_RESOLVE          41222
#define IDS_NOT_CONFLICT_FILE           41223
#define IDS_SAVE_AS_TITLE               41232
#define IDS_SAVE_FMT                    41233
#define IDS_SAVEREADONLY_FMT            41234
#define IDS_ERROR_BACKUP                41236
#define IDS_BACKUP_FAILED_PROMPT        41237
#define IDS_FILESAVE_FAILED             41238
#define IDS_FILEPACK_FAILED_LEFT        41239
#define IDS_FILEPACK_FAILED_MIDDLE      41240
#define IDS_FILEPACK_FAILED_RIGHT       41241
#define IDS_FILECHANGED_ONDISK          41242
#define IDS_SAVEREADONLY_MULTI          41243
#define IDS_FILECHANGED_RESCAN          41244
#define IDS_SAVE_LEFT_AS                41245
#define IDS_SAVE_MIDDLE_AS              41246
#define IDS_SAVE_RIGHT_AS               41247
#define IDS_FILE_DISAPPEARED            41248
#define IDS_VIEWS_OUTOFSYNC             41300
#define IDS_COPY_RIGHT_TO_LEFT          41620
#define IDS_COPY_RIGHT_TO_MIDDLE        41621
#define IDS_COPY_MIDDLE_TO_LEFT         41622
#define IDS_COPY_MIDDLE_TO_RIGHT        41623
#define IDS_COPY_LEFT_TO_RIGHT          41624
#define IDS_COPY_LEFT_TO_MIDDLE         41625
#define IDS_COPY_RIGHT_TO_LEFT2         41626
#define IDS_COPY_RIGHT_TO_MIDDLE2       41627
#define IDS_COPY_MIDDLE_TO_LEFT2        41628
#define IDS_COPY_MIDDLE_TO_RIGHT2       41629
#define IDS_COPY_LEFT_TO_RIGHT2         41630
#define IDS_COPY_LEFT_TO_MIDDLE2        41631
#define IDS_COPY_LEFT_TO                41632
#define IDS_COPY_MIDDLE_TO              41633
#define IDS_COPY_RIGHT_TO               41634
#define IDS_COPY_BOTH_TO                41635
#define IDS_COPY_ALL_TO                 41638
#define IDS_COPY_DIFFERENCES_TO         41639
#define IDS_COPY_LEFT_TO2               41640
#define IDS_COPY_MIDDLE_TO2             41641
#define IDS_COPY_RIGHT_TO2              41642
#define IDS_COPY_BOTH_TO2               41643
#define IDS_COPY_ALL_TO2                41645
#define IDS_COPY_DIFFERENCES_TO2        41646
#define IDS_DEL_LEFT_FMT                41671
#define IDS_DEL_MIDDLE_FMT              41672
#define IDS_DEL_RIGHT_FMT               41673
#define IDS_DEL_BOTH_FMT                41674
#define IDS_DEL_ALL_FMT                 41675
#define IDS_DEL_LEFT_FMT2               41676
#define IDS_DEL_MIDDLE_FMT2             41677
#define IDS_DEL_RIGHT_FMT2              41678
#define IDS_DEL_BOTH_FMT2               41679
#define IDS_DEL_ALL_FMT2                41680
#define IDS_MOVE_LEFT_TO                41681
#define IDS_MOVE_MIDDLE_TO              41682
#define IDS_MOVE_RIGHT_TO               41683
#define IDS_MOVE_LEFT_TO2               41684
#define IDS_MOVE_MIDDLE_TO2             41685
#define IDS_MOVE_RIGHT_TO2              41686
#define IDS_SELECT_DEST_LEFT            41687
#define IDS_SELECT_DEST_MIDDLE          41688
#define IDS_SELECT_DEST_RIGHT           41689
#define IDS_FILES_AFFECTED_FMT          41690
#define IDS_FILES_AFFECTED_FMT2         41691
#define IDS_CONFIRM_DELETE_SINGLE       41692
#define IDS_CONFIRM_SINGLE_COPY         41693
#define IDS_CONFIRM_MULTIPLE_COPY       41694
#define IDS_DIRCMP_NOTSYNC              41695
#define IDS_CONFIRM_SINGLE_MOVE         41696
#define IDS_CONFIRM_MULTIPLE_MOVE       41697
#define IDS_CONFIRM_COPY_CAPTION        41698
#define IDS_CONFIRM_MOVE_CAPTION        41699
#define IDS_CONFIRM_CLOSE_WINDOW        41700
#define IDS_ERROR_INVALID_DIR_FILE_NAME 41701
#define IDS_ERROR_EXECUTE_FILE          41719
#define IDS_UNKNOWN_ARCHIVE_FORMAT      41731
#define IDS_FAILED_EXTRACT_ARCHIVE_FILES 41732
#define IDS_COLHDR_FILENAME             41751
#define IDS_COLHDR_DIR                  41752
#define IDS_COLHDR_RESULT               41753
#define IDS_COLHDR_LTIMEM               41754
#define IDS_COLHDR_RTIMEM               41755
#define IDS_COLHDR_MTIMEM               41756
#define IDS_COLHDR_EXTENSION            41757
#define IDS_COLHDR_LSIZE                41758
#define IDS_COLHDR_RSIZE                41759
#define IDS_COLHDR_MSIZE                41760
#define IDS_COLHDR_RSIZE_SHORT          41761
#define IDS_COLHDR_LSIZE_SHORT          41762
#define IDS_COLHDR_MSIZE_SHORT          41763
#define IDS_COLHDR_LTIMEC               41781
#define IDS_COLHDR_RTIMEC               41782
#define IDS_COLHDR_MTIMEC               41783
#define IDS_COLHDR_NEWER                41784
#define IDS_COLHDR_LVERSION             41785
#define IDS_COLHDR_RVERSION             41786
#define IDS_COLHDR_MVERSION             41787
#define IDS_COLHDR_RESULT_ABBR          41788
#define IDS_COLHDR_LATTRIBUTES          41789
#define IDS_COLHDR_RATTRIBUTES          41790
#define IDS_COLHDR_MATTRIBUTES          41791
#define IDS_COLHDR_LEOL_TYPE            41792
#define IDS_COLHDR_MEOL_TYPE            41793
#define IDS_COLHDR_REOL_TYPE            41794
#define IDS_COLHDR_LENCODING            41811
#define IDS_COLHDR_RENCODING            41812
#define IDS_COLHDR_MENCODING            41813
#define IDS_COLHDR_NIDIFFS              41814
#define IDS_COLHDR_NSDIFFS              41815
#define IDS_COLHDR_BINARY               41816
#define IDS_COLHDR_UNPACKER             41817
#define IDS_COLHDR_PREDIFFER            41818
#define IDS_COLHDR_LEFT                 41819
#define IDS_COLHDR_MIDDLE               41820
#define IDS_COLHDR_RIGHT                41821
#define IDS_COLHDR_DIFF                 41822
#define IDS_COLHDR_LEFT_DUPLICATE       41823
#define IDS_COLHDR_RIGHT_DUPLICATE      41824
#define IDS_COLHDR_MIDDLE_DUPLICATE     41825
#define IDS_COLHDR_MOVE                 41826
#define IDS_HASH_GROUP                  41827
#define IDS_CANT_COMPARE_FILES          41831
#define IDS_ABORTED_ITEM                41832
#define IDS_FILE_SKIPPED                41833
#define IDS_DIR_SKIPPED                 41834
#define IDS_LEFT_ONLY_IN_FMT            41835
#define IDS_MIDDLE_ONLY_IN_FMT          41836
#define IDS_RIGHT_ONLY_IN_FMT           41837
#define IDS_DOES_NOT_EXIST_IN_FMT       41838
#define IDS_BIN_FILES_SAME              41839
#define IDS_IDENTICAL                   41840
#define IDS_BIN_FILES_DIFF              41841
#define IDS_FILES_ARE_DIFFERENT         41842
#define IDS_FOLDERS_ARE_DIFFERENT       41843
#define IDS_LEFTONLY                    41844
#define IDS_RIGHTONLY                   41845
#define IDS_MIDDLEONLY                  41846
#define IDS_NOITEMLEFT                  41847
#define IDS_NOITEMRIGHT                 41848
#define IDS_NOITEMMIDDLE                41849
#define IDS_DIFFERENT                   41850
#define IDS_CMPRES_ERROR                41851
#define IDS_TEXT_FILES_SAME             41852
#define IDS_TEXT_FILES_DIFF             41861
#define IDS_LEFTONLY_DIFF               41862
#define IDS_MIDDLEONLY_DIFF             41863
#define IDS_RIGHTONLY_DIFF              41864
#define IDS_IMAGE_FILES_SAME            41865
#define IDS_IMAGE_FILES_DIFF            41866
#define IDS_ELAPSED_TIME                41881
#define IDS_STATUS_SELITEM1             41882
#define IDS_STATUS_SELITEMS             41883
#define IDS_COLDESC_FILENAME            41901
#define IDS_COLDESC_DIR                 41902
#define IDS_COLDESC_RESULT              41903
#define IDS_COLDESC_LTIMEM              41904
#define IDS_COLDESC_RTIMEM              41905
#define IDS_COLDESC_MTIMEM              41906
#define IDS_COLDESC_EXTENSION           41907
#define IDS_COLDESC_LSIZE               41908
#define IDS_COLDESC_RSIZE               41909
#define IDS_COLDESC_MSIZE               41910
#define IDS_COLDESC_LSIZE_SHORT         41911
#define IDS_COLDESC_RSIZE_SHORT         41912
#define IDS_COLDESC_MSIZE_SHORT         41913
#define IDS_COLDESC_LTIMEC              41914
#define IDS_COLDESC_RTIMEC              41915
#define IDS_COLDESC_MTIMEC              41916
#define IDS_COLDESC_NEWER               41917
#define IDS_COLDESC_LVERSION            41918
#define IDS_COLDESC_RVERSION            41919
#define IDS_COLDESC_MVERSION            41920
#define IDS_COLDESC_RESULT_ABBR         41921
#define IDS_COLDESC_LATTRIBUTES         41922
#define IDS_COLDESC_RATTRIBUTES         41923
#define IDS_COLDESC_MATTRIBUTES         41924
#define IDS_COLDESC_LEOL_TYPE           41925
#define IDS_COLDESC_REOL_TYPE           41926
#define IDS_COLDESC_MEOL_TYPE           41927
#define IDS_COLDESC_LENCODING           41941
#define IDS_COLDESC_RENCODING           41942
#define IDS_COLDESC_MENCODING           41943
#define IDS_COLDESC_NIDIFFS             41944
#define IDS_COLDESC_NSDIFFS             41945
#define IDS_COLDESC_BINARY              41946
#define IDS_COLDESC_UNPACKER            41947
#define IDS_COLDESC_PREDIFFER           41948
#define IDS_PRPCAT_SYSTEM               41950
#define IDS_PRPCAT_AUDIO                41951
#define IDS_PRPCAT_CALENDAR             41952
#define IDS_PRPCAT_COMMUNICATION        41953
#define IDS_PRPCAT_CONTACT              41954
#define IDS_PRPCAT_DEVICES              41955
#define IDS_PRPCAT_DOCUMENT             41956
#define IDS_PRPCAT_HOME                 41957
#define IDS_PRPCAT_IMAGE                41958
#define IDS_PRPCAT_JOURNAL              41959
#define IDS_PRPCAT_LINK                 41960
#define IDS_PRPCAT_MEDIA                41961
#define IDS_PRPCAT_MESSAGE              41962
#define IDS_PRPCAT_MUSIC                41963
#define IDS_PRPCAT_NOTE                 41964
#define IDS_PRPCAT_PHOTO                41965
#define IDS_PRPCAT_RECORDEDTV           41966
#define IDS_PRPCAT_SEARCH               41967
#define IDS_PRPCAT_SECURITY             41968
#define IDS_PRPCAT_SOFTWARE             41969
#define IDS_PRPCAT_TASK                 41970
#define IDS_PRPCAT_VIDEO                41971
#define IDS_PRPCAT_HASH                 41972
#define IDS_DIRECTORY_REPORT_TITLE      41980
#define IDS_DIRECTORY_REPORT_TITLE3     41981
#define IDS_REPORT_COMMALIST            41990
#define IDS_REPORT_TABLIST              41991
#define IDS_REPORT_SIMPLEHTML           41992
#define IDS_REPORT_SIMPLEXML            41993
#define IDS_REPORT_FILEOVERWRITE        41994
#define IDS_REPORT_ERROR                41995
#define IDS_REPORT_SUCCESS              41996
#define IDS_SYNCPOINT_LASTBLOCK         42000
#define IDS_FILE_TO_ITSELF              42100
#define IDS_FILESSAME                   42101
#define IDS_FILEERROR                   42103
#define IDS_TEMP_FILEERROR              42105
#define IDS_SUGGEST_IGNOREEOL           42107
#define IDS_INVALID_DIRECTORY           42108
#define IDS_CANNOT_OPEN_BINARYFILE      42109
#define IDS_CREATE_PAIR_FOLDER          42110
#define IDS_MOVE_TO_NEXTFILE            42111
#define IDS_MOVE_TO_PREVFILE            42112
#define IDS_MOVE_TO_NEXTPAGE            42113
#define IDS_MOVE_TO_PREVPAGE            42114
#define IDS_MOVE_TO_FIRSTFILE           42115
#define IDS_MOVE_TO_LASTFILE            42116
#define IDS_SUGGEST_IGNORECODEPAGE      42131
#define IDS_LOSSY_TRANSCODING_FIRST     42132
#define IDS_LOSSY_TRANSCODING_SECOND    42133
#define IDS_LOSSY_TRANSCODING_THIRD     42134
#define IDS_LOSSY_TRANSCODING_BOTH      42135
#define IDS_LINEDIFF_NODIFF             42151
#define IDS_LINEDIFF_NODIFF_CAPTION     42152
#define IDS_NUM_REPLACED                42161
#define IDS_EDIT_TEXT_NOT_FOUND         42162
#define IDS_MERGE_MODE                  42181
#define IDS_LOCBAR_CAPTION              42201
#define IDS_DIFFBAR_CAPTION             42202
#define IDS_DIFF_SUCCEEDED              42400
#define IDS_DIFF_ITEM1NOTFOUND          42401
#define IDS_DIFF_ITEM2NOTFOUND          42402
#define IDS_DIFF_FILEOVERWRITE          42403
#define IDS_DIFF_SELECTEDFILES          42404
#define IDS_DIFF_NORMAL                 42405
#define IDS_DIFF_CONTEXT                42406
#define IDS_DIFF_UNIFIED                42407
#define IDS_DIFF_HTML                   42408
#define IDS_FILEWRITE_ERROR             42409
#define IDS_PATH_NOT_ABSOLUTE           42410
#define IDS_MUST_SPECIFY_OUTPUT         42411
#define IDS_CANNOT_CREATE_BINARYPATCH   42412
#define IDS_SAVEFILES_FORPATCH          42414
#define IDS_FOLDER_NOTEXIST             42415
#define IDS_NO_ZIP_SUPPORT              42449
#define IDS_OPT_EXPORT_CAPTION          42452
#define IDS_OPT_IMPORT_CAPTION          42453
#define IDS_OPT_IMPORT_DONE             42454
#define IDS_OPT_EXPORT_DONE             42455
#define IDS_OPT_IMPORT_ERR              42456
#define IDS_OPT_EXPORT_ERR              42457
#define IDS_CLOSEALL_WINDOWS            42458
#define IDS_BREAK_ON_WHITESPACE         42491
#define IDS_BREAK_ON_PUNCTUATION        42492
#define IDS_UNK_ERROR_READING_PROJECT   42510
#define IDS_UNK_ERROR_SAVING_PROJECT    42511
#define IDS_PROJFILE_LOAD_SUCCESS       42513
#define IDS_PROJFILE_SAVE_SUCCESS       42514
#define IDS_TEXT_REPORT_FILES           42540
#define IDS_HTML_REPORT_FILES           42541
#define IDS_XML_REPORT_FILES            42542
#define IDS_LOCBAR_GOTOLINE_FMT         43115
#define IDS_AUTOCOMPLETE_DISABLED       43142
#define IDS_AUTOCOMPLETE_FILE_SYS       43143
#define IDS_AUTOCOMPLETE_MRU            43144
#define IDS_FRHED_NOTINSTALLED          43229
#define IDS_AUTO_MERGE                  43241
#define IDS_CODEPAGE_MERGED             43244
#define IDS_CODEPAGE_CONFLICT           43245
#define IDS_EOL_MERGED                  43246
#define IDS_EOL_CONFLICT                43247
#define IDS_IMAGE_MENU                  43352
#define IDS_WEBPAGE_MENU                43353
#define IDS_VIEW_WRAP_TEXT              43354
#define IDS_EOL_DOS                     43400
#define IDS_EOL_MAC                     43401
#define IDS_EOL_UNIX                    43402
#define IDS_EOL_MIXED                   43403
#define IDS_EOL_BIN                     43404
#define IDS_EOL_LF                      43405
#define IDS_EOL_CR                      43406
#define IDS_EOL_CRLF                    43407
#define IDS_EOL_NONE                    43408
#define IDS_MARKER_COLOR_FMT            43409
#define IDS_MARKER_NEW_PATTERN          43410
#define IDS_PLUGINSLIST_NAME            43432
#define IDS_PLUGINSLIST_TYPE            43433
#define IDS_PLUGINSLIST_DESC            43434
#define IDS_PLUGINS_TYPE_UNPACKER       43435
#define IDS_PLUGINS_TYPE_PREDIFFER      43436
#define IDS_PLUGINS_TYPE_EDITSCRIPT     43437
#define IDS_GOTO_MOVED_LINE             43438
#define IDS_COMPMETHOD_FULL_CONTENTS    43490
#define IDS_COMPMETHOD_QUICK_CONTENTS   43491
#define IDS_COMPMETHOD_BINARY_CONTENTS  43492
#define IDS_COMPMETHOD_MODDATE          43493
#define IDS_COMPMETHOD_DATESIZE         43494
#define IDS_COMPMETHOD_SIZE             43495
#define IDS_SYNTAXTABLE_FILETYPE        43496
#define IDS_SYNTAXTABLE_EXTENSION       43497
#define IDS_UNPACK_AUTO                 43498
#define IDS_MESSAGEBOX_MESSAGE          43499
#define IDS_MESSAGEBOX_ANSWER           43500
#define IDS_NO_PREDIFFER                43501
#define IDS_SUGGESTED_PLUGINS           43502
#define IDS_NOT_SUGGESTED_PLUGINS       43503
#define IDS_PRIVATEBUILD_FMT            43504
#define IDS_PROJECT_ITEM                43505
#define IDS_PROJECT_OPEN                43506
#define IDS_PROJECT_LOAD                43507
#define IDS_PROJECT_SAVE                43508
#define IDS_PROJECT_ITEM_FILE_FILTER    43509
#define IDS_PROJECT_ITEM_INCLUDE_SUBFOLDERS 43510
#define IDS_PROJECT_ITEM_PLUGIN         43511
#define IDS_PROJECT_ITEM_COMPARE_OPTIONS 43512
#define IDS_CHECKFORUPDATES_UPTODATE    43521
#define IDS_CHECKFORUPDATES_NEWVERSION  43522
#define IDS_CHECKFORUPDATES_FAILED      43523
#define IDS_TITLE_PLUGINS_SETTINGS      43524
#define IDS_NO_EDIT_SCRIPTS             43525
#define IDS_NO_SCT_SCRIPTS              43541
#define IDS_USERCHOICE_NONE             43542
#define IDS_USERCHOICE_AUTOMATIC        43543
#define IDS_CLOSE_LEFT_TABS             43544
#define IDS_CLOSE_RIGHT_TABS            43545
#define IDS_CLOSE_OTHER_TABS            43644
#define IDS_TABBAR_AUTO_MAXWIDTH        43645
#define IDS_CREATE_FOLDER               43657
#define IDS_CREATE_FOLDER_ERROR         43658
#define IDS_DIFF_ALGORITHM_DEFAULT      43700
#define IDS_DIFF_ALGORITHM_MINIMAL      43701
#define IDS_DIFF_ALGORITHM_PATIENCE     43702
#define IDS_DIFF_ALGORITHM_HISTOGRAM    43703
#define IDS_DIFF_ALGORITHM_NONE         43704
#define IDS_RENDERING_MODE_GDI          43710
#define IDS_RENDERING_MODE_DIRECTWRITE_DEFAULT 43711
#define IDS_RENDERING_MODE_DIRECTWRITE_ALIASED 43712
#define IDS_RENDERING_MODE_DIRECTWRITE_GDI_CLASSIC 43713
#define IDS_RENDERING_MODE_DIRECTWRITE_GDI_NATURAL 43714
#define IDS_RENDERING_MODE_DIRECTWRITE_NATURAL 43715
#define IDS_RENDERING_MODE_DIRECTWRITE_NATURAL_SYMMETRIC 43716
#define IDS_CLOSE_WINDOWS_WITH_ESC_1    43717
#define IDS_CLOSE_WINDOWS_WITH_ESC_2    43718
#define IDS_CLOSE_WINDOWS_WITH_ESC_3    43719
#define IDS_DIFF_GROUP                  44131
#define IDS_DIFF_HIGHLIGHT              44132
#define IDS_DIFF_BLINK                  44133
#define IDS_DIFF_BLOCKSIZE              44134
#define IDS_DIFF_BLOCKALPHA             44135
#define IDS_DIFF_CDTHRESHOLD            44136
#define IDS_DIFF_INSERTION_DELETION_DETECTION 44137
#define IDS_DIFF_INSERTION_DELETION_DETECTION_NONE 44138
#define IDS_DIFF_INSERTION_DELETION_DETECTION_VERTICAL 44139
#define IDS_DIFF_INSERTION_DELETION_DETECTION_HORIZONTAL 44140
#define IDS_OVERLAY_GROUP               44141
#define IDS_OVERLAY_ALPHA               44142
#define IDS_OVERLAY_MODE_NONE           44143
#define IDS_OVERLAY_MODE_XOR            44144
#define IDS_OVERLAY_MODE_ALPHA          44145
#define IDS_OVERLAY_MODE_ALPHA_ANIMATION 44146
#define IDS_ZOOM                        44147
#define IDS_PAGE                        44148
#define IDS_IMGCMP_STATUS_PT_RGBA_FMT   44149
#define IDS_IMGCMP_STATUS_DIST1_FMT     44150
#define IDS_IMGCMP_STATUS_DIST2_FMT     44151
#define IDS_IMGCMP_STATUS_PAGE_ZOOM_SIZE_BPP_FMT 44152
#define IDS_IMGCMP_STATUS_RC_FMT        44153
#define IDS_IMGCMP_STATUS_FLIPPED_FMT   44154
#define IDS_IMGCMP_STATUS_ROTATED_FMT   44155
#define IDS_IMGCMP_REPORT_ALLPAGES      44156
#define IDS_COMPARE_LARGE_FILES         44165
#define IDS_OCRRESULT_TEXTONLY          44166
#define IDS_OCRRESULT_POS_LINE          44167
#define IDS_OCRRESULT_POS_WORD          44168
#define IDS_USERDATAFOLDER_APPDATA      44169
#define IDS_USERDATAFOLDER_INSTALL      44170
#define IDS_IGNSUB_STR1                 44174
#define IDS_IGNSUB_STR2                 44175
#define IDS_IGNSUB_STR3                 44176
#define IDS_IGNSUB_STR4                 44177
#define IDS_IGNSUB_STR5                 44178
#define IDS_SINGLEINSTANCE_STR1         44179
#define IDS_SINGLEINSTANCE_STR2         44180
#define IDS_AUTO_RELOAD_MODIFIED_FILES_STR1 44181
#define IDS_AUTO_RELOAD_MODIFIED_FILES_STR2 44182
#define IDS_PLUGIN_ALL                  44200
#define IDS_PLUGIN_OTHERS               44201
#define IDS_PLUGIN_MISSING_PLUGIN_NAME  44490
#define IDS_PLUGIN_MISSING_QUOTATION_MARK 44491
#define IDS_PLUGIN_TITLE1               44492
#define IDS_L2M                         44500
#define IDS_R2M                         44501
#define IDS_COPY_FROM_MIDDLE_R          44502
#define IDS_COPY_FROM_MIDDLE_L          44503
#define IDS_L2MNEXT                     44504
#define IDS_R2MNEXT                     44505
#define IDS_ALL_MIDDLE                  44506
#define IDS_FILTER_APPLIED              44507
#define IDS_CLIPBOARDHISTORY_TIME       44510
#define IDS_CLIPBOARDHISTORY_DISABLED   44511
#define IDS_CLIPBOARDHISTORY_NOT_SUPPORTED1 44512
#define IDS_CLIPBOARDHISTORY_NOT_SUPPORTED2 44513
#define IDS_WEBVIEW2_RUNTIME_NOT_INSTALLED 44514
#define IDS_PROJECT_ITEM_HIDDEN_ITEMS   44515
#define IDS_CONFIRM_COPY_ALL_DIFFS      44516
#define IDS_JUMPLIST_NEW_TEXT_COMPARE   44520
#define IDS_JUMPLIST_NEW_TABLE_COMPARE  44521
#define IDS_JUMPLIST_NEW_BINARY_COMPARE 44522
#define IDS_JUMPLIST_NEW_IMAGE_COMPARE  44523
#define IDS_JUMPLIST_NEW_WEBPAGE_COMPARE 44524
#define IDS_JUMPLIST_CLIPBOARD_COMPARE  44525

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        258
#define _APS_NEXT_COMMAND_VALUE         34194
#define _APS_NEXT_CONTROL_VALUE         1632
#define _APS_NEXT_SYMED_VALUE           118
#endif
#endif
